// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/personal_notification/personal_notification_service.proto

package personal_notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchResponse struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	UnreadNotifications *entity.PersonalNotification `protobuf:"bytes,1,opt,name=unread_notifications,json=unreadNotifications,proto3" json:"unread_notifications,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_app_personal_notification_personal_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_personal_notification_personal_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_app_personal_notification_personal_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *FetchResponse) GetUnreadNotifications() *entity.PersonalNotification {
	if x != nil {
		return x.UnreadNotifications
	}
	return nil
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       []int64                `protobuf:"varint,1,rep,packed,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_app_personal_notification_personal_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_personal_notification_personal_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_app_personal_notification_personal_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimRequest) GetClaimId() []int64 {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

var File_app_personal_notification_personal_notification_service_proto protoreflect.FileDescriptor

const file_app_personal_notification_personal_notification_service_proto_rawDesc = "" +
	"\n" +
	"=app/personal_notification/personal_notification_service.proto\x12\x19app.personal_notification\x1a\"entity/personal_notification.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\rFetchResponse\x12O\n" +
	"\x14unread_notifications\x18\x01 \x01(\v2\x1c.entity.PersonalNotificationR\x13unreadNotifications\")\n" +
	"\fClaimRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x03(\x03R\aclaimId2\xb2\x01\n" +
	"\x1bPersonalNotificationService\x12I\n" +
	"\x05Fetch\x12\x16.google.protobuf.Empty\x1a(.app.personal_notification.FetchResponse\x12H\n" +
	"\x05Claim\x12'.app.personal_notification.ClaimRequest\x1a\x16.google.protobuf.EmptyB$\xaa\x02!App.Protobuf.PersonalNotificationb\x06proto3"

var (
	file_app_personal_notification_personal_notification_service_proto_rawDescOnce sync.Once
	file_app_personal_notification_personal_notification_service_proto_rawDescData []byte
)

func file_app_personal_notification_personal_notification_service_proto_rawDescGZIP() []byte {
	file_app_personal_notification_personal_notification_service_proto_rawDescOnce.Do(func() {
		file_app_personal_notification_personal_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_personal_notification_personal_notification_service_proto_rawDesc), len(file_app_personal_notification_personal_notification_service_proto_rawDesc)))
	})
	return file_app_personal_notification_personal_notification_service_proto_rawDescData
}

var file_app_personal_notification_personal_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_personal_notification_personal_notification_service_proto_goTypes = []any{
	(*FetchResponse)(nil),               // 0: app.personal_notification.FetchResponse
	(*ClaimRequest)(nil),                // 1: app.personal_notification.ClaimRequest
	(*entity.PersonalNotification)(nil), // 2: entity.PersonalNotification
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
}
var file_app_personal_notification_personal_notification_service_proto_depIdxs = []int32{
	2, // 0: app.personal_notification.FetchResponse.unread_notifications:type_name -> entity.PersonalNotification
	3, // 1: app.personal_notification.PersonalNotificationService.Fetch:input_type -> google.protobuf.Empty
	1, // 2: app.personal_notification.PersonalNotificationService.Claim:input_type -> app.personal_notification.ClaimRequest
	0, // 3: app.personal_notification.PersonalNotificationService.Fetch:output_type -> app.personal_notification.FetchResponse
	3, // 4: app.personal_notification.PersonalNotificationService.Claim:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_personal_notification_personal_notification_service_proto_init() }
func file_app_personal_notification_personal_notification_service_proto_init() {
	if File_app_personal_notification_personal_notification_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_personal_notification_personal_notification_service_proto_rawDesc), len(file_app_personal_notification_personal_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_personal_notification_personal_notification_service_proto_goTypes,
		DependencyIndexes: file_app_personal_notification_personal_notification_service_proto_depIdxs,
		MessageInfos:      file_app_personal_notification_personal_notification_service_proto_msgTypes,
	}.Build()
	File_app_personal_notification_personal_notification_service_proto = out.File
	file_app_personal_notification_personal_notification_service_proto_goTypes = nil
	file_app_personal_notification_personal_notification_service_proto_depIdxs = nil
}
