// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/exchange/exchange_service.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_app_exchange_exchange_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_exchange_exchange_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_app_exchange_exchange_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ExchangeRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_app_exchange_exchange_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_exchange_exchange_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_app_exchange_exchange_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_app_exchange_exchange_service_proto protoreflect.FileDescriptor

const file_app_exchange_exchange_service_proto_rawDesc = "" +
	"\n" +
	"#app/exchange/exchange_service.proto\x12\fapp.exchange\x1a\x19entity/notification.proto\"H\n" +
	"\x0fExchangeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"L\n" +
	"\x10ExchangeResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification2\\\n" +
	"\x0fExchangeService\x12I\n" +
	"\bExchange\x12\x1d.app.exchange.ExchangeRequest\x1a\x1e.app.exchange.ExchangeResponseB\x18\xaa\x02\x15App.Protobuf.Exchangeb\x06proto3"

var (
	file_app_exchange_exchange_service_proto_rawDescOnce sync.Once
	file_app_exchange_exchange_service_proto_rawDescData []byte
)

func file_app_exchange_exchange_service_proto_rawDescGZIP() []byte {
	file_app_exchange_exchange_service_proto_rawDescOnce.Do(func() {
		file_app_exchange_exchange_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_exchange_exchange_service_proto_rawDesc), len(file_app_exchange_exchange_service_proto_rawDesc)))
	})
	return file_app_exchange_exchange_service_proto_rawDescData
}

var file_app_exchange_exchange_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_exchange_exchange_service_proto_goTypes = []any{
	(*ExchangeRequest)(nil),     // 0: app.exchange.ExchangeRequest
	(*ExchangeResponse)(nil),    // 1: app.exchange.ExchangeResponse
	(*entity.Notification)(nil), // 2: entity.Notification
}
var file_app_exchange_exchange_service_proto_depIdxs = []int32{
	2, // 0: app.exchange.ExchangeResponse.notification:type_name -> entity.Notification
	0, // 1: app.exchange.ExchangeService.Exchange:input_type -> app.exchange.ExchangeRequest
	1, // 2: app.exchange.ExchangeService.Exchange:output_type -> app.exchange.ExchangeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_exchange_exchange_service_proto_init() }
func file_app_exchange_exchange_service_proto_init() {
	if File_app_exchange_exchange_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_exchange_exchange_service_proto_rawDesc), len(file_app_exchange_exchange_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_exchange_exchange_service_proto_goTypes,
		DependencyIndexes: file_app_exchange_exchange_service_proto_depIdxs,
		MessageInfos:      file_app_exchange_exchange_service_proto_msgTypes,
	}.Build()
	File_app_exchange_exchange_service_proto = out.File
	file_app_exchange_exchange_service_proto_goTypes = nil
	file_app_exchange_exchange_service_proto_depIdxs = nil
}
