// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: app/supportcard/supportcard_service.proto

package supportcard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupportCardService_LevelUp_FullMethodName = "/app.supportcard.SupportCardService/LevelUp"
	SupportCardService_RankUp_FullMethodName  = "/app.supportcard.SupportCardService/RankUp"
)

// SupportCardServiceClient is the client API for SupportCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupportCardServiceClient interface {
	LevelUp(ctx context.Context, in *LevelUpRequest, opts ...grpc.CallOption) (*LevelUpResponse, error)
	RankUp(ctx context.Context, in *RankUpRequest, opts ...grpc.CallOption) (*RankUpResponse, error)
}

type supportCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupportCardServiceClient(cc grpc.ClientConnInterface) SupportCardServiceClient {
	return &supportCardServiceClient{cc}
}

func (c *supportCardServiceClient) LevelUp(ctx context.Context, in *LevelUpRequest, opts ...grpc.CallOption) (*LevelUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LevelUpResponse)
	err := c.cc.Invoke(ctx, SupportCardService_LevelUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportCardServiceClient) RankUp(ctx context.Context, in *RankUpRequest, opts ...grpc.CallOption) (*RankUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankUpResponse)
	err := c.cc.Invoke(ctx, SupportCardService_RankUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportCardServiceServer is the server API for SupportCardService service.
// All implementations must embed UnimplementedSupportCardServiceServer
// for forward compatibility.
type SupportCardServiceServer interface {
	LevelUp(context.Context, *LevelUpRequest) (*LevelUpResponse, error)
	RankUp(context.Context, *RankUpRequest) (*RankUpResponse, error)
	mustEmbedUnimplementedSupportCardServiceServer()
}

// UnimplementedSupportCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupportCardServiceServer struct{}

func (UnimplementedSupportCardServiceServer) LevelUp(context.Context, *LevelUpRequest) (*LevelUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LevelUp not implemented")
}
func (UnimplementedSupportCardServiceServer) RankUp(context.Context, *RankUpRequest) (*RankUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankUp not implemented")
}
func (UnimplementedSupportCardServiceServer) mustEmbedUnimplementedSupportCardServiceServer() {}
func (UnimplementedSupportCardServiceServer) testEmbeddedByValue()                            {}

// UnsafeSupportCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupportCardServiceServer will
// result in compilation errors.
type UnsafeSupportCardServiceServer interface {
	mustEmbedUnimplementedSupportCardServiceServer()
}

func RegisterSupportCardServiceServer(s grpc.ServiceRegistrar, srv SupportCardServiceServer) {
	// If the following call pancis, it indicates UnimplementedSupportCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupportCardService_ServiceDesc, srv)
}

func _SupportCardService_LevelUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LevelUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportCardServiceServer).LevelUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportCardService_LevelUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportCardServiceServer).LevelUp(ctx, req.(*LevelUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportCardService_RankUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportCardServiceServer).RankUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportCardService_RankUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportCardServiceServer).RankUp(ctx, req.(*RankUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupportCardService_ServiceDesc is the grpc.ServiceDesc for SupportCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupportCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.supportcard.SupportCardService",
	HandlerType: (*SupportCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LevelUp",
			Handler:    _SupportCardService_LevelUp_Handler,
		},
		{
			MethodName: "RankUp",
			Handler:    _SupportCardService_RankUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/supportcard/supportcard_service.proto",
}
