// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/arena/arena_service.proto

package arena

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportPenaltyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Penalty       int32                  `protobuf:"varint,1,opt,name=penalty,proto3" json:"penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPenaltyRequest) Reset() {
	*x = ReportPenaltyRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPenaltyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPenaltyRequest) ProtoMessage() {}

func (x *ReportPenaltyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPenaltyRequest.ProtoReflect.Descriptor instead.
func (*ReportPenaltyRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReportPenaltyRequest) GetPenalty() int32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

type ReportPenaltyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPenaltyResponse) Reset() {
	*x = ReportPenaltyResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPenaltyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPenaltyResponse) ProtoMessage() {}

func (x *ReportPenaltyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPenaltyResponse.ProtoReflect.Descriptor instead.
func (*ReportPenaltyResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{1}
}

type ArenaTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArenaSeasonId int64                  `protobuf:"varint,1,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaTopRequest) Reset() {
	*x = ArenaTopRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaTopRequest) ProtoMessage() {}

func (x *ArenaTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaTopRequest.ProtoReflect.Descriptor instead.
func (*ArenaTopRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{2}
}

func (x *ArenaTopRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

type ArenaTopResponse struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	LatestStatus            *entity.ArenaTopLastStatus     `protobuf:"bytes,1,opt,name=latest_status,json=latestStatus,proto3" json:"latest_status,omitempty"`
	Mp                      int64                          `protobuf:"varint,2,opt,name=mp,proto3" json:"mp,omitempty"`
	Lp                      []*entity.ArenaLp              `protobuf:"bytes,3,rep,name=lp,proto3" json:"lp,omitempty"`
	DailyRewards            []*entity.ArenaTopDailyRewards `protobuf:"bytes,4,rep,name=daily_rewards,json=dailyRewards,proto3" json:"daily_rewards,omitempty"`
	PenaltyCount            int32                          `protobuf:"varint,5,opt,name=penalty_count,json=penaltyCount,proto3" json:"penalty_count,omitempty"`
	BeforeSeasonId          int64                          `protobuf:"varint,6,opt,name=before_season_id,json=beforeSeasonId,proto3" json:"before_season_id,omitempty"`
	IsShowSeasonResult      bool                           `protobuf:"varint,7,opt,name=is_show_season_result,json=isShowSeasonResult,proto3" json:"is_show_season_result,omitempty"`
	ArenaPromotionRewardIds []int64                        `protobuf:"varint,8,rep,packed,name=arena_promotion_reward_ids,json=arenaPromotionRewardIds,proto3" json:"arena_promotion_reward_ids,omitempty"`
	LpRankDiff              []*entity.ArenaLpRankDiff      `protobuf:"bytes,9,rep,name=lp_rank_diff,json=lpRankDiff,proto3" json:"lp_rank_diff,omitempty"`
	ArenaDedicatedDecks     []*entity.ArenaDedicatedDecks  `protobuf:"bytes,10,rep,name=arena_dedicated_decks,json=arenaDedicatedDecks,proto3" json:"arena_dedicated_decks,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ArenaTopResponse) Reset() {
	*x = ArenaTopResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaTopResponse) ProtoMessage() {}

func (x *ArenaTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaTopResponse.ProtoReflect.Descriptor instead.
func (*ArenaTopResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{3}
}

func (x *ArenaTopResponse) GetLatestStatus() *entity.ArenaTopLastStatus {
	if x != nil {
		return x.LatestStatus
	}
	return nil
}

func (x *ArenaTopResponse) GetMp() int64 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *ArenaTopResponse) GetLp() []*entity.ArenaLp {
	if x != nil {
		return x.Lp
	}
	return nil
}

func (x *ArenaTopResponse) GetDailyRewards() []*entity.ArenaTopDailyRewards {
	if x != nil {
		return x.DailyRewards
	}
	return nil
}

func (x *ArenaTopResponse) GetPenaltyCount() int32 {
	if x != nil {
		return x.PenaltyCount
	}
	return 0
}

func (x *ArenaTopResponse) GetBeforeSeasonId() int64 {
	if x != nil {
		return x.BeforeSeasonId
	}
	return 0
}

func (x *ArenaTopResponse) GetIsShowSeasonResult() bool {
	if x != nil {
		return x.IsShowSeasonResult
	}
	return false
}

func (x *ArenaTopResponse) GetArenaPromotionRewardIds() []int64 {
	if x != nil {
		return x.ArenaPromotionRewardIds
	}
	return nil
}

func (x *ArenaTopResponse) GetLpRankDiff() []*entity.ArenaLpRankDiff {
	if x != nil {
		return x.LpRankDiff
	}
	return nil
}

func (x *ArenaTopResponse) GetArenaDedicatedDecks() []*entity.ArenaDedicatedDecks {
	if x != nil {
		return x.ArenaDedicatedDecks
	}
	return nil
}

type ConsecutiveWinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArenaSeasonId int64                  `protobuf:"varint,1,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsecutiveWinsRequest) Reset() {
	*x = ConsecutiveWinsRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsecutiveWinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsecutiveWinsRequest) ProtoMessage() {}

func (x *ConsecutiveWinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsecutiveWinsRequest.ProtoReflect.Descriptor instead.
func (*ConsecutiveWinsRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConsecutiveWinsRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

type ConsecutiveWinsResponse struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	ArenaConsecutiveWins []*entity.ArenaConsecutiveWins `protobuf:"bytes,1,rep,name=arena_consecutive_wins,json=arenaConsecutiveWins,proto3" json:"arena_consecutive_wins,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConsecutiveWinsResponse) Reset() {
	*x = ConsecutiveWinsResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsecutiveWinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsecutiveWinsResponse) ProtoMessage() {}

func (x *ConsecutiveWinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsecutiveWinsResponse.ProtoReflect.Descriptor instead.
func (*ConsecutiveWinsResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConsecutiveWinsResponse) GetArenaConsecutiveWins() []*entity.ArenaConsecutiveWins {
	if x != nil {
		return x.ArenaConsecutiveWins
	}
	return nil
}

type DeckTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MusicId       int64                  `protobuf:"varint,1,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty"`
	ArenaSeasonId int64                  `protobuf:"varint,2,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckTrendRequest) Reset() {
	*x = DeckTrendRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckTrendRequest) ProtoMessage() {}

func (x *DeckTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckTrendRequest.ProtoReflect.Descriptor instead.
func (*DeckTrendRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeckTrendRequest) GetMusicId() int64 {
	if x != nil {
		return x.MusicId
	}
	return 0
}

func (x *DeckTrendRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

type DeckTrendResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Leaders       []*entity.ArenaDeckTrendMemberCard  `protobuf:"bytes,1,rep,name=leaders,proto3" json:"leaders,omitempty"`
	Members       []*entity.ArenaDeckTrendMemberCard  `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Supports      []*entity.ArenaDeckTrendSupportCard `protobuf:"bytes,3,rep,name=supports,proto3" json:"supports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckTrendResponse) Reset() {
	*x = DeckTrendResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckTrendResponse) ProtoMessage() {}

func (x *DeckTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckTrendResponse.ProtoReflect.Descriptor instead.
func (*DeckTrendResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeckTrendResponse) GetLeaders() []*entity.ArenaDeckTrendMemberCard {
	if x != nil {
		return x.Leaders
	}
	return nil
}

func (x *DeckTrendResponse) GetMembers() []*entity.ArenaDeckTrendMemberCard {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *DeckTrendResponse) GetSupports() []*entity.ArenaDeckTrendSupportCard {
	if x != nil {
		return x.Supports
	}
	return nil
}

type ArenaRewardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArenaSeasonId int64                  `protobuf:"varint,1,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaRewardsRequest) Reset() {
	*x = ArenaRewardsRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaRewardsRequest) ProtoMessage() {}

func (x *ArenaRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaRewardsRequest.ProtoReflect.Descriptor instead.
func (*ArenaRewardsRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{8}
}

func (x *ArenaRewardsRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

type ArenaRewardsResponse struct {
	state                  protoimpl.MessageState                `protogen:"open.v1"`
	Season                 *entity.ArenaSeason                   `protobuf:"bytes,1,opt,name=season,proto3" json:"season,omitempty"`
	MasterRanking          *entity.ArenaMasterRanking            `protobuf:"bytes,2,opt,name=master_ranking,json=masterRanking,proto3" json:"master_ranking,omitempty"`
	BandRankings           []*entity.ArenaBandRankings           `protobuf:"bytes,3,rep,name=band_rankings,json=bandRankings,proto3" json:"band_rankings,omitempty"`
	MasterPromotionRewards []*entity.ArenaMasterPromotionRewards `protobuf:"bytes,4,rep,name=master_promotion_rewards,json=masterPromotionRewards,proto3" json:"master_promotion_rewards,omitempty"`
	BandPromotionRewards   []*entity.ArenaBandPromotionRewards   `protobuf:"bytes,5,rep,name=band_promotion_rewards,json=bandPromotionRewards,proto3" json:"band_promotion_rewards,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ArenaRewardsResponse) Reset() {
	*x = ArenaRewardsResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaRewardsResponse) ProtoMessage() {}

func (x *ArenaRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaRewardsResponse.ProtoReflect.Descriptor instead.
func (*ArenaRewardsResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{9}
}

func (x *ArenaRewardsResponse) GetSeason() *entity.ArenaSeason {
	if x != nil {
		return x.Season
	}
	return nil
}

func (x *ArenaRewardsResponse) GetMasterRanking() *entity.ArenaMasterRanking {
	if x != nil {
		return x.MasterRanking
	}
	return nil
}

func (x *ArenaRewardsResponse) GetBandRankings() []*entity.ArenaBandRankings {
	if x != nil {
		return x.BandRankings
	}
	return nil
}

func (x *ArenaRewardsResponse) GetMasterPromotionRewards() []*entity.ArenaMasterPromotionRewards {
	if x != nil {
		return x.MasterPromotionRewards
	}
	return nil
}

func (x *ArenaRewardsResponse) GetBandPromotionRewards() []*entity.ArenaBandPromotionRewards {
	if x != nil {
		return x.BandPromotionRewards
	}
	return nil
}

type ArenaRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArenaSeasonId int64                  `protobuf:"varint,1,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	BandId        *int64                 `protobuf:"varint,2,opt,name=band_id,json=bandId,proto3,oneof" json:"band_id,omitempty"`
	RankingStart  int64                  `protobuf:"varint,3,opt,name=ranking_start,json=rankingStart,proto3" json:"ranking_start,omitempty"`
	RankingEnd    int64                  `protobuf:"varint,4,opt,name=ranking_end,json=rankingEnd,proto3" json:"ranking_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaRankingRequest) Reset() {
	*x = ArenaRankingRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaRankingRequest) ProtoMessage() {}

func (x *ArenaRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaRankingRequest.ProtoReflect.Descriptor instead.
func (*ArenaRankingRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{10}
}

func (x *ArenaRankingRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

func (x *ArenaRankingRequest) GetBandId() int64 {
	if x != nil && x.BandId != nil {
		return *x.BandId
	}
	return 0
}

func (x *ArenaRankingRequest) GetRankingStart() int64 {
	if x != nil {
		return x.RankingStart
	}
	return 0
}

func (x *ArenaRankingRequest) GetRankingEnd() int64 {
	if x != nil {
		return x.RankingEnd
	}
	return 0
}

type ArenaRankingResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Ranking       []*entity.ArenaRankingEntry `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
	MaxRank       int64                       `protobuf:"varint,2,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaRankingResponse) Reset() {
	*x = ArenaRankingResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaRankingResponse) ProtoMessage() {}

func (x *ArenaRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaRankingResponse.ProtoReflect.Descriptor instead.
func (*ArenaRankingResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{11}
}

func (x *ArenaRankingResponse) GetRanking() []*entity.ArenaRankingEntry {
	if x != nil {
		return x.Ranking
	}
	return nil
}

func (x *ArenaRankingResponse) GetMaxRank() int64 {
	if x != nil {
		return x.MaxRank
	}
	return 0
}

type ArenaMyRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArenaSeasonId int64                  `protobuf:"varint,1,opt,name=arena_season_id,json=arenaSeasonId,proto3" json:"arena_season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaMyRankRequest) Reset() {
	*x = ArenaMyRankRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaMyRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaMyRankRequest) ProtoMessage() {}

func (x *ArenaMyRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaMyRankRequest.ProtoReflect.Descriptor instead.
func (*ArenaMyRankRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{12}
}

func (x *ArenaMyRankRequest) GetArenaSeasonId() int64 {
	if x != nil {
		return x.ArenaSeasonId
	}
	return 0
}

type ArenaMyRankResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Mp            *entity.ArenaMyRankMasterPoint   `protobuf:"bytes,1,opt,name=mp,proto3" json:"mp,omitempty"`
	Lp            []*entity.ArenaMyRankLeaguePoint `protobuf:"bytes,2,rep,name=lp,proto3" json:"lp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaMyRankResponse) Reset() {
	*x = ArenaMyRankResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaMyRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaMyRankResponse) ProtoMessage() {}

func (x *ArenaMyRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaMyRankResponse.ProtoReflect.Descriptor instead.
func (*ArenaMyRankResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{13}
}

func (x *ArenaMyRankResponse) GetMp() *entity.ArenaMyRankMasterPoint {
	if x != nil {
		return x.Mp
	}
	return nil
}

func (x *ArenaMyRankResponse) GetLp() []*entity.ArenaMyRankLeaguePoint {
	if x != nil {
		return x.Lp
	}
	return nil
}

type MatchingHistoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingHistoriesRequest) Reset() {
	*x = MatchingHistoriesRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingHistoriesRequest) ProtoMessage() {}

func (x *MatchingHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingHistoriesRequest.ProtoReflect.Descriptor instead.
func (*MatchingHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{14}
}

type MatchingHistoriesResponse struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	MatchingHistories []*entity.ArenaMatchingHistories `protobuf:"bytes,1,rep,name=matching_histories,json=matchingHistories,proto3" json:"matching_histories,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchingHistoriesResponse) Reset() {
	*x = MatchingHistoriesResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingHistoriesResponse) ProtoMessage() {}

func (x *MatchingHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingHistoriesResponse.ProtoReflect.Descriptor instead.
func (*MatchingHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{15}
}

func (x *MatchingHistoriesResponse) GetMatchingHistories() []*entity.ArenaMatchingHistories {
	if x != nil {
		return x.MatchingHistories
	}
	return nil
}

type SaveDedicatedDecksRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Deck          *entity.ArenaDedicatedDecks `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDedicatedDecksRequest) Reset() {
	*x = SaveDedicatedDecksRequest{}
	mi := &file_app_arena_arena_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDedicatedDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDedicatedDecksRequest) ProtoMessage() {}

func (x *SaveDedicatedDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDedicatedDecksRequest.ProtoReflect.Descriptor instead.
func (*SaveDedicatedDecksRequest) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{16}
}

func (x *SaveDedicatedDecksRequest) GetDeck() *entity.ArenaDedicatedDecks {
	if x != nil {
		return x.Deck
	}
	return nil
}

type SaveDedicatedDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDedicatedDecksResponse) Reset() {
	*x = SaveDedicatedDecksResponse{}
	mi := &file_app_arena_arena_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDedicatedDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDedicatedDecksResponse) ProtoMessage() {}

func (x *SaveDedicatedDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_arena_arena_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDedicatedDecksResponse.ProtoReflect.Descriptor instead.
func (*SaveDedicatedDecksResponse) Descriptor() ([]byte, []int) {
	return file_app_arena_arena_service_proto_rawDescGZIP(), []int{17}
}

var File_app_arena_arena_service_proto protoreflect.FileDescriptor

const file_app_arena_arena_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/arena/arena_service.proto\x12\tapp.arena\x1a\x12entity/arena.proto\"0\n" +
	"\x14ReportPenaltyRequest\x12\x18\n" +
	"\apenalty\x18\x01 \x01(\x05R\apenalty\"\x17\n" +
	"\x15ReportPenaltyResponse\"9\n" +
	"\x0fArenaTopRequest\x12&\n" +
	"\x0farena_season_id\x18\x01 \x01(\x03R\rarenaSeasonId\"\x92\x04\n" +
	"\x10ArenaTopResponse\x12?\n" +
	"\rlatest_status\x18\x01 \x01(\v2\x1a.entity.ArenaTopLastStatusR\flatestStatus\x12\x0e\n" +
	"\x02mp\x18\x02 \x01(\x03R\x02mp\x12\x1f\n" +
	"\x02lp\x18\x03 \x03(\v2\x0f.entity.ArenaLpR\x02lp\x12A\n" +
	"\rdaily_rewards\x18\x04 \x03(\v2\x1c.entity.ArenaTopDailyRewardsR\fdailyRewards\x12#\n" +
	"\rpenalty_count\x18\x05 \x01(\x05R\fpenaltyCount\x12(\n" +
	"\x10before_season_id\x18\x06 \x01(\x03R\x0ebeforeSeasonId\x121\n" +
	"\x15is_show_season_result\x18\a \x01(\bR\x12isShowSeasonResult\x12;\n" +
	"\x1aarena_promotion_reward_ids\x18\b \x03(\x03R\x17arenaPromotionRewardIds\x129\n" +
	"\flp_rank_diff\x18\t \x03(\v2\x17.entity.ArenaLpRankDiffR\n" +
	"lpRankDiff\x12O\n" +
	"\x15arena_dedicated_decks\x18\n" +
	" \x03(\v2\x1b.entity.ArenaDedicatedDecksR\x13arenaDedicatedDecks\"@\n" +
	"\x16ConsecutiveWinsRequest\x12&\n" +
	"\x0farena_season_id\x18\x01 \x01(\x03R\rarenaSeasonId\"m\n" +
	"\x17ConsecutiveWinsResponse\x12R\n" +
	"\x16arena_consecutive_wins\x18\x01 \x03(\v2\x1c.entity.ArenaConsecutiveWinsR\x14arenaConsecutiveWins\"U\n" +
	"\x10DeckTrendRequest\x12\x19\n" +
	"\bmusic_id\x18\x01 \x01(\x03R\amusicId\x12&\n" +
	"\x0farena_season_id\x18\x02 \x01(\x03R\rarenaSeasonId\"\xca\x01\n" +
	"\x11DeckTrendResponse\x12:\n" +
	"\aleaders\x18\x01 \x03(\v2 .entity.ArenaDeckTrendMemberCardR\aleaders\x12:\n" +
	"\amembers\x18\x02 \x03(\v2 .entity.ArenaDeckTrendMemberCardR\amembers\x12=\n" +
	"\bsupports\x18\x03 \x03(\v2!.entity.ArenaDeckTrendSupportCardR\bsupports\"=\n" +
	"\x13ArenaRewardsRequest\x12&\n" +
	"\x0farena_season_id\x18\x01 \x01(\x03R\rarenaSeasonId\"\xfe\x02\n" +
	"\x14ArenaRewardsResponse\x12+\n" +
	"\x06season\x18\x01 \x01(\v2\x13.entity.ArenaSeasonR\x06season\x12A\n" +
	"\x0emaster_ranking\x18\x02 \x01(\v2\x1a.entity.ArenaMasterRankingR\rmasterRanking\x12>\n" +
	"\rband_rankings\x18\x03 \x03(\v2\x19.entity.ArenaBandRankingsR\fbandRankings\x12]\n" +
	"\x18master_promotion_rewards\x18\x04 \x03(\v2#.entity.ArenaMasterPromotionRewardsR\x16masterPromotionRewards\x12W\n" +
	"\x16band_promotion_rewards\x18\x05 \x03(\v2!.entity.ArenaBandPromotionRewardsR\x14bandPromotionRewards\"\xad\x01\n" +
	"\x13ArenaRankingRequest\x12&\n" +
	"\x0farena_season_id\x18\x01 \x01(\x03R\rarenaSeasonId\x12\x1c\n" +
	"\aband_id\x18\x02 \x01(\x03H\x00R\x06bandId\x88\x01\x01\x12#\n" +
	"\rranking_start\x18\x03 \x01(\x03R\frankingStart\x12\x1f\n" +
	"\vranking_end\x18\x04 \x01(\x03R\n" +
	"rankingEndB\n" +
	"\n" +
	"\b_band_id\"f\n" +
	"\x14ArenaRankingResponse\x123\n" +
	"\aranking\x18\x01 \x03(\v2\x19.entity.ArenaRankingEntryR\aranking\x12\x19\n" +
	"\bmax_rank\x18\x02 \x01(\x03R\amaxRank\"<\n" +
	"\x12ArenaMyRankRequest\x12&\n" +
	"\x0farena_season_id\x18\x01 \x01(\x03R\rarenaSeasonId\"u\n" +
	"\x13ArenaMyRankResponse\x12.\n" +
	"\x02mp\x18\x01 \x01(\v2\x1e.entity.ArenaMyRankMasterPointR\x02mp\x12.\n" +
	"\x02lp\x18\x02 \x03(\v2\x1e.entity.ArenaMyRankLeaguePointR\x02lp\"\x1a\n" +
	"\x18MatchingHistoriesRequest\"j\n" +
	"\x19MatchingHistoriesResponse\x12M\n" +
	"\x12matching_histories\x18\x01 \x03(\v2\x1e.entity.ArenaMatchingHistoriesR\x11matchingHistories\"L\n" +
	"\x19SaveDedicatedDecksRequest\x12/\n" +
	"\x04deck\x18\x01 \x01(\v2\x1b.entity.ArenaDedicatedDecksR\x04deck\"\x1c\n" +
	"\x1aSaveDedicatedDecksResponse2\xfc\x05\n" +
	"\fArenaService\x12R\n" +
	"\rReportPenalty\x12\x1f.app.arena.ReportPenaltyRequest\x1a .app.arena.ReportPenaltyResponse\x12C\n" +
	"\bArenaTop\x12\x1a.app.arena.ArenaTopRequest\x1a\x1b.app.arena.ArenaTopResponse\x12X\n" +
	"\x0fConsecutiveWins\x12!.app.arena.ConsecutiveWinsRequest\x1a\".app.arena.ConsecutiveWinsResponse\x12F\n" +
	"\tDeckTrend\x12\x1b.app.arena.DeckTrendRequest\x1a\x1c.app.arena.DeckTrendResponse\x12O\n" +
	"\fArenaRewards\x12\x1e.app.arena.ArenaRewardsRequest\x1a\x1f.app.arena.ArenaRewardsResponse\x12O\n" +
	"\fArenaRanking\x12\x1e.app.arena.ArenaRankingRequest\x1a\x1f.app.arena.ArenaRankingResponse\x12L\n" +
	"\vArenaMyRank\x12\x1d.app.arena.ArenaMyRankRequest\x1a\x1e.app.arena.ArenaMyRankResponse\x12^\n" +
	"\x11MatchingHistories\x12#.app.arena.MatchingHistoriesRequest\x1a$.app.arena.MatchingHistoriesResponse\x12a\n" +
	"\x12SaveDedicatedDecks\x12$.app.arena.SaveDedicatedDecksRequest\x1a%.app.arena.SaveDedicatedDecksResponseB\x15\xaa\x02\x12App.Protobuf.Arenab\x06proto3"

var (
	file_app_arena_arena_service_proto_rawDescOnce sync.Once
	file_app_arena_arena_service_proto_rawDescData []byte
)

func file_app_arena_arena_service_proto_rawDescGZIP() []byte {
	file_app_arena_arena_service_proto_rawDescOnce.Do(func() {
		file_app_arena_arena_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_arena_arena_service_proto_rawDesc), len(file_app_arena_arena_service_proto_rawDesc)))
	})
	return file_app_arena_arena_service_proto_rawDescData
}

var file_app_arena_arena_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_arena_arena_service_proto_goTypes = []any{
	(*ReportPenaltyRequest)(nil),               // 0: app.arena.ReportPenaltyRequest
	(*ReportPenaltyResponse)(nil),              // 1: app.arena.ReportPenaltyResponse
	(*ArenaTopRequest)(nil),                    // 2: app.arena.ArenaTopRequest
	(*ArenaTopResponse)(nil),                   // 3: app.arena.ArenaTopResponse
	(*ConsecutiveWinsRequest)(nil),             // 4: app.arena.ConsecutiveWinsRequest
	(*ConsecutiveWinsResponse)(nil),            // 5: app.arena.ConsecutiveWinsResponse
	(*DeckTrendRequest)(nil),                   // 6: app.arena.DeckTrendRequest
	(*DeckTrendResponse)(nil),                  // 7: app.arena.DeckTrendResponse
	(*ArenaRewardsRequest)(nil),                // 8: app.arena.ArenaRewardsRequest
	(*ArenaRewardsResponse)(nil),               // 9: app.arena.ArenaRewardsResponse
	(*ArenaRankingRequest)(nil),                // 10: app.arena.ArenaRankingRequest
	(*ArenaRankingResponse)(nil),               // 11: app.arena.ArenaRankingResponse
	(*ArenaMyRankRequest)(nil),                 // 12: app.arena.ArenaMyRankRequest
	(*ArenaMyRankResponse)(nil),                // 13: app.arena.ArenaMyRankResponse
	(*MatchingHistoriesRequest)(nil),           // 14: app.arena.MatchingHistoriesRequest
	(*MatchingHistoriesResponse)(nil),          // 15: app.arena.MatchingHistoriesResponse
	(*SaveDedicatedDecksRequest)(nil),          // 16: app.arena.SaveDedicatedDecksRequest
	(*SaveDedicatedDecksResponse)(nil),         // 17: app.arena.SaveDedicatedDecksResponse
	(*entity.ArenaTopLastStatus)(nil),          // 18: entity.ArenaTopLastStatus
	(*entity.ArenaLp)(nil),                     // 19: entity.ArenaLp
	(*entity.ArenaTopDailyRewards)(nil),        // 20: entity.ArenaTopDailyRewards
	(*entity.ArenaLpRankDiff)(nil),             // 21: entity.ArenaLpRankDiff
	(*entity.ArenaDedicatedDecks)(nil),         // 22: entity.ArenaDedicatedDecks
	(*entity.ArenaConsecutiveWins)(nil),        // 23: entity.ArenaConsecutiveWins
	(*entity.ArenaDeckTrendMemberCard)(nil),    // 24: entity.ArenaDeckTrendMemberCard
	(*entity.ArenaDeckTrendSupportCard)(nil),   // 25: entity.ArenaDeckTrendSupportCard
	(*entity.ArenaSeason)(nil),                 // 26: entity.ArenaSeason
	(*entity.ArenaMasterRanking)(nil),          // 27: entity.ArenaMasterRanking
	(*entity.ArenaBandRankings)(nil),           // 28: entity.ArenaBandRankings
	(*entity.ArenaMasterPromotionRewards)(nil), // 29: entity.ArenaMasterPromotionRewards
	(*entity.ArenaBandPromotionRewards)(nil),   // 30: entity.ArenaBandPromotionRewards
	(*entity.ArenaRankingEntry)(nil),           // 31: entity.ArenaRankingEntry
	(*entity.ArenaMyRankMasterPoint)(nil),      // 32: entity.ArenaMyRankMasterPoint
	(*entity.ArenaMyRankLeaguePoint)(nil),      // 33: entity.ArenaMyRankLeaguePoint
	(*entity.ArenaMatchingHistories)(nil),      // 34: entity.ArenaMatchingHistories
}
var file_app_arena_arena_service_proto_depIdxs = []int32{
	18, // 0: app.arena.ArenaTopResponse.latest_status:type_name -> entity.ArenaTopLastStatus
	19, // 1: app.arena.ArenaTopResponse.lp:type_name -> entity.ArenaLp
	20, // 2: app.arena.ArenaTopResponse.daily_rewards:type_name -> entity.ArenaTopDailyRewards
	21, // 3: app.arena.ArenaTopResponse.lp_rank_diff:type_name -> entity.ArenaLpRankDiff
	22, // 4: app.arena.ArenaTopResponse.arena_dedicated_decks:type_name -> entity.ArenaDedicatedDecks
	23, // 5: app.arena.ConsecutiveWinsResponse.arena_consecutive_wins:type_name -> entity.ArenaConsecutiveWins
	24, // 6: app.arena.DeckTrendResponse.leaders:type_name -> entity.ArenaDeckTrendMemberCard
	24, // 7: app.arena.DeckTrendResponse.members:type_name -> entity.ArenaDeckTrendMemberCard
	25, // 8: app.arena.DeckTrendResponse.supports:type_name -> entity.ArenaDeckTrendSupportCard
	26, // 9: app.arena.ArenaRewardsResponse.season:type_name -> entity.ArenaSeason
	27, // 10: app.arena.ArenaRewardsResponse.master_ranking:type_name -> entity.ArenaMasterRanking
	28, // 11: app.arena.ArenaRewardsResponse.band_rankings:type_name -> entity.ArenaBandRankings
	29, // 12: app.arena.ArenaRewardsResponse.master_promotion_rewards:type_name -> entity.ArenaMasterPromotionRewards
	30, // 13: app.arena.ArenaRewardsResponse.band_promotion_rewards:type_name -> entity.ArenaBandPromotionRewards
	31, // 14: app.arena.ArenaRankingResponse.ranking:type_name -> entity.ArenaRankingEntry
	32, // 15: app.arena.ArenaMyRankResponse.mp:type_name -> entity.ArenaMyRankMasterPoint
	33, // 16: app.arena.ArenaMyRankResponse.lp:type_name -> entity.ArenaMyRankLeaguePoint
	34, // 17: app.arena.MatchingHistoriesResponse.matching_histories:type_name -> entity.ArenaMatchingHistories
	22, // 18: app.arena.SaveDedicatedDecksRequest.deck:type_name -> entity.ArenaDedicatedDecks
	0,  // 19: app.arena.ArenaService.ReportPenalty:input_type -> app.arena.ReportPenaltyRequest
	2,  // 20: app.arena.ArenaService.ArenaTop:input_type -> app.arena.ArenaTopRequest
	4,  // 21: app.arena.ArenaService.ConsecutiveWins:input_type -> app.arena.ConsecutiveWinsRequest
	6,  // 22: app.arena.ArenaService.DeckTrend:input_type -> app.arena.DeckTrendRequest
	8,  // 23: app.arena.ArenaService.ArenaRewards:input_type -> app.arena.ArenaRewardsRequest
	10, // 24: app.arena.ArenaService.ArenaRanking:input_type -> app.arena.ArenaRankingRequest
	12, // 25: app.arena.ArenaService.ArenaMyRank:input_type -> app.arena.ArenaMyRankRequest
	14, // 26: app.arena.ArenaService.MatchingHistories:input_type -> app.arena.MatchingHistoriesRequest
	16, // 27: app.arena.ArenaService.SaveDedicatedDecks:input_type -> app.arena.SaveDedicatedDecksRequest
	1,  // 28: app.arena.ArenaService.ReportPenalty:output_type -> app.arena.ReportPenaltyResponse
	3,  // 29: app.arena.ArenaService.ArenaTop:output_type -> app.arena.ArenaTopResponse
	5,  // 30: app.arena.ArenaService.ConsecutiveWins:output_type -> app.arena.ConsecutiveWinsResponse
	7,  // 31: app.arena.ArenaService.DeckTrend:output_type -> app.arena.DeckTrendResponse
	9,  // 32: app.arena.ArenaService.ArenaRewards:output_type -> app.arena.ArenaRewardsResponse
	11, // 33: app.arena.ArenaService.ArenaRanking:output_type -> app.arena.ArenaRankingResponse
	13, // 34: app.arena.ArenaService.ArenaMyRank:output_type -> app.arena.ArenaMyRankResponse
	15, // 35: app.arena.ArenaService.MatchingHistories:output_type -> app.arena.MatchingHistoriesResponse
	17, // 36: app.arena.ArenaService.SaveDedicatedDecks:output_type -> app.arena.SaveDedicatedDecksResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_app_arena_arena_service_proto_init() }
func file_app_arena_arena_service_proto_init() {
	if File_app_arena_arena_service_proto != nil {
		return
	}
	file_app_arena_arena_service_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_arena_arena_service_proto_rawDesc), len(file_app_arena_arena_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_arena_arena_service_proto_goTypes,
		DependencyIndexes: file_app_arena_arena_service_proto_depIdxs,
		MessageInfos:      file_app_arena_arena_service_proto_msgTypes,
	}.Build()
	File_app_arena_arena_service_proto = out.File
	file_app_arena_arena_service_proto_goTypes = nil
	file_app_arena_arena_service_proto_depIdxs = nil
}
