// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: app/arena/arena_service.proto

package arena

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArenaService_ReportPenalty_FullMethodName      = "/app.arena.ArenaService/ReportPenalty"
	ArenaService_ArenaTop_FullMethodName           = "/app.arena.ArenaService/ArenaTop"
	ArenaService_ConsecutiveWins_FullMethodName    = "/app.arena.ArenaService/ConsecutiveWins"
	ArenaService_DeckTrend_FullMethodName          = "/app.arena.ArenaService/DeckTrend"
	ArenaService_ArenaRewards_FullMethodName       = "/app.arena.ArenaService/ArenaRewards"
	ArenaService_ArenaRanking_FullMethodName       = "/app.arena.ArenaService/ArenaRanking"
	ArenaService_ArenaMyRank_FullMethodName        = "/app.arena.ArenaService/ArenaMyRank"
	ArenaService_MatchingHistories_FullMethodName  = "/app.arena.ArenaService/MatchingHistories"
	ArenaService_SaveDedicatedDecks_FullMethodName = "/app.arena.ArenaService/SaveDedicatedDecks"
)

// ArenaServiceClient is the client API for ArenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArenaServiceClient interface {
	ReportPenalty(ctx context.Context, in *ReportPenaltyRequest, opts ...grpc.CallOption) (*ReportPenaltyResponse, error)
	ArenaTop(ctx context.Context, in *ArenaTopRequest, opts ...grpc.CallOption) (*ArenaTopResponse, error)
	ConsecutiveWins(ctx context.Context, in *ConsecutiveWinsRequest, opts ...grpc.CallOption) (*ConsecutiveWinsResponse, error)
	DeckTrend(ctx context.Context, in *DeckTrendRequest, opts ...grpc.CallOption) (*DeckTrendResponse, error)
	ArenaRewards(ctx context.Context, in *ArenaRewardsRequest, opts ...grpc.CallOption) (*ArenaRewardsResponse, error)
	ArenaRanking(ctx context.Context, in *ArenaRankingRequest, opts ...grpc.CallOption) (*ArenaRankingResponse, error)
	ArenaMyRank(ctx context.Context, in *ArenaMyRankRequest, opts ...grpc.CallOption) (*ArenaMyRankResponse, error)
	MatchingHistories(ctx context.Context, in *MatchingHistoriesRequest, opts ...grpc.CallOption) (*MatchingHistoriesResponse, error)
	SaveDedicatedDecks(ctx context.Context, in *SaveDedicatedDecksRequest, opts ...grpc.CallOption) (*SaveDedicatedDecksResponse, error)
}

type arenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaServiceClient(cc grpc.ClientConnInterface) ArenaServiceClient {
	return &arenaServiceClient{cc}
}

func (c *arenaServiceClient) ReportPenalty(ctx context.Context, in *ReportPenaltyRequest, opts ...grpc.CallOption) (*ReportPenaltyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportPenaltyResponse)
	err := c.cc.Invoke(ctx, ArenaService_ReportPenalty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ArenaTop(ctx context.Context, in *ArenaTopRequest, opts ...grpc.CallOption) (*ArenaTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArenaTopResponse)
	err := c.cc.Invoke(ctx, ArenaService_ArenaTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ConsecutiveWins(ctx context.Context, in *ConsecutiveWinsRequest, opts ...grpc.CallOption) (*ConsecutiveWinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsecutiveWinsResponse)
	err := c.cc.Invoke(ctx, ArenaService_ConsecutiveWins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) DeckTrend(ctx context.Context, in *DeckTrendRequest, opts ...grpc.CallOption) (*DeckTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckTrendResponse)
	err := c.cc.Invoke(ctx, ArenaService_DeckTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ArenaRewards(ctx context.Context, in *ArenaRewardsRequest, opts ...grpc.CallOption) (*ArenaRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArenaRewardsResponse)
	err := c.cc.Invoke(ctx, ArenaService_ArenaRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ArenaRanking(ctx context.Context, in *ArenaRankingRequest, opts ...grpc.CallOption) (*ArenaRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArenaRankingResponse)
	err := c.cc.Invoke(ctx, ArenaService_ArenaRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ArenaMyRank(ctx context.Context, in *ArenaMyRankRequest, opts ...grpc.CallOption) (*ArenaMyRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArenaMyRankResponse)
	err := c.cc.Invoke(ctx, ArenaService_ArenaMyRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) MatchingHistories(ctx context.Context, in *MatchingHistoriesRequest, opts ...grpc.CallOption) (*MatchingHistoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchingHistoriesResponse)
	err := c.cc.Invoke(ctx, ArenaService_MatchingHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) SaveDedicatedDecks(ctx context.Context, in *SaveDedicatedDecksRequest, opts ...grpc.CallOption) (*SaveDedicatedDecksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDedicatedDecksResponse)
	err := c.cc.Invoke(ctx, ArenaService_SaveDedicatedDecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServiceServer is the server API for ArenaService service.
// All implementations must embed UnimplementedArenaServiceServer
// for forward compatibility.
type ArenaServiceServer interface {
	ReportPenalty(context.Context, *ReportPenaltyRequest) (*ReportPenaltyResponse, error)
	ArenaTop(context.Context, *ArenaTopRequest) (*ArenaTopResponse, error)
	ConsecutiveWins(context.Context, *ConsecutiveWinsRequest) (*ConsecutiveWinsResponse, error)
	DeckTrend(context.Context, *DeckTrendRequest) (*DeckTrendResponse, error)
	ArenaRewards(context.Context, *ArenaRewardsRequest) (*ArenaRewardsResponse, error)
	ArenaRanking(context.Context, *ArenaRankingRequest) (*ArenaRankingResponse, error)
	ArenaMyRank(context.Context, *ArenaMyRankRequest) (*ArenaMyRankResponse, error)
	MatchingHistories(context.Context, *MatchingHistoriesRequest) (*MatchingHistoriesResponse, error)
	SaveDedicatedDecks(context.Context, *SaveDedicatedDecksRequest) (*SaveDedicatedDecksResponse, error)
	mustEmbedUnimplementedArenaServiceServer()
}

// UnimplementedArenaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServiceServer struct{}

func (UnimplementedArenaServiceServer) ReportPenalty(context.Context, *ReportPenaltyRequest) (*ReportPenaltyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPenalty not implemented")
}
func (UnimplementedArenaServiceServer) ArenaTop(context.Context, *ArenaTopRequest) (*ArenaTopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArenaTop not implemented")
}
func (UnimplementedArenaServiceServer) ConsecutiveWins(context.Context, *ConsecutiveWinsRequest) (*ConsecutiveWinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsecutiveWins not implemented")
}
func (UnimplementedArenaServiceServer) DeckTrend(context.Context, *DeckTrendRequest) (*DeckTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeckTrend not implemented")
}
func (UnimplementedArenaServiceServer) ArenaRewards(context.Context, *ArenaRewardsRequest) (*ArenaRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArenaRewards not implemented")
}
func (UnimplementedArenaServiceServer) ArenaRanking(context.Context, *ArenaRankingRequest) (*ArenaRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArenaRanking not implemented")
}
func (UnimplementedArenaServiceServer) ArenaMyRank(context.Context, *ArenaMyRankRequest) (*ArenaMyRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArenaMyRank not implemented")
}
func (UnimplementedArenaServiceServer) MatchingHistories(context.Context, *MatchingHistoriesRequest) (*MatchingHistoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchingHistories not implemented")
}
func (UnimplementedArenaServiceServer) SaveDedicatedDecks(context.Context, *SaveDedicatedDecksRequest) (*SaveDedicatedDecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDedicatedDecks not implemented")
}
func (UnimplementedArenaServiceServer) mustEmbedUnimplementedArenaServiceServer() {}
func (UnimplementedArenaServiceServer) testEmbeddedByValue()                      {}

// UnsafeArenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServiceServer will
// result in compilation errors.
type UnsafeArenaServiceServer interface {
	mustEmbedUnimplementedArenaServiceServer()
}

func RegisterArenaServiceServer(s grpc.ServiceRegistrar, srv ArenaServiceServer) {
	// If the following call pancis, it indicates UnimplementedArenaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArenaService_ServiceDesc, srv)
}

func _ArenaService_ReportPenalty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPenaltyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ReportPenalty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ReportPenalty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ReportPenalty(ctx, req.(*ReportPenaltyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ArenaTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ArenaTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ArenaTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ArenaTop(ctx, req.(*ArenaTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ConsecutiveWins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsecutiveWinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ConsecutiveWins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ConsecutiveWins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ConsecutiveWins(ctx, req.(*ConsecutiveWinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_DeckTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).DeckTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_DeckTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).DeckTrend(ctx, req.(*DeckTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ArenaRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ArenaRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ArenaRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ArenaRewards(ctx, req.(*ArenaRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ArenaRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ArenaRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ArenaRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ArenaRanking(ctx, req.(*ArenaRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ArenaMyRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaMyRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ArenaMyRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ArenaMyRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ArenaMyRank(ctx, req.(*ArenaMyRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_MatchingHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchingHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).MatchingHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_MatchingHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).MatchingHistories(ctx, req.(*MatchingHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_SaveDedicatedDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDedicatedDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).SaveDedicatedDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_SaveDedicatedDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).SaveDedicatedDecks(ctx, req.(*SaveDedicatedDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArenaService_ServiceDesc is the grpc.ServiceDesc for ArenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.arena.ArenaService",
	HandlerType: (*ArenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportPenalty",
			Handler:    _ArenaService_ReportPenalty_Handler,
		},
		{
			MethodName: "ArenaTop",
			Handler:    _ArenaService_ArenaTop_Handler,
		},
		{
			MethodName: "ConsecutiveWins",
			Handler:    _ArenaService_ConsecutiveWins_Handler,
		},
		{
			MethodName: "DeckTrend",
			Handler:    _ArenaService_DeckTrend_Handler,
		},
		{
			MethodName: "ArenaRewards",
			Handler:    _ArenaService_ArenaRewards_Handler,
		},
		{
			MethodName: "ArenaRanking",
			Handler:    _ArenaService_ArenaRanking_Handler,
		},
		{
			MethodName: "ArenaMyRank",
			Handler:    _ArenaService_ArenaMyRank_Handler,
		},
		{
			MethodName: "MatchingHistories",
			Handler:    _ArenaService_MatchingHistories_Handler,
		},
		{
			MethodName: "SaveDedicatedDecks",
			Handler:    _ArenaService_SaveDedicatedDecks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/arena/arena_service.proto",
}
