// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: app/serial_code/serial_code_service.proto

package serial_code

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SerialCodeService_RedeemSerialCode_FullMethodName = "/app.serial_code.SerialCodeService/RedeemSerialCode"
)

// SerialCodeServiceClient is the client API for SerialCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SerialCodeServiceClient interface {
	RedeemSerialCode(ctx context.Context, in *RedeemSerialCodeRequest, opts ...grpc.CallOption) (*RedeemSerialCodeResponse, error)
}

type serialCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSerialCodeServiceClient(cc grpc.ClientConnInterface) SerialCodeServiceClient {
	return &serialCodeServiceClient{cc}
}

func (c *serialCodeServiceClient) RedeemSerialCode(ctx context.Context, in *RedeemSerialCodeRequest, opts ...grpc.CallOption) (*RedeemSerialCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemSerialCodeResponse)
	err := c.cc.Invoke(ctx, SerialCodeService_RedeemSerialCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerialCodeServiceServer is the server API for SerialCodeService service.
// All implementations must embed UnimplementedSerialCodeServiceServer
// for forward compatibility.
type SerialCodeServiceServer interface {
	RedeemSerialCode(context.Context, *RedeemSerialCodeRequest) (*RedeemSerialCodeResponse, error)
	mustEmbedUnimplementedSerialCodeServiceServer()
}

// UnimplementedSerialCodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSerialCodeServiceServer struct{}

func (UnimplementedSerialCodeServiceServer) RedeemSerialCode(context.Context, *RedeemSerialCodeRequest) (*RedeemSerialCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemSerialCode not implemented")
}
func (UnimplementedSerialCodeServiceServer) mustEmbedUnimplementedSerialCodeServiceServer() {}
func (UnimplementedSerialCodeServiceServer) testEmbeddedByValue()                           {}

// UnsafeSerialCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SerialCodeServiceServer will
// result in compilation errors.
type UnsafeSerialCodeServiceServer interface {
	mustEmbedUnimplementedSerialCodeServiceServer()
}

func RegisterSerialCodeServiceServer(s grpc.ServiceRegistrar, srv SerialCodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSerialCodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SerialCodeService_ServiceDesc, srv)
}

func _SerialCodeService_RedeemSerialCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemSerialCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialCodeServiceServer).RedeemSerialCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialCodeService_RedeemSerialCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialCodeServiceServer).RedeemSerialCode(ctx, req.(*RedeemSerialCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SerialCodeService_ServiceDesc is the grpc.ServiceDesc for SerialCodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SerialCodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.serial_code.SerialCodeService",
	HandlerType: (*SerialCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedeemSerialCode",
			Handler:    _SerialCodeService_RedeemSerialCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/serial_code/serial_code_service.proto",
}
