// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/supports_terms/supports_terms_service.proto

package supports_terms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFaqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaqRequest) Reset() {
	*x = GetFaqRequest{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaqRequest) ProtoMessage() {}

func (x *GetFaqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaqRequest.ProtoReflect.Descriptor instead.
func (*GetFaqRequest) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{0}
}

type GetFaqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faqs          []*entity.Faqs         `protobuf:"bytes,1,rep,name=faqs,proto3" json:"faqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaqResponse) Reset() {
	*x = GetFaqResponse{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaqResponse) ProtoMessage() {}

func (x *GetFaqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaqResponse.ProtoReflect.Descriptor instead.
func (*GetFaqResponse) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFaqResponse) GetFaqs() []*entity.Faqs {
	if x != nil {
		return x.Faqs
	}
	return nil
}

type TermsAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermsIds      []*entity.TermsIds     `protobuf:"bytes,1,rep,name=terms_ids,json=termsIds,proto3" json:"terms_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsAgreementRequest) Reset() {
	*x = TermsAgreementRequest{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsAgreementRequest) ProtoMessage() {}

func (x *TermsAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsAgreementRequest.ProtoReflect.Descriptor instead.
func (*TermsAgreementRequest) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{2}
}

func (x *TermsAgreementRequest) GetTermsIds() []*entity.TermsIds {
	if x != nil {
		return x.TermsIds
	}
	return nil
}

type TermsAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsAgreementResponse) Reset() {
	*x = TermsAgreementResponse{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsAgreementResponse) ProtoMessage() {}

func (x *TermsAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsAgreementResponse.ProtoReflect.Descriptor instead.
func (*TermsAgreementResponse) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{3}
}

type TermsAgreementHistoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsAgreementHistoriesRequest) Reset() {
	*x = TermsAgreementHistoriesRequest{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsAgreementHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsAgreementHistoriesRequest) ProtoMessage() {}

func (x *TermsAgreementHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsAgreementHistoriesRequest.ProtoReflect.Descriptor instead.
func (*TermsAgreementHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{4}
}

type TermsAgreementHistoriesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Histories     []*entity.TermsHistories `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsAgreementHistoriesResponse) Reset() {
	*x = TermsAgreementHistoriesResponse{}
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsAgreementHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsAgreementHistoriesResponse) ProtoMessage() {}

func (x *TermsAgreementHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_supports_terms_supports_terms_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsAgreementHistoriesResponse.ProtoReflect.Descriptor instead.
func (*TermsAgreementHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_app_supports_terms_supports_terms_service_proto_rawDescGZIP(), []int{5}
}

func (x *TermsAgreementHistoriesResponse) GetHistories() []*entity.TermsHistories {
	if x != nil {
		return x.Histories
	}
	return nil
}

var File_app_supports_terms_supports_terms_service_proto protoreflect.FileDescriptor

const file_app_supports_terms_supports_terms_service_proto_rawDesc = "" +
	"\n" +
	"/app/supports_terms/supports_terms_service.proto\x12\x12app.supports_terms\x1a\x1bentity/supports_terms.proto\"\x0f\n" +
	"\rGetFaqRequest\"2\n" +
	"\x0eGetFaqResponse\x12 \n" +
	"\x04faqs\x18\x01 \x03(\v2\f.entity.FaqsR\x04faqs\"F\n" +
	"\x15TermsAgreementRequest\x12-\n" +
	"\tterms_ids\x18\x01 \x03(\v2\x10.entity.TermsIdsR\btermsIds\"\x18\n" +
	"\x16TermsAgreementResponse\" \n" +
	"\x1eTermsAgreementHistoriesRequest\"W\n" +
	"\x1fTermsAgreementHistoriesResponse\x124\n" +
	"\thistories\x18\x01 \x03(\v2\x16.entity.TermsHistoriesR\thistories2\xd5\x02\n" +
	"\x14SupportsTermsService\x12O\n" +
	"\x06GetFaq\x12!.app.supports_terms.GetFaqRequest\x1a\".app.supports_terms.GetFaqResponse\x12g\n" +
	"\x0eTermsAgreement\x12).app.supports_terms.TermsAgreementRequest\x1a*.app.supports_terms.TermsAgreementResponse\x12\x82\x01\n" +
	"\x17TermsAgreementHistories\x122.app.supports_terms.TermsAgreementHistoriesRequest\x1a3.app.supports_terms.TermsAgreementHistoriesResponseB\x1d\xaa\x02\x1aApp.Protobuf.SupportsTermsb\x06proto3"

var (
	file_app_supports_terms_supports_terms_service_proto_rawDescOnce sync.Once
	file_app_supports_terms_supports_terms_service_proto_rawDescData []byte
)

func file_app_supports_terms_supports_terms_service_proto_rawDescGZIP() []byte {
	file_app_supports_terms_supports_terms_service_proto_rawDescOnce.Do(func() {
		file_app_supports_terms_supports_terms_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_supports_terms_supports_terms_service_proto_rawDesc), len(file_app_supports_terms_supports_terms_service_proto_rawDesc)))
	})
	return file_app_supports_terms_supports_terms_service_proto_rawDescData
}

var file_app_supports_terms_supports_terms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_supports_terms_supports_terms_service_proto_goTypes = []any{
	(*GetFaqRequest)(nil),                   // 0: app.supports_terms.GetFaqRequest
	(*GetFaqResponse)(nil),                  // 1: app.supports_terms.GetFaqResponse
	(*TermsAgreementRequest)(nil),           // 2: app.supports_terms.TermsAgreementRequest
	(*TermsAgreementResponse)(nil),          // 3: app.supports_terms.TermsAgreementResponse
	(*TermsAgreementHistoriesRequest)(nil),  // 4: app.supports_terms.TermsAgreementHistoriesRequest
	(*TermsAgreementHistoriesResponse)(nil), // 5: app.supports_terms.TermsAgreementHistoriesResponse
	(*entity.Faqs)(nil),                     // 6: entity.Faqs
	(*entity.TermsIds)(nil),                 // 7: entity.TermsIds
	(*entity.TermsHistories)(nil),           // 8: entity.TermsHistories
}
var file_app_supports_terms_supports_terms_service_proto_depIdxs = []int32{
	6, // 0: app.supports_terms.GetFaqResponse.faqs:type_name -> entity.Faqs
	7, // 1: app.supports_terms.TermsAgreementRequest.terms_ids:type_name -> entity.TermsIds
	8, // 2: app.supports_terms.TermsAgreementHistoriesResponse.histories:type_name -> entity.TermsHistories
	0, // 3: app.supports_terms.SupportsTermsService.GetFaq:input_type -> app.supports_terms.GetFaqRequest
	2, // 4: app.supports_terms.SupportsTermsService.TermsAgreement:input_type -> app.supports_terms.TermsAgreementRequest
	4, // 5: app.supports_terms.SupportsTermsService.TermsAgreementHistories:input_type -> app.supports_terms.TermsAgreementHistoriesRequest
	1, // 6: app.supports_terms.SupportsTermsService.GetFaq:output_type -> app.supports_terms.GetFaqResponse
	3, // 7: app.supports_terms.SupportsTermsService.TermsAgreement:output_type -> app.supports_terms.TermsAgreementResponse
	5, // 8: app.supports_terms.SupportsTermsService.TermsAgreementHistories:output_type -> app.supports_terms.TermsAgreementHistoriesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_supports_terms_supports_terms_service_proto_init() }
func file_app_supports_terms_supports_terms_service_proto_init() {
	if File_app_supports_terms_supports_terms_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_supports_terms_supports_terms_service_proto_rawDesc), len(file_app_supports_terms_supports_terms_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_supports_terms_supports_terms_service_proto_goTypes,
		DependencyIndexes: file_app_supports_terms_supports_terms_service_proto_depIdxs,
		MessageInfos:      file_app_supports_terms_supports_terms_service_proto_msgTypes,
	}.Build()
	File_app_supports_terms_supports_terms_service_proto = out.File
	file_app_supports_terms_supports_terms_service_proto_goTypes = nil
	file_app_supports_terms_supports_terms_service_proto_depIdxs = nil
}
