// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: app/memory/memory_service.proto

package memory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_UnlockMemoryMusic_FullMethodName    = "/app.memory.MemoryService/UnlockMemoryMusic"
	MemoryService_UnlockMemoryMember_FullMethodName   = "/app.memory.MemoryService/UnlockMemoryMember"
	MemoryService_UnlockMemorySupports_FullMethodName = "/app.memory.MemoryService/UnlockMemorySupports"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	UnlockMemoryMusic(ctx context.Context, in *UnlockMemoryMusicRequest, opts ...grpc.CallOption) (*UnlockMemoryMusicResponse, error)
	UnlockMemoryMember(ctx context.Context, in *UnlockMemoryMemberRequest, opts ...grpc.CallOption) (*UnlockMemoryMemberResponse, error)
	UnlockMemorySupports(ctx context.Context, in *UnlockMemorySupportsRequest, opts ...grpc.CallOption) (*UnlockMemorySupportsResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) UnlockMemoryMusic(ctx context.Context, in *UnlockMemoryMusicRequest, opts ...grpc.CallOption) (*UnlockMemoryMusicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockMemoryMusicResponse)
	err := c.cc.Invoke(ctx, MemoryService_UnlockMemoryMusic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) UnlockMemoryMember(ctx context.Context, in *UnlockMemoryMemberRequest, opts ...grpc.CallOption) (*UnlockMemoryMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockMemoryMemberResponse)
	err := c.cc.Invoke(ctx, MemoryService_UnlockMemoryMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) UnlockMemorySupports(ctx context.Context, in *UnlockMemorySupportsRequest, opts ...grpc.CallOption) (*UnlockMemorySupportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockMemorySupportsResponse)
	err := c.cc.Invoke(ctx, MemoryService_UnlockMemorySupports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
type MemoryServiceServer interface {
	UnlockMemoryMusic(context.Context, *UnlockMemoryMusicRequest) (*UnlockMemoryMusicResponse, error)
	UnlockMemoryMember(context.Context, *UnlockMemoryMemberRequest) (*UnlockMemoryMemberResponse, error)
	UnlockMemorySupports(context.Context, *UnlockMemorySupportsRequest) (*UnlockMemorySupportsResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) UnlockMemoryMusic(context.Context, *UnlockMemoryMusicRequest) (*UnlockMemoryMusicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockMemoryMusic not implemented")
}
func (UnimplementedMemoryServiceServer) UnlockMemoryMember(context.Context, *UnlockMemoryMemberRequest) (*UnlockMemoryMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockMemoryMember not implemented")
}
func (UnimplementedMemoryServiceServer) UnlockMemorySupports(context.Context, *UnlockMemorySupportsRequest) (*UnlockMemorySupportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockMemorySupports not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_UnlockMemoryMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockMemoryMusicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UnlockMemoryMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_UnlockMemoryMusic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UnlockMemoryMusic(ctx, req.(*UnlockMemoryMusicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_UnlockMemoryMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockMemoryMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UnlockMemoryMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_UnlockMemoryMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UnlockMemoryMember(ctx, req.(*UnlockMemoryMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_UnlockMemorySupports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockMemorySupportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UnlockMemorySupports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_UnlockMemorySupports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UnlockMemorySupports(ctx, req.(*UnlockMemorySupportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.memory.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnlockMemoryMusic",
			Handler:    _MemoryService_UnlockMemoryMusic_Handler,
		},
		{
			MethodName: "UnlockMemoryMember",
			Handler:    _MemoryService_UnlockMemoryMember_Handler,
		},
		{
			MethodName: "UnlockMemorySupports",
			Handler:    _MemoryService_UnlockMemorySupports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/memory/memory_service.proto",
}
