// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/activity/activity_service.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	StartAt       int64                  `protobuf:"varint,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Display       int32                  `protobuf:"varint,6,opt,name=display,proto3" json:"display,omitempty"`
	IconSeqId     int32                  `protobuf:"varint,7,opt,name=icon_seq_id,json=iconSeqId,proto3" json:"icon_seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityConfig) Reset() {
	*x = ActivityConfig{}
	mi := &file_app_activity_activity_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityConfig) ProtoMessage() {}

func (x *ActivityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_activity_activity_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityConfig.ProtoReflect.Descriptor instead.
func (*ActivityConfig) Descriptor() ([]byte, []int) {
	return file_app_activity_activity_service_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityConfig) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ActivityConfig) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *ActivityConfig) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *ActivityConfig) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

func (x *ActivityConfig) GetIconSeqId() int32 {
	if x != nil {
		return x.IconSeqId
	}
	return 0
}

type GetAllActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActivitiesRequest) Reset() {
	*x = GetAllActivitiesRequest{}
	mi := &file_app_activity_activity_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActivitiesRequest) ProtoMessage() {}

func (x *GetAllActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_activity_activity_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetAllActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_app_activity_activity_service_proto_rawDescGZIP(), []int{1}
}

type GetAllActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityConfig      `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActivitiesResponse) Reset() {
	*x = GetAllActivitiesResponse{}
	mi := &file_app_activity_activity_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActivitiesResponse) ProtoMessage() {}

func (x *GetAllActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_activity_activity_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActivitiesResponse.ProtoReflect.Descriptor instead.
func (*GetAllActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_app_activity_activity_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllActivitiesResponse) GetActivities() []*ActivityConfig {
	if x != nil {
		return x.Activities
	}
	return nil
}

var File_app_activity_activity_service_proto protoreflect.FileDescriptor

const file_app_activity_activity_service_proto_rawDesc = "" +
	"\n" +
	"#app/activity/activity_service.proto\x12\fapp.activity\"\xc5\x01\n" +
	"\x0eActivityConfig\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\x03R\x05endAt\x12\x18\n" +
	"\adisplay\x18\x06 \x01(\x05R\adisplay\x12\x1e\n" +
	"\vicon_seq_id\x18\a \x01(\x05R\ticonSeqId\"\x19\n" +
	"\x17GetAllActivitiesRequest\"X\n" +
	"\x18GetAllActivitiesResponse\x12<\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1c.app.activity.ActivityConfigR\n" +
	"activities2t\n" +
	"\x0fActivityService\x12a\n" +
	"\x10GetAllActivities\x12%.app.activity.GetAllActivitiesRequest\x1a&.app.activity.GetAllActivitiesResponseB\x18\xaa\x02\x15App.Protobuf.Activityb\x06proto3"

var (
	file_app_activity_activity_service_proto_rawDescOnce sync.Once
	file_app_activity_activity_service_proto_rawDescData []byte
)

func file_app_activity_activity_service_proto_rawDescGZIP() []byte {
	file_app_activity_activity_service_proto_rawDescOnce.Do(func() {
		file_app_activity_activity_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_activity_activity_service_proto_rawDesc), len(file_app_activity_activity_service_proto_rawDesc)))
	})
	return file_app_activity_activity_service_proto_rawDescData
}

var file_app_activity_activity_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_activity_activity_service_proto_goTypes = []any{
	(*ActivityConfig)(nil),           // 0: app.activity.ActivityConfig
	(*GetAllActivitiesRequest)(nil),  // 1: app.activity.GetAllActivitiesRequest
	(*GetAllActivitiesResponse)(nil), // 2: app.activity.GetAllActivitiesResponse
}
var file_app_activity_activity_service_proto_depIdxs = []int32{
	0, // 0: app.activity.GetAllActivitiesResponse.activities:type_name -> app.activity.ActivityConfig
	1, // 1: app.activity.ActivityService.GetAllActivities:input_type -> app.activity.GetAllActivitiesRequest
	2, // 2: app.activity.ActivityService.GetAllActivities:output_type -> app.activity.GetAllActivitiesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_activity_activity_service_proto_init() }
func file_app_activity_activity_service_proto_init() {
	if File_app_activity_activity_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_activity_activity_service_proto_rawDesc), len(file_app_activity_activity_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_activity_activity_service_proto_goTypes,
		DependencyIndexes: file_app_activity_activity_service_proto_depIdxs,
		MessageInfos:      file_app_activity_activity_service_proto_msgTypes,
	}.Build()
	File_app_activity_activity_service_proto = out.File
	file_app_activity_activity_service_proto_goTypes = nil
	file_app_activity_activity_service_proto_depIdxs = nil
}
