// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/pieceexchange/pieceexchange_service.proto

package pieceexchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PieceExchangeRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pieces        []*Piece                `protobuf:"bytes,1,rep,name=pieces,proto3" json:"pieces,omitempty"`
	SupportCards  []*DuplicateSupportCard `protobuf:"bytes,2,rep,name=support_cards,json=supportCards,proto3" json:"support_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceExchangeRequest) Reset() {
	*x = PieceExchangeRequest{}
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceExchangeRequest) ProtoMessage() {}

func (x *PieceExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceExchangeRequest.ProtoReflect.Descriptor instead.
func (*PieceExchangeRequest) Descriptor() ([]byte, []int) {
	return file_app_pieceexchange_pieceexchange_service_proto_rawDescGZIP(), []int{0}
}

func (x *PieceExchangeRequest) GetPieces() []*Piece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *PieceExchangeRequest) GetSupportCards() []*DuplicateSupportCard {
	if x != nil {
		return x.SupportCards
	}
	return nil
}

type PieceExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceExchangeResponse) Reset() {
	*x = PieceExchangeResponse{}
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceExchangeResponse) ProtoMessage() {}

func (x *PieceExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceExchangeResponse.ProtoReflect.Descriptor instead.
func (*PieceExchangeResponse) Descriptor() ([]byte, []int) {
	return file_app_pieceexchange_pieceexchange_service_proto_rawDescGZIP(), []int{1}
}

func (x *PieceExchangeResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_app_pieceexchange_pieceexchange_service_proto_rawDescGZIP(), []int{2}
}

func (x *Piece) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Piece) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DuplicateSupportCard struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportCardMasterId int64                  `protobuf:"varint,1,opt,name=support_card_master_id,json=supportCardMasterId,proto3" json:"support_card_master_id,omitempty"`
	Count               int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DuplicateSupportCard) Reset() {
	*x = DuplicateSupportCard{}
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateSupportCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateSupportCard) ProtoMessage() {}

func (x *DuplicateSupportCard) ProtoReflect() protoreflect.Message {
	mi := &file_app_pieceexchange_pieceexchange_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateSupportCard.ProtoReflect.Descriptor instead.
func (*DuplicateSupportCard) Descriptor() ([]byte, []int) {
	return file_app_pieceexchange_pieceexchange_service_proto_rawDescGZIP(), []int{3}
}

func (x *DuplicateSupportCard) GetSupportCardMasterId() int64 {
	if x != nil {
		return x.SupportCardMasterId
	}
	return 0
}

func (x *DuplicateSupportCard) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_app_pieceexchange_pieceexchange_service_proto protoreflect.FileDescriptor

const file_app_pieceexchange_pieceexchange_service_proto_rawDesc = "" +
	"\n" +
	"-app/pieceexchange/pieceexchange_service.proto\x12\x11app.pieceexchange\x1a\x19entity/notification.proto\"\x96\x01\n" +
	"\x14PieceExchangeRequest\x120\n" +
	"\x06pieces\x18\x01 \x03(\v2\x18.app.pieceexchange.PieceR\x06pieces\x12L\n" +
	"\rsupport_cards\x18\x02 \x03(\v2'.app.pieceexchange.DuplicateSupportCardR\fsupportCards\"Q\n" +
	"\x15PieceExchangeResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification\"-\n" +
	"\x05Piece\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"a\n" +
	"\x14DuplicateSupportCard\x123\n" +
	"\x16support_card_master_id\x18\x01 \x01(\x03R\x13supportCardMasterId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2u\n" +
	"\x14PieceExchangeService\x12]\n" +
	"\bExchange\x12'.app.pieceexchange.PieceExchangeRequest\x1a(.app.pieceexchange.PieceExchangeResponseB\x1d\xaa\x02\x1aApp.Protobuf.PieceExchangeb\x06proto3"

var (
	file_app_pieceexchange_pieceexchange_service_proto_rawDescOnce sync.Once
	file_app_pieceexchange_pieceexchange_service_proto_rawDescData []byte
)

func file_app_pieceexchange_pieceexchange_service_proto_rawDescGZIP() []byte {
	file_app_pieceexchange_pieceexchange_service_proto_rawDescOnce.Do(func() {
		file_app_pieceexchange_pieceexchange_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_pieceexchange_pieceexchange_service_proto_rawDesc), len(file_app_pieceexchange_pieceexchange_service_proto_rawDesc)))
	})
	return file_app_pieceexchange_pieceexchange_service_proto_rawDescData
}

var file_app_pieceexchange_pieceexchange_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_pieceexchange_pieceexchange_service_proto_goTypes = []any{
	(*PieceExchangeRequest)(nil),  // 0: app.pieceexchange.PieceExchangeRequest
	(*PieceExchangeResponse)(nil), // 1: app.pieceexchange.PieceExchangeResponse
	(*Piece)(nil),                 // 2: app.pieceexchange.Piece
	(*DuplicateSupportCard)(nil),  // 3: app.pieceexchange.DuplicateSupportCard
	(*entity.Notification)(nil),   // 4: entity.Notification
}
var file_app_pieceexchange_pieceexchange_service_proto_depIdxs = []int32{
	2, // 0: app.pieceexchange.PieceExchangeRequest.pieces:type_name -> app.pieceexchange.Piece
	3, // 1: app.pieceexchange.PieceExchangeRequest.support_cards:type_name -> app.pieceexchange.DuplicateSupportCard
	4, // 2: app.pieceexchange.PieceExchangeResponse.notification:type_name -> entity.Notification
	0, // 3: app.pieceexchange.PieceExchangeService.Exchange:input_type -> app.pieceexchange.PieceExchangeRequest
	1, // 4: app.pieceexchange.PieceExchangeService.Exchange:output_type -> app.pieceexchange.PieceExchangeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_pieceexchange_pieceexchange_service_proto_init() }
func file_app_pieceexchange_pieceexchange_service_proto_init() {
	if File_app_pieceexchange_pieceexchange_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_pieceexchange_pieceexchange_service_proto_rawDesc), len(file_app_pieceexchange_pieceexchange_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_pieceexchange_pieceexchange_service_proto_goTypes,
		DependencyIndexes: file_app_pieceexchange_pieceexchange_service_proto_depIdxs,
		MessageInfos:      file_app_pieceexchange_pieceexchange_service_proto_msgTypes,
	}.Build()
	File_app_pieceexchange_pieceexchange_service_proto = out.File
	file_app_pieceexchange_pieceexchange_service_proto_goTypes = nil
	file_app_pieceexchange_pieceexchange_service_proto_depIdxs = nil
}
