syntax = "proto3";

package app.player;

option go_package = "private-notes/game/proto/app/player;playerpb";

import "entity/player.proto";

message RegisterRequest {
  string initial_data_group = 1;
}

message RegisterResponse {
  entity.PlayerCredential credential = 1;
  int64 profile_id = 2;
}

message WhoamiRequest {}

message WhoamiResponse {
  string player_id = 1;
}

service PlayerService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Whoami(WhoamiRequest) returns (WhoamiResponse);
}
