// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/circleinvitation/circleinvitation_service.proto

package circleinvitation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	entity "private-notes/game/proto/entity"
	_ "private-notes/game/proto/entity/method_options"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteCircleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *string                `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3,oneof" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCircleRequest) Reset() {
	*x = InviteCircleRequest{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCircleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCircleRequest) ProtoMessage() {}

func (x *InviteCircleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCircleRequest.ProtoReflect.Descriptor instead.
func (*InviteCircleRequest) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{0}
}

func (x *InviteCircleRequest) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

type RevokeCircleInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *string                `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3,oneof" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCircleInvitationRequest) Reset() {
	*x = RevokeCircleInvitationRequest{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCircleInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCircleInvitationRequest) ProtoMessage() {}

func (x *RevokeCircleInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCircleInvitationRequest.ProtoReflect.Descriptor instead.
func (*RevokeCircleInvitationRequest) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeCircleInvitationRequest) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

type GetInvitationListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvitationListRequest) Reset() {
	*x = GetInvitationListRequest{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitationListRequest) ProtoMessage() {}

func (x *GetInvitationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitationListRequest.ProtoReflect.Descriptor instead.
func (*GetInvitationListRequest) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{2}
}

type GetInvitationListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Invitations   []*entity.CircleInvitation `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvitationListResponse) Reset() {
	*x = GetInvitationListResponse{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitationListResponse) ProtoMessage() {}

func (x *GetInvitationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitationListResponse.ProtoReflect.Descriptor instead.
func (*GetInvitationListResponse) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvitationListResponse) GetInvitations() []*entity.CircleInvitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type GetCircleInvitationRecommendListResponse struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	PlayerBasicProfiles []*entity.PlayerSimpleProfile `protobuf:"bytes,1,rep,name=player_basic_profiles,json=playerBasicProfiles,proto3" json:"player_basic_profiles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCircleInvitationRecommendListResponse) Reset() {
	*x = GetCircleInvitationRecommendListResponse{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCircleInvitationRecommendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCircleInvitationRecommendListResponse) ProtoMessage() {}

func (x *GetCircleInvitationRecommendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCircleInvitationRecommendListResponse.ProtoReflect.Descriptor instead.
func (*GetCircleInvitationRecommendListResponse) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCircleInvitationRecommendListResponse) GetPlayerBasicProfiles() []*entity.PlayerSimpleProfile {
	if x != nil {
		return x.PlayerBasicProfiles
	}
	return nil
}

type GetInvitablePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *string                `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3,oneof" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvitablePlayerRequest) Reset() {
	*x = GetInvitablePlayerRequest{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitablePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitablePlayerRequest) ProtoMessage() {}

func (x *GetInvitablePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitablePlayerRequest.ProtoReflect.Descriptor instead.
func (*GetInvitablePlayerRequest) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvitablePlayerRequest) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

type GetInvitablePlayerResponse struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	PlayerBasicProfile *entity.PlayerSimpleProfile `protobuf:"bytes,1,opt,name=player_basic_profile,json=playerBasicProfile,proto3" json:"player_basic_profile,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInvitablePlayerResponse) Reset() {
	*x = GetInvitablePlayerResponse{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitablePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitablePlayerResponse) ProtoMessage() {}

func (x *GetInvitablePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitablePlayerResponse.ProtoReflect.Descriptor instead.
func (*GetInvitablePlayerResponse) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvitablePlayerResponse) GetPlayerBasicProfile() *entity.PlayerSimpleProfile {
	if x != nil {
		return x.PlayerBasicProfile
	}
	return nil
}

type GetInvitingPlayerResponse struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	PlayerBasicProfiles []*entity.PlayerSimpleProfile `protobuf:"bytes,1,rep,name=player_basic_profiles,json=playerBasicProfiles,proto3" json:"player_basic_profiles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInvitingPlayerResponse) Reset() {
	*x = GetInvitingPlayerResponse{}
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitingPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitingPlayerResponse) ProtoMessage() {}

func (x *GetInvitingPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_circleinvitation_circleinvitation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitingPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetInvitingPlayerResponse) Descriptor() ([]byte, []int) {
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetInvitingPlayerResponse) GetPlayerBasicProfiles() []*entity.PlayerSimpleProfile {
	if x != nil {
		return x.PlayerBasicProfiles
	}
	return nil
}

var File_app_circleinvitation_circleinvitation_service_proto protoreflect.FileDescriptor

const file_app_circleinvitation_circleinvitation_service_proto_rawDesc = "" +
	"\n" +
	"3app/circleinvitation/circleinvitation_service.proto\x12\x14app.circleinvitation\x1a\x1eentity/circle_invitation.proto\x1a*entity/method_options/method_options.proto\x1a\x1bentity/player_profile.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x13InviteCircleRequest\x12 \n" +
	"\tplayer_id\x18\x01 \x01(\tH\x00R\bplayerId\x88\x01\x01B\f\n" +
	"\n" +
	"_player_id\"O\n" +
	"\x1dRevokeCircleInvitationRequest\x12 \n" +
	"\tplayer_id\x18\x01 \x01(\tH\x00R\bplayerId\x88\x01\x01B\f\n" +
	"\n" +
	"_player_id\"\x1a\n" +
	"\x18GetInvitationListRequest\"W\n" +
	"\x19GetInvitationListResponse\x12:\n" +
	"\vinvitations\x18\x01 \x03(\v2\x18.entity.CircleInvitationR\vinvitations\"{\n" +
	"(GetCircleInvitationRecommendListResponse\x12O\n" +
	"\x15player_basic_profiles\x18\x01 \x03(\v2\x1b.entity.PlayerSimpleProfileR\x13playerBasicProfiles\"K\n" +
	"\x19GetInvitablePlayerRequest\x12 \n" +
	"\tplayer_id\x18\x01 \x01(\tH\x00R\bplayerId\x88\x01\x01B\f\n" +
	"\n" +
	"_player_id\"k\n" +
	"\x1aGetInvitablePlayerResponse\x12M\n" +
	"\x14player_basic_profile\x18\x01 \x01(\v2\x1b.entity.PlayerSimpleProfileR\x12playerBasicProfile\"l\n" +
	"\x19GetInvitingPlayerResponse\x12O\n" +
	"\x15player_basic_profiles\x18\x01 \x03(\v2\x1b.entity.PlayerSimpleProfileR\x13playerBasicProfiles2\xcd\x05\n" +
	"\x17CircleInvitationService\x12Y\n" +
	"\fInviteCircle\x12).app.circleinvitation.InviteCircleRequest\x1a\x16.google.protobuf.Empty\"\x06\x92\xb5\x18\x020\x01\x12m\n" +
	"\x16RevokeCircleInvitation\x123.app.circleinvitation.RevokeCircleInvitationRequest\x1a\x16.google.protobuf.Empty\"\x06\x92\xb5\x18\x020\x01\x12|\n" +
	"\x11GetInvitationList\x12..app.circleinvitation.GetInvitationListRequest\x1a/.app.circleinvitation.GetInvitationListResponse\"\x06\x92\xb5\x18\x020\x01\x12\x82\x01\n" +
	" GetCircleInvitationRecommendList\x12\x16.google.protobuf.Empty\x1a>.app.circleinvitation.GetCircleInvitationRecommendListResponse\"\x06\x92\xb5\x18\x020\x01\x12\x7f\n" +
	"\x12GetInvitablePlayer\x12/.app.circleinvitation.GetInvitablePlayerRequest\x1a0.app.circleinvitation.GetInvitablePlayerResponse\"\x06\x92\xb5\x18\x020\x01\x12d\n" +
	"\x11GetInvitingPlayer\x12\x16.google.protobuf.Empty\x1a/.app.circleinvitation.GetInvitingPlayerResponse\"\x06\x92\xb5\x18\x020\x01B \xaa\x02\x1dApp.Protobuf.CircleInvitationb\x06proto3"

var (
	file_app_circleinvitation_circleinvitation_service_proto_rawDescOnce sync.Once
	file_app_circleinvitation_circleinvitation_service_proto_rawDescData []byte
)

func file_app_circleinvitation_circleinvitation_service_proto_rawDescGZIP() []byte {
	file_app_circleinvitation_circleinvitation_service_proto_rawDescOnce.Do(func() {
		file_app_circleinvitation_circleinvitation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_circleinvitation_circleinvitation_service_proto_rawDesc), len(file_app_circleinvitation_circleinvitation_service_proto_rawDesc)))
	})
	return file_app_circleinvitation_circleinvitation_service_proto_rawDescData
}

var file_app_circleinvitation_circleinvitation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_circleinvitation_circleinvitation_service_proto_goTypes = []any{
	(*InviteCircleRequest)(nil),                      // 0: app.circleinvitation.InviteCircleRequest
	(*RevokeCircleInvitationRequest)(nil),            // 1: app.circleinvitation.RevokeCircleInvitationRequest
	(*GetInvitationListRequest)(nil),                 // 2: app.circleinvitation.GetInvitationListRequest
	(*GetInvitationListResponse)(nil),                // 3: app.circleinvitation.GetInvitationListResponse
	(*GetCircleInvitationRecommendListResponse)(nil), // 4: app.circleinvitation.GetCircleInvitationRecommendListResponse
	(*GetInvitablePlayerRequest)(nil),                // 5: app.circleinvitation.GetInvitablePlayerRequest
	(*GetInvitablePlayerResponse)(nil),               // 6: app.circleinvitation.GetInvitablePlayerResponse
	(*GetInvitingPlayerResponse)(nil),                // 7: app.circleinvitation.GetInvitingPlayerResponse
	(*entity.CircleInvitation)(nil),                  // 8: entity.CircleInvitation
	(*entity.PlayerSimpleProfile)(nil),               // 9: entity.PlayerSimpleProfile
	(*emptypb.Empty)(nil),                            // 10: google.protobuf.Empty
}
var file_app_circleinvitation_circleinvitation_service_proto_depIdxs = []int32{
	8,  // 0: app.circleinvitation.GetInvitationListResponse.invitations:type_name -> entity.CircleInvitation
	9,  // 1: app.circleinvitation.GetCircleInvitationRecommendListResponse.player_basic_profiles:type_name -> entity.PlayerSimpleProfile
	9,  // 2: app.circleinvitation.GetInvitablePlayerResponse.player_basic_profile:type_name -> entity.PlayerSimpleProfile
	9,  // 3: app.circleinvitation.GetInvitingPlayerResponse.player_basic_profiles:type_name -> entity.PlayerSimpleProfile
	0,  // 4: app.circleinvitation.CircleInvitationService.InviteCircle:input_type -> app.circleinvitation.InviteCircleRequest
	1,  // 5: app.circleinvitation.CircleInvitationService.RevokeCircleInvitation:input_type -> app.circleinvitation.RevokeCircleInvitationRequest
	2,  // 6: app.circleinvitation.CircleInvitationService.GetInvitationList:input_type -> app.circleinvitation.GetInvitationListRequest
	10, // 7: app.circleinvitation.CircleInvitationService.GetCircleInvitationRecommendList:input_type -> google.protobuf.Empty
	5,  // 8: app.circleinvitation.CircleInvitationService.GetInvitablePlayer:input_type -> app.circleinvitation.GetInvitablePlayerRequest
	10, // 9: app.circleinvitation.CircleInvitationService.GetInvitingPlayer:input_type -> google.protobuf.Empty
	10, // 10: app.circleinvitation.CircleInvitationService.InviteCircle:output_type -> google.protobuf.Empty
	10, // 11: app.circleinvitation.CircleInvitationService.RevokeCircleInvitation:output_type -> google.protobuf.Empty
	3,  // 12: app.circleinvitation.CircleInvitationService.GetInvitationList:output_type -> app.circleinvitation.GetInvitationListResponse
	4,  // 13: app.circleinvitation.CircleInvitationService.GetCircleInvitationRecommendList:output_type -> app.circleinvitation.GetCircleInvitationRecommendListResponse
	6,  // 14: app.circleinvitation.CircleInvitationService.GetInvitablePlayer:output_type -> app.circleinvitation.GetInvitablePlayerResponse
	7,  // 15: app.circleinvitation.CircleInvitationService.GetInvitingPlayer:output_type -> app.circleinvitation.GetInvitingPlayerResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_circleinvitation_circleinvitation_service_proto_init() }
func file_app_circleinvitation_circleinvitation_service_proto_init() {
	if File_app_circleinvitation_circleinvitation_service_proto != nil {
		return
	}
	file_app_circleinvitation_circleinvitation_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_app_circleinvitation_circleinvitation_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_app_circleinvitation_circleinvitation_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_circleinvitation_circleinvitation_service_proto_rawDesc), len(file_app_circleinvitation_circleinvitation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_circleinvitation_circleinvitation_service_proto_goTypes,
		DependencyIndexes: file_app_circleinvitation_circleinvitation_service_proto_depIdxs,
		MessageInfos:      file_app_circleinvitation_circleinvitation_service_proto_msgTypes,
	}.Build()
	File_app_circleinvitation_circleinvitation_service_proto = out.File
	file_app_circleinvitation_circleinvitation_service_proto_goTypes = nil
	file_app_circleinvitation_circleinvitation_service_proto_depIdxs = nil
}
