// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/admin_user.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminRole int32

const (
	AdminRole_ADMINROLE_DEVELOPER     AdminRole = 0
	AdminRole_ADMINROLE_OPERATORADMIN AdminRole = 1
	AdminRole_ADMINROLE_OPERATOR      AdminRole = 2
	AdminRole_ADMINROLE_SPECIFIC      AdminRole = 3
	AdminRole_ADMINROLE_VIEWONLY      AdminRole = 4
)

// Enum value maps for AdminRole.
var (
	AdminRole_name = map[int32]string{
		0: "ADMINROLE_DEVELOPER",
		1: "ADMINROLE_OPERATORADMIN",
		2: "ADMINROLE_OPERATOR",
		3: "ADMINROLE_SPECIFIC",
		4: "ADMINROLE_VIEWONLY",
	}
	AdminRole_value = map[string]int32{
		"ADMINROLE_DEVELOPER":     0,
		"ADMINROLE_OPERATORADMIN": 1,
		"ADMINROLE_OPERATOR":      2,
		"ADMINROLE_SPECIFIC":      3,
		"ADMINROLE_VIEWONLY":      4,
	}
)

func (x AdminRole) Enum() *AdminRole {
	p := new(AdminRole)
	*p = x
	return p
}

func (x AdminRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminRole) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_admin_user_proto_enumTypes[0].Descriptor()
}

func (AdminRole) Type() protoreflect.EnumType {
	return &file_entity_admin_user_proto_enumTypes[0]
}

func (x AdminRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminRole.Descriptor instead.
func (AdminRole) EnumDescriptor() ([]byte, []int) {
	return file_entity_admin_user_proto_rawDescGZIP(), []int{0}
}

type AdminUser struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MailAddress      string                 `protobuf:"bytes,1,opt,name=mail_address,json=mailAddress,proto3" json:"mail_address,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role             AdminRole              `protobuf:"varint,3,opt,name=role,proto3,enum=entity.AdminRole" json:"role,omitempty"`
	AccessTokenCount uint32                 `protobuf:"varint,4,opt,name=access_token_count,json=accessTokenCount,proto3" json:"access_token_count,omitempty"`
	GoogleId         string                 `protobuf:"bytes,5,opt,name=google_id,json=googleId,proto3" json:"google_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_entity_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_entity_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_entity_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetMailAddress() string {
	if x != nil {
		return x.MailAddress
	}
	return ""
}

func (x *AdminUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUser) GetRole() AdminRole {
	if x != nil {
		return x.Role
	}
	return AdminRole_ADMINROLE_DEVELOPER
}

func (x *AdminUser) GetAccessTokenCount() uint32 {
	if x != nil {
		return x.AccessTokenCount
	}
	return 0
}

func (x *AdminUser) GetGoogleId() string {
	if x != nil {
		return x.GoogleId
	}
	return ""
}

var File_entity_admin_user_proto protoreflect.FileDescriptor

const file_entity_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x17entity/admin_user.proto\x12\x06entity\"\xb4\x01\n" +
	"\tAdminUser\x12!\n" +
	"\fmail_address\x18\x01 \x01(\tR\vmailAddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.entity.AdminRoleR\x04role\x12,\n" +
	"\x12access_token_count\x18\x04 \x01(\rR\x10accessTokenCount\x12\x1b\n" +
	"\tgoogle_id\x18\x05 \x01(\tR\bgoogleId*\x89\x01\n" +
	"\tAdminRole\x12\x17\n" +
	"\x13ADMINROLE_DEVELOPER\x10\x00\x12\x1b\n" +
	"\x17ADMINROLE_OPERATORADMIN\x10\x01\x12\x16\n" +
	"\x12ADMINROLE_OPERATOR\x10\x02\x12\x16\n" +
	"\x12ADMINROLE_SPECIFIC\x10\x03\x12\x16\n" +
	"\x12ADMINROLE_VIEWONLY\x10\x04B\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_admin_user_proto_rawDescOnce sync.Once
	file_entity_admin_user_proto_rawDescData []byte
)

func file_entity_admin_user_proto_rawDescGZIP() []byte {
	file_entity_admin_user_proto_rawDescOnce.Do(func() {
		file_entity_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_admin_user_proto_rawDesc), len(file_entity_admin_user_proto_rawDesc)))
	})
	return file_entity_admin_user_proto_rawDescData
}

var file_entity_admin_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entity_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_admin_user_proto_goTypes = []any{
	(AdminRole)(0),    // 0: entity.AdminRole
	(*AdminUser)(nil), // 1: entity.AdminUser
}
var file_entity_admin_user_proto_depIdxs = []int32{
	0, // 0: entity.AdminUser.role:type_name -> entity.AdminRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entity_admin_user_proto_init() }
func file_entity_admin_user_proto_init() {
	if File_entity_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_admin_user_proto_rawDesc), len(file_entity_admin_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_admin_user_proto_goTypes,
		DependencyIndexes: file_entity_admin_user_proto_depIdxs,
		EnumInfos:         file_entity_admin_user_proto_enumTypes,
		MessageInfos:      file_entity_admin_user_proto_msgTypes,
	}.Build()
	File_entity_admin_user_proto = out.File
	file_entity_admin_user_proto_goTypes = nil
	file_entity_admin_user_proto_depIdxs = nil
}
