// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/carousel_help.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarouselHelp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      int64                  `protobuf:"varint,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarouselHelp) Reset() {
	*x = CarouselHelp{}
	mi := &file_entity_carousel_help_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarouselHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarouselHelp) ProtoMessage() {}

func (x *CarouselHelp) ProtoReflect() protoreflect.Message {
	mi := &file_entity_carousel_help_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarouselHelp.ProtoReflect.Descriptor instead.
func (*CarouselHelp) Descriptor() ([]byte, []int) {
	return file_entity_carousel_help_proto_rawDescGZIP(), []int{0}
}

func (x *CarouselHelp) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

var File_entity_carousel_help_proto protoreflect.FileDescriptor

const file_entity_carousel_help_proto_rawDesc = "" +
	"\n" +
	"\x1aentity/carousel_help.proto\x12\x06entity\"+\n" +
	"\fCarouselHelp\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\x03R\bmasterIdB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_carousel_help_proto_rawDescOnce sync.Once
	file_entity_carousel_help_proto_rawDescData []byte
)

func file_entity_carousel_help_proto_rawDescGZIP() []byte {
	file_entity_carousel_help_proto_rawDescOnce.Do(func() {
		file_entity_carousel_help_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_carousel_help_proto_rawDesc), len(file_entity_carousel_help_proto_rawDesc)))
	})
	return file_entity_carousel_help_proto_rawDescData
}

var file_entity_carousel_help_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_carousel_help_proto_goTypes = []any{
	(*CarouselHelp)(nil), // 0: entity.CarouselHelp
}
var file_entity_carousel_help_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_carousel_help_proto_init() }
func file_entity_carousel_help_proto_init() {
	if File_entity_carousel_help_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_carousel_help_proto_rawDesc), len(file_entity_carousel_help_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_carousel_help_proto_goTypes,
		DependencyIndexes: file_entity_carousel_help_proto_depIdxs,
		MessageInfos:      file_entity_carousel_help_proto_msgTypes,
	}.Build()
	File_entity_carousel_help_proto = out.File
	file_entity_carousel_help_proto_goTypes = nil
	file_entity_carousel_help_proto_depIdxs = nil
}
