// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/circle_mission.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CircleMissionProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     int64                  `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Progress      int64                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	IsCompleted   bool                   `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsReceived    bool                   `protobuf:"varint,4,opt,name=is_received,json=isReceived,proto3" json:"is_received,omitempty"`
	StartAt       int64                  `protobuf:"varint,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircleMissionProgress) Reset() {
	*x = CircleMissionProgress{}
	mi := &file_entity_circle_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircleMissionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircleMissionProgress) ProtoMessage() {}

func (x *CircleMissionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_entity_circle_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircleMissionProgress.ProtoReflect.Descriptor instead.
func (*CircleMissionProgress) Descriptor() ([]byte, []int) {
	return file_entity_circle_mission_proto_rawDescGZIP(), []int{0}
}

func (x *CircleMissionProgress) GetMissionId() int64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

func (x *CircleMissionProgress) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CircleMissionProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *CircleMissionProgress) GetIsReceived() bool {
	if x != nil {
		return x.IsReceived
	}
	return false
}

func (x *CircleMissionProgress) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

var File_entity_circle_mission_proto protoreflect.FileDescriptor

const file_entity_circle_mission_proto_rawDesc = "" +
	"\n" +
	"\x1bentity/circle_mission.proto\x12\x06entity\"\xb1\x01\n" +
	"\x15CircleMissionProgress\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x03R\tmissionId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x03R\bprogress\x12!\n" +
	"\fis_completed\x18\x03 \x01(\bR\visCompleted\x12\x1f\n" +
	"\vis_received\x18\x04 \x01(\bR\n" +
	"isReceived\x12\x19\n" +
	"\bstart_at\x18\x05 \x01(\x03R\astartAtB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_circle_mission_proto_rawDescOnce sync.Once
	file_entity_circle_mission_proto_rawDescData []byte
)

func file_entity_circle_mission_proto_rawDescGZIP() []byte {
	file_entity_circle_mission_proto_rawDescOnce.Do(func() {
		file_entity_circle_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_circle_mission_proto_rawDesc), len(file_entity_circle_mission_proto_rawDesc)))
	})
	return file_entity_circle_mission_proto_rawDescData
}

var file_entity_circle_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_circle_mission_proto_goTypes = []any{
	(*CircleMissionProgress)(nil), // 0: entity.CircleMissionProgress
}
var file_entity_circle_mission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_circle_mission_proto_init() }
func file_entity_circle_mission_proto_init() {
	if File_entity_circle_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_circle_mission_proto_rawDesc), len(file_entity_circle_mission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_circle_mission_proto_goTypes,
		DependencyIndexes: file_entity_circle_mission_proto_depIdxs,
		MessageInfos:      file_entity_circle_mission_proto_msgTypes,
	}.Build()
	File_entity_circle_mission_proto = out.File
	file_entity_circle_mission_proto_goTypes = nil
	file_entity_circle_mission_proto_depIdxs = nil
}
