// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/integrity.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestPackageName string                 `protobuf:"bytes,1,opt,name=request_package_name,json=requestPackageName,proto3" json:"request_package_name,omitempty"`
	TimestampMillis    int64                  `protobuf:"varint,2,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestDetails) Reset() {
	*x = RequestDetails{}
	mi := &file_entity_integrity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDetails) ProtoMessage() {}

func (x *RequestDetails) ProtoReflect() protoreflect.Message {
	mi := &file_entity_integrity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDetails.ProtoReflect.Descriptor instead.
func (*RequestDetails) Descriptor() ([]byte, []int) {
	return file_entity_integrity_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDetails) GetRequestPackageName() string {
	if x != nil {
		return x.RequestPackageName
	}
	return ""
}

func (x *RequestDetails) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

type AppIntegrity struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AppRecognitionVerdict   string                 `protobuf:"bytes,1,opt,name=app_recognition_verdict,json=appRecognitionVerdict,proto3" json:"app_recognition_verdict,omitempty"`
	PackageName             string                 `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	CertificateSha256Digest []string               `protobuf:"bytes,3,rep,name=certificate_sha256_digest,json=certificateSha256Digest,proto3" json:"certificate_sha256_digest,omitempty"`
	VersionCode             int64                  `protobuf:"varint,4,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AppIntegrity) Reset() {
	*x = AppIntegrity{}
	mi := &file_entity_integrity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIntegrity) ProtoMessage() {}

func (x *AppIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_integrity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIntegrity.ProtoReflect.Descriptor instead.
func (*AppIntegrity) Descriptor() ([]byte, []int) {
	return file_entity_integrity_proto_rawDescGZIP(), []int{1}
}

func (x *AppIntegrity) GetAppRecognitionVerdict() string {
	if x != nil {
		return x.AppRecognitionVerdict
	}
	return ""
}

func (x *AppIntegrity) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *AppIntegrity) GetCertificateSha256Digest() []string {
	if x != nil {
		return x.CertificateSha256Digest
	}
	return nil
}

func (x *AppIntegrity) GetVersionCode() int64 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

type DeviceIntegrity struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DeviceRecognitionVerdict []string               `protobuf:"bytes,1,rep,name=device_recognition_verdict,json=deviceRecognitionVerdict,proto3" json:"device_recognition_verdict,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeviceIntegrity) Reset() {
	*x = DeviceIntegrity{}
	mi := &file_entity_integrity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIntegrity) ProtoMessage() {}

func (x *DeviceIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_integrity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIntegrity.ProtoReflect.Descriptor instead.
func (*DeviceIntegrity) Descriptor() ([]byte, []int) {
	return file_entity_integrity_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceIntegrity) GetDeviceRecognitionVerdict() []string {
	if x != nil {
		return x.DeviceRecognitionVerdict
	}
	return nil
}

type AccountDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppLicensingVerdict string                 `protobuf:"bytes,1,opt,name=app_licensing_verdict,json=appLicensingVerdict,proto3" json:"app_licensing_verdict,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AccountDetails) Reset() {
	*x = AccountDetails{}
	mi := &file_entity_integrity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetails) ProtoMessage() {}

func (x *AccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_entity_integrity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetails.ProtoReflect.Descriptor instead.
func (*AccountDetails) Descriptor() ([]byte, []int) {
	return file_entity_integrity_proto_rawDescGZIP(), []int{3}
}

func (x *AccountDetails) GetAppLicensingVerdict() string {
	if x != nil {
		return x.AppLicensingVerdict
	}
	return ""
}

var File_entity_integrity_proto protoreflect.FileDescriptor

const file_entity_integrity_proto_rawDesc = "" +
	"\n" +
	"\x16entity/integrity.proto\x12\x06entity\"m\n" +
	"\x0eRequestDetails\x120\n" +
	"\x14request_package_name\x18\x01 \x01(\tR\x12requestPackageName\x12)\n" +
	"\x10timestamp_millis\x18\x02 \x01(\x03R\x0ftimestampMillis\"\xc8\x01\n" +
	"\fAppIntegrity\x126\n" +
	"\x17app_recognition_verdict\x18\x01 \x01(\tR\x15appRecognitionVerdict\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12:\n" +
	"\x19certificate_sha256_digest\x18\x03 \x03(\tR\x17certificateSha256Digest\x12!\n" +
	"\fversion_code\x18\x04 \x01(\x03R\vversionCode\"O\n" +
	"\x0fDeviceIntegrity\x12<\n" +
	"\x1adevice_recognition_verdict\x18\x01 \x03(\tR\x18deviceRecognitionVerdict\"D\n" +
	"\x0eAccountDetails\x122\n" +
	"\x15app_licensing_verdict\x18\x01 \x01(\tR\x13appLicensingVerdictB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_integrity_proto_rawDescOnce sync.Once
	file_entity_integrity_proto_rawDescData []byte
)

func file_entity_integrity_proto_rawDescGZIP() []byte {
	file_entity_integrity_proto_rawDescOnce.Do(func() {
		file_entity_integrity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_integrity_proto_rawDesc), len(file_entity_integrity_proto_rawDesc)))
	})
	return file_entity_integrity_proto_rawDescData
}

var file_entity_integrity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_entity_integrity_proto_goTypes = []any{
	(*RequestDetails)(nil),  // 0: entity.RequestDetails
	(*AppIntegrity)(nil),    // 1: entity.AppIntegrity
	(*DeviceIntegrity)(nil), // 2: entity.DeviceIntegrity
	(*AccountDetails)(nil),  // 3: entity.AccountDetails
}
var file_entity_integrity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_integrity_proto_init() }
func file_entity_integrity_proto_init() {
	if File_entity_integrity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_integrity_proto_rawDesc), len(file_entity_integrity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_integrity_proto_goTypes,
		DependencyIndexes: file_entity_integrity_proto_depIdxs,
		MessageInfos:      file_entity_integrity_proto_msgTypes,
	}.Build()
	File_entity_integrity_proto = out.File
	file_entity_integrity_proto_goTypes = nil
	file_entity_integrity_proto_depIdxs = nil
}
