// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/member_card.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberCard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in entity/member_card.proto.
	Id                    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterId              int64 `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Exp                   int32 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	AwakeCount            int32 `protobuf:"varint,4,opt,name=awake_count,json=awakeCount,proto3" json:"awake_count,omitempty"`
	CardRank              int32 `protobuf:"varint,5,opt,name=card_rank,json=cardRank,proto3" json:"card_rank,omitempty"`
	LeaderSkillLevel      int32 `protobuf:"varint,6,opt,name=leader_skill_level,json=leaderSkillLevel,proto3" json:"leader_skill_level,omitempty"`
	LiveSkillLevel        int32 `protobuf:"varint,7,opt,name=live_skill_level,json=liveSkillLevel,proto3" json:"live_skill_level,omitempty"`
	PerformanceSkillLevel int32 `protobuf:"varint,8,opt,name=performance_skill_level,json=performanceSkillLevel,proto3" json:"performance_skill_level,omitempty"`
	GainAt                int64 `protobuf:"varint,9,opt,name=gain_at,json=gainAt,proto3" json:"gain_at,omitempty"`
	LinkSkillLevel        int32 `protobuf:"varint,10,opt,name=link_skill_level,json=linkSkillLevel,proto3" json:"link_skill_level,omitempty"`
	GekisouSkillLevel     int32 `protobuf:"varint,11,opt,name=gekisou_skill_level,json=gekisouSkillLevel,proto3" json:"gekisou_skill_level,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MemberCard) Reset() {
	*x = MemberCard{}
	mi := &file_entity_member_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberCard) ProtoMessage() {}

func (x *MemberCard) ProtoReflect() protoreflect.Message {
	mi := &file_entity_member_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberCard.ProtoReflect.Descriptor instead.
func (*MemberCard) Descriptor() ([]byte, []int) {
	return file_entity_member_card_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in entity/member_card.proto.
func (x *MemberCard) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberCard) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *MemberCard) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *MemberCard) GetAwakeCount() int32 {
	if x != nil {
		return x.AwakeCount
	}
	return 0
}

func (x *MemberCard) GetCardRank() int32 {
	if x != nil {
		return x.CardRank
	}
	return 0
}

func (x *MemberCard) GetLeaderSkillLevel() int32 {
	if x != nil {
		return x.LeaderSkillLevel
	}
	return 0
}

func (x *MemberCard) GetLiveSkillLevel() int32 {
	if x != nil {
		return x.LiveSkillLevel
	}
	return 0
}

func (x *MemberCard) GetPerformanceSkillLevel() int32 {
	if x != nil {
		return x.PerformanceSkillLevel
	}
	return 0
}

func (x *MemberCard) GetGainAt() int64 {
	if x != nil {
		return x.GainAt
	}
	return 0
}

func (x *MemberCard) GetLinkSkillLevel() int32 {
	if x != nil {
		return x.LinkSkillLevel
	}
	return 0
}

func (x *MemberCard) GetGekisouSkillLevel() int32 {
	if x != nil {
		return x.GekisouSkillLevel
	}
	return 0
}

var File_entity_member_card_proto protoreflect.FileDescriptor

const file_entity_member_card_proto_rawDesc = "" +
	"\n" +
	"\x18entity/member_card.proto\x12\x06entity\"\x90\x03\n" +
	"\n" +
	"MemberCard\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x05B\x02\x18\x01R\x02id\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\x03R\bmasterId\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x1f\n" +
	"\vawake_count\x18\x04 \x01(\x05R\n" +
	"awakeCount\x12\x1b\n" +
	"\tcard_rank\x18\x05 \x01(\x05R\bcardRank\x12,\n" +
	"\x12leader_skill_level\x18\x06 \x01(\x05R\x10leaderSkillLevel\x12(\n" +
	"\x10live_skill_level\x18\a \x01(\x05R\x0eliveSkillLevel\x126\n" +
	"\x17performance_skill_level\x18\b \x01(\x05R\x15performanceSkillLevel\x12\x17\n" +
	"\again_at\x18\t \x01(\x03R\x06gainAt\x12(\n" +
	"\x10link_skill_level\x18\n" +
	" \x01(\x05R\x0elinkSkillLevel\x12.\n" +
	"\x13gekisou_skill_level\x18\v \x01(\x05R\x11gekisouSkillLevelB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_member_card_proto_rawDescOnce sync.Once
	file_entity_member_card_proto_rawDescData []byte
)

func file_entity_member_card_proto_rawDescGZIP() []byte {
	file_entity_member_card_proto_rawDescOnce.Do(func() {
		file_entity_member_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_member_card_proto_rawDesc), len(file_entity_member_card_proto_rawDesc)))
	})
	return file_entity_member_card_proto_rawDescData
}

var file_entity_member_card_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_member_card_proto_goTypes = []any{
	(*MemberCard)(nil), // 0: entity.MemberCard
}
var file_entity_member_card_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_member_card_proto_init() }
func file_entity_member_card_proto_init() {
	if File_entity_member_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_member_card_proto_rawDesc), len(file_entity_member_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_member_card_proto_goTypes,
		DependencyIndexes: file_entity_member_card_proto_depIdxs,
		MessageInfos:      file_entity_member_card_proto_msgTypes,
	}.Build()
	File_entity_member_card_proto = out.File
	file_entity_member_card_proto_goTypes = nil
	file_entity_member_card_proto_depIdxs = nil
}
