// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/offline_bonus.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfflineBonusResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  ResourceType           `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=entity.ResourceType" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceCount int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineBonusResource) Reset() {
	*x = OfflineBonusResource{}
	mi := &file_entity_offline_bonus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineBonusResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBonusResource) ProtoMessage() {}

func (x *OfflineBonusResource) ProtoReflect() protoreflect.Message {
	mi := &file_entity_offline_bonus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBonusResource.ProtoReflect.Descriptor instead.
func (*OfflineBonusResource) Descriptor() ([]byte, []int) {
	return file_entity_offline_bonus_proto_rawDescGZIP(), []int{0}
}

func (x *OfflineBonusResource) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *OfflineBonusResource) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *OfflineBonusResource) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type OfflineBonus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdViewCount    int32                  `protobuf:"varint,1,opt,name=ad_view_count,json=adViewCount,proto3" json:"ad_view_count,omitempty"`
	LastAdViewedAt *int64                 `protobuf:"varint,2,opt,name=last_ad_viewed_at,json=lastAdViewedAt,proto3,oneof" json:"last_ad_viewed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OfflineBonus) Reset() {
	*x = OfflineBonus{}
	mi := &file_entity_offline_bonus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineBonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBonus) ProtoMessage() {}

func (x *OfflineBonus) ProtoReflect() protoreflect.Message {
	mi := &file_entity_offline_bonus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBonus.ProtoReflect.Descriptor instead.
func (*OfflineBonus) Descriptor() ([]byte, []int) {
	return file_entity_offline_bonus_proto_rawDescGZIP(), []int{1}
}

func (x *OfflineBonus) GetAdViewCount() int32 {
	if x != nil {
		return x.AdViewCount
	}
	return 0
}

func (x *OfflineBonus) GetLastAdViewedAt() int64 {
	if x != nil && x.LastAdViewedAt != nil {
		return *x.LastAdViewedAt
	}
	return 0
}

type OfflineBonusUnit struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	OfflineBonusUnitId    int64                   `protobuf:"varint,1,opt,name=offline_bonus_unit_id,json=offlineBonusUnitId,proto3" json:"offline_bonus_unit_id,omitempty"`
	Exp                   int32                   `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	StartAt               int64                   `protobuf:"varint,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	RewardCoin            int32                   `protobuf:"varint,4,opt,name=reward_coin,json=rewardCoin,proto3" json:"reward_coin,omitempty"`
	RewardMemberExp       int32                   `protobuf:"varint,5,opt,name=reward_member_exp,json=rewardMemberExp,proto3" json:"reward_member_exp,omitempty"`
	RewardSupportExp      int32                   `protobuf:"varint,6,opt,name=reward_support_exp,json=rewardSupportExp,proto3" json:"reward_support_exp,omitempty"`
	RewardOfflineBonusExp int32                   `protobuf:"varint,7,opt,name=reward_offline_bonus_exp,json=rewardOfflineBonusExp,proto3" json:"reward_offline_bonus_exp,omitempty"`
	RewardResources       []*OfflineBonusResource `protobuf:"bytes,8,rep,name=reward_resources,json=rewardResources,proto3" json:"reward_resources,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OfflineBonusUnit) Reset() {
	*x = OfflineBonusUnit{}
	mi := &file_entity_offline_bonus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineBonusUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBonusUnit) ProtoMessage() {}

func (x *OfflineBonusUnit) ProtoReflect() protoreflect.Message {
	mi := &file_entity_offline_bonus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBonusUnit.ProtoReflect.Descriptor instead.
func (*OfflineBonusUnit) Descriptor() ([]byte, []int) {
	return file_entity_offline_bonus_proto_rawDescGZIP(), []int{2}
}

func (x *OfflineBonusUnit) GetOfflineBonusUnitId() int64 {
	if x != nil {
		return x.OfflineBonusUnitId
	}
	return 0
}

func (x *OfflineBonusUnit) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *OfflineBonusUnit) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *OfflineBonusUnit) GetRewardCoin() int32 {
	if x != nil {
		return x.RewardCoin
	}
	return 0
}

func (x *OfflineBonusUnit) GetRewardMemberExp() int32 {
	if x != nil {
		return x.RewardMemberExp
	}
	return 0
}

func (x *OfflineBonusUnit) GetRewardSupportExp() int32 {
	if x != nil {
		return x.RewardSupportExp
	}
	return 0
}

func (x *OfflineBonusUnit) GetRewardOfflineBonusExp() int32 {
	if x != nil {
		return x.RewardOfflineBonusExp
	}
	return 0
}

func (x *OfflineBonusUnit) GetRewardResources() []*OfflineBonusResource {
	if x != nil {
		return x.RewardResources
	}
	return nil
}

type OfflineBonusUnitLite struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OfflineBonusUnitId int64                  `protobuf:"varint,1,opt,name=offline_bonus_unit_id,json=offlineBonusUnitId,proto3" json:"offline_bonus_unit_id,omitempty"`
	Exp                int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	StartAt            int64                  `protobuf:"varint,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	IsStockRewards     bool                   `protobuf:"varint,4,opt,name=is_stock_rewards,json=isStockRewards,proto3" json:"is_stock_rewards,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OfflineBonusUnitLite) Reset() {
	*x = OfflineBonusUnitLite{}
	mi := &file_entity_offline_bonus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineBonusUnitLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBonusUnitLite) ProtoMessage() {}

func (x *OfflineBonusUnitLite) ProtoReflect() protoreflect.Message {
	mi := &file_entity_offline_bonus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBonusUnitLite.ProtoReflect.Descriptor instead.
func (*OfflineBonusUnitLite) Descriptor() ([]byte, []int) {
	return file_entity_offline_bonus_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineBonusUnitLite) GetOfflineBonusUnitId() int64 {
	if x != nil {
		return x.OfflineBonusUnitId
	}
	return 0
}

func (x *OfflineBonusUnitLite) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *OfflineBonusUnitLite) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *OfflineBonusUnitLite) GetIsStockRewards() bool {
	if x != nil {
		return x.IsStockRewards
	}
	return false
}

type OfflineBonusUnitResult struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	OfflineBonusUnit   *OfflineBonusUnit       `protobuf:"bytes,1,opt,name=offline_bonus_unit,json=offlineBonusUnit,proto3" json:"offline_bonus_unit,omitempty"`
	AccumulatedRewards []*OfflineBonusResource `protobuf:"bytes,2,rep,name=accumulated_rewards,json=accumulatedRewards,proto3" json:"accumulated_rewards,omitempty"`
	LotRewards         []*OfflineBonusResource `protobuf:"bytes,3,rep,name=lot_rewards,json=lotRewards,proto3" json:"lot_rewards,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OfflineBonusUnitResult) Reset() {
	*x = OfflineBonusUnitResult{}
	mi := &file_entity_offline_bonus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineBonusUnitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBonusUnitResult) ProtoMessage() {}

func (x *OfflineBonusUnitResult) ProtoReflect() protoreflect.Message {
	mi := &file_entity_offline_bonus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBonusUnitResult.ProtoReflect.Descriptor instead.
func (*OfflineBonusUnitResult) Descriptor() ([]byte, []int) {
	return file_entity_offline_bonus_proto_rawDescGZIP(), []int{4}
}

func (x *OfflineBonusUnitResult) GetOfflineBonusUnit() *OfflineBonusUnit {
	if x != nil {
		return x.OfflineBonusUnit
	}
	return nil
}

func (x *OfflineBonusUnitResult) GetAccumulatedRewards() []*OfflineBonusResource {
	if x != nil {
		return x.AccumulatedRewards
	}
	return nil
}

func (x *OfflineBonusUnitResult) GetLotRewards() []*OfflineBonusResource {
	if x != nil {
		return x.LotRewards
	}
	return nil
}

var File_entity_offline_bonus_proto protoreflect.FileDescriptor

const file_entity_offline_bonus_proto_rawDesc = "" +
	"\n" +
	"\x1aentity/offline_bonus.proto\x12\x06entity\x1a\x15entity/resource.proto\"\x99\x01\n" +
	"\x14OfflineBonusResource\x129\n" +
	"\rresource_type\x18\x01 \x01(\x0e2\x14.entity.ResourceTypeR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\x03R\n" +
	"resourceId\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCount\"x\n" +
	"\fOfflineBonus\x12\"\n" +
	"\rad_view_count\x18\x01 \x01(\x05R\vadViewCount\x12.\n" +
	"\x11last_ad_viewed_at\x18\x02 \x01(\x03H\x00R\x0elastAdViewedAt\x88\x01\x01B\x14\n" +
	"\x12_last_ad_viewed_at\"\xef\x02\n" +
	"\x10OfflineBonusUnit\x121\n" +
	"\x15offline_bonus_unit_id\x18\x01 \x01(\x03R\x12offlineBonusUnitId\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x19\n" +
	"\bstart_at\x18\x03 \x01(\x03R\astartAt\x12\x1f\n" +
	"\vreward_coin\x18\x04 \x01(\x05R\n" +
	"rewardCoin\x12*\n" +
	"\x11reward_member_exp\x18\x05 \x01(\x05R\x0frewardMemberExp\x12,\n" +
	"\x12reward_support_exp\x18\x06 \x01(\x05R\x10rewardSupportExp\x127\n" +
	"\x18reward_offline_bonus_exp\x18\a \x01(\x05R\x15rewardOfflineBonusExp\x12G\n" +
	"\x10reward_resources\x18\b \x03(\v2\x1c.entity.OfflineBonusResourceR\x0frewardResources\"\xa0\x01\n" +
	"\x14OfflineBonusUnitLite\x121\n" +
	"\x15offline_bonus_unit_id\x18\x01 \x01(\x03R\x12offlineBonusUnitId\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x19\n" +
	"\bstart_at\x18\x03 \x01(\x03R\astartAt\x12(\n" +
	"\x10is_stock_rewards\x18\x04 \x01(\bR\x0eisStockRewards\"\xee\x01\n" +
	"\x16OfflineBonusUnitResult\x12F\n" +
	"\x12offline_bonus_unit\x18\x01 \x01(\v2\x18.entity.OfflineBonusUnitR\x10offlineBonusUnit\x12M\n" +
	"\x13accumulated_rewards\x18\x02 \x03(\v2\x1c.entity.OfflineBonusResourceR\x12accumulatedRewards\x12=\n" +
	"\vlot_rewards\x18\x03 \x03(\v2\x1c.entity.OfflineBonusResourceR\n" +
	"lotRewardsB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_offline_bonus_proto_rawDescOnce sync.Once
	file_entity_offline_bonus_proto_rawDescData []byte
)

func file_entity_offline_bonus_proto_rawDescGZIP() []byte {
	file_entity_offline_bonus_proto_rawDescOnce.Do(func() {
		file_entity_offline_bonus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_offline_bonus_proto_rawDesc), len(file_entity_offline_bonus_proto_rawDesc)))
	})
	return file_entity_offline_bonus_proto_rawDescData
}

var file_entity_offline_bonus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_entity_offline_bonus_proto_goTypes = []any{
	(*OfflineBonusResource)(nil),   // 0: entity.OfflineBonusResource
	(*OfflineBonus)(nil),           // 1: entity.OfflineBonus
	(*OfflineBonusUnit)(nil),       // 2: entity.OfflineBonusUnit
	(*OfflineBonusUnitLite)(nil),   // 3: entity.OfflineBonusUnitLite
	(*OfflineBonusUnitResult)(nil), // 4: entity.OfflineBonusUnitResult
	(ResourceType)(0),              // 5: entity.ResourceType
}
var file_entity_offline_bonus_proto_depIdxs = []int32{
	5, // 0: entity.OfflineBonusResource.resource_type:type_name -> entity.ResourceType
	0, // 1: entity.OfflineBonusUnit.reward_resources:type_name -> entity.OfflineBonusResource
	2, // 2: entity.OfflineBonusUnitResult.offline_bonus_unit:type_name -> entity.OfflineBonusUnit
	0, // 3: entity.OfflineBonusUnitResult.accumulated_rewards:type_name -> entity.OfflineBonusResource
	0, // 4: entity.OfflineBonusUnitResult.lot_rewards:type_name -> entity.OfflineBonusResource
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_entity_offline_bonus_proto_init() }
func file_entity_offline_bonus_proto_init() {
	if File_entity_offline_bonus_proto != nil {
		return
	}
	file_entity_resource_proto_init()
	file_entity_offline_bonus_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_offline_bonus_proto_rawDesc), len(file_entity_offline_bonus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_offline_bonus_proto_goTypes,
		DependencyIndexes: file_entity_offline_bonus_proto_depIdxs,
		MessageInfos:      file_entity_offline_bonus_proto_msgTypes,
	}.Build()
	File_entity_offline_bonus_proto = out.File
	file_entity_offline_bonus_proto_goTypes = nil
	file_entity_offline_bonus_proto_depIdxs = nil
}
