// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/paging_info.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PagingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPage     uint32                 `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrentPage   uint32                 `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagingInfo) Reset() {
	*x = PagingInfo{}
	mi := &file_entity_paging_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagingInfo) ProtoMessage() {}

func (x *PagingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_paging_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagingInfo.ProtoReflect.Descriptor instead.
func (*PagingInfo) Descriptor() ([]byte, []int) {
	return file_entity_paging_info_proto_rawDescGZIP(), []int{0}
}

func (x *PagingInfo) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PagingInfo) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PagingInfo) GetTotalPage() uint32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *PagingInfo) GetCurrentPage() uint32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

var File_entity_paging_info_proto protoreflect.FileDescriptor

const file_entity_paging_info_proto_rawDesc = "" +
	"\n" +
	"\x18entity/paging_info.proto\x12\x06entity\"\x85\x01\n" +
	"\n" +
	"PagingInfo\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"total_page\x18\x03 \x01(\rR\ttotalPage\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\rR\vcurrentPageB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_paging_info_proto_rawDescOnce sync.Once
	file_entity_paging_info_proto_rawDescData []byte
)

func file_entity_paging_info_proto_rawDescGZIP() []byte {
	file_entity_paging_info_proto_rawDescOnce.Do(func() {
		file_entity_paging_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_paging_info_proto_rawDesc), len(file_entity_paging_info_proto_rawDesc)))
	})
	return file_entity_paging_info_proto_rawDescData
}

var file_entity_paging_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_paging_info_proto_goTypes = []any{
	(*PagingInfo)(nil), // 0: entity.PagingInfo
}
var file_entity_paging_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_paging_info_proto_init() }
func file_entity_paging_info_proto_init() {
	if File_entity_paging_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_paging_info_proto_rawDesc), len(file_entity_paging_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_paging_info_proto_goTypes,
		DependencyIndexes: file_entity_paging_info_proto_depIdxs,
		MessageInfos:      file_entity_paging_info_proto_msgTypes,
	}.Build()
	File_entity_paging_info_proto = out.File
	file_entity_paging_info_proto_goTypes = nil
	file_entity_paging_info_proto_depIdxs = nil
}
