// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/personal_notification.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExshopPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       int64                  `protobuf:"varint,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExshopPayment) Reset() {
	*x = ExshopPayment{}
	mi := &file_entity_personal_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExshopPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExshopPayment) ProtoMessage() {}

func (x *ExshopPayment) ProtoReflect() protoreflect.Message {
	mi := &file_entity_personal_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExshopPayment.ProtoReflect.Descriptor instead.
func (*ExshopPayment) Descriptor() ([]byte, []int) {
	return file_entity_personal_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ExshopPayment) GetClaimId() int64 {
	if x != nil {
		return x.ClaimId
	}
	return 0
}

func (x *ExshopPayment) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type PersonalNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExShopPayments []*ExshopPayment       `protobuf:"bytes,1,rep,name=ex_shop_payments,json=exShopPayments,proto3" json:"ex_shop_payments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonalNotification) Reset() {
	*x = PersonalNotification{}
	mi := &file_entity_personal_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalNotification) ProtoMessage() {}

func (x *PersonalNotification) ProtoReflect() protoreflect.Message {
	mi := &file_entity_personal_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalNotification.ProtoReflect.Descriptor instead.
func (*PersonalNotification) Descriptor() ([]byte, []int) {
	return file_entity_personal_notification_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalNotification) GetExShopPayments() []*ExshopPayment {
	if x != nil {
		return x.ExShopPayments
	}
	return nil
}

var File_entity_personal_notification_proto protoreflect.FileDescriptor

const file_entity_personal_notification_proto_rawDesc = "" +
	"\n" +
	"\"entity/personal_notification.proto\x12\x06entity\"C\n" +
	"\rExshopPayment\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\x03R\aclaimId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\"W\n" +
	"\x14PersonalNotification\x12?\n" +
	"\x10ex_shop_payments\x18\x01 \x03(\v2\x15.entity.ExshopPaymentR\x0eexShopPaymentsB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_personal_notification_proto_rawDescOnce sync.Once
	file_entity_personal_notification_proto_rawDescData []byte
)

func file_entity_personal_notification_proto_rawDescGZIP() []byte {
	file_entity_personal_notification_proto_rawDescOnce.Do(func() {
		file_entity_personal_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_personal_notification_proto_rawDesc), len(file_entity_personal_notification_proto_rawDesc)))
	})
	return file_entity_personal_notification_proto_rawDescData
}

var file_entity_personal_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entity_personal_notification_proto_goTypes = []any{
	(*ExshopPayment)(nil),        // 0: entity.ExshopPayment
	(*PersonalNotification)(nil), // 1: entity.PersonalNotification
}
var file_entity_personal_notification_proto_depIdxs = []int32{
	0, // 0: entity.PersonalNotification.ex_shop_payments:type_name -> entity.ExshopPayment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entity_personal_notification_proto_init() }
func file_entity_personal_notification_proto_init() {
	if File_entity_personal_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_personal_notification_proto_rawDesc), len(file_entity_personal_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_personal_notification_proto_goTypes,
		DependencyIndexes: file_entity_personal_notification_proto_depIdxs,
		MessageInfos:      file_entity_personal_notification_proto_msgTypes,
	}.Build()
	File_entity_personal_notification_proto = out.File
	file_entity_personal_notification_proto_goTypes = nil
	file_entity_personal_notification_proto_depIdxs = nil
}
