// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/player_profile.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerSimpleProfile struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RankExp                    int32                  `protobuf:"varint,3,opt,name=rank_exp,json=rankExp,proto3" json:"rank_exp,omitempty"`
	LastUpdatedAt              int64                  `protobuf:"varint,4,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	FavoriteMemberCard         *DeckMemberCardDetail  `protobuf:"bytes,5,opt,name=favorite_member_card,json=favoriteMemberCard,proto3" json:"favorite_member_card,omitempty"`
	ProfileId                  int64                  `protobuf:"varint,6,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FavoriteMemberCardMasterId int64                  `protobuf:"varint,7,opt,name=favorite_member_card_master_id,json=favoriteMemberCardMasterId,proto3" json:"favorite_member_card_master_id,omitempty"`
	ProfileCard                *SimpleProfileCard     `protobuf:"bytes,8,opt,name=profile_card,json=profileCard,proto3" json:"profile_card,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PlayerSimpleProfile) Reset() {
	*x = PlayerSimpleProfile{}
	mi := &file_entity_player_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSimpleProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSimpleProfile) ProtoMessage() {}

func (x *PlayerSimpleProfile) ProtoReflect() protoreflect.Message {
	mi := &file_entity_player_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSimpleProfile.ProtoReflect.Descriptor instead.
func (*PlayerSimpleProfile) Descriptor() ([]byte, []int) {
	return file_entity_player_profile_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerSimpleProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerSimpleProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerSimpleProfile) GetRankExp() int32 {
	if x != nil {
		return x.RankExp
	}
	return 0
}

func (x *PlayerSimpleProfile) GetLastUpdatedAt() int64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

func (x *PlayerSimpleProfile) GetFavoriteMemberCard() *DeckMemberCardDetail {
	if x != nil {
		return x.FavoriteMemberCard
	}
	return nil
}

func (x *PlayerSimpleProfile) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *PlayerSimpleProfile) GetFavoriteMemberCardMasterId() int64 {
	if x != nil {
		return x.FavoriteMemberCardMasterId
	}
	return 0
}

func (x *PlayerSimpleProfile) GetProfileCard() *SimpleProfileCard {
	if x != nil {
		return x.ProfileCard
	}
	return nil
}

type PlayerDetailProfile struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RankExp                    int32                  `protobuf:"varint,3,opt,name=rank_exp,json=rankExp,proto3" json:"rank_exp,omitempty"`
	LastUpdatedAt              int64                  `protobuf:"varint,4,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	FavoriteMemberCard         *DeckMemberCardDetail  `protobuf:"bytes,5,opt,name=favorite_member_card,json=favoriteMemberCard,proto3" json:"favorite_member_card,omitempty"`
	ProfileId                  int64                  `protobuf:"varint,6,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FavoriteMemberCardMasterId int64                  `protobuf:"varint,7,opt,name=favorite_member_card_master_id,json=favoriteMemberCardMasterId,proto3" json:"favorite_member_card_master_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PlayerDetailProfile) Reset() {
	*x = PlayerDetailProfile{}
	mi := &file_entity_player_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDetailProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDetailProfile) ProtoMessage() {}

func (x *PlayerDetailProfile) ProtoReflect() protoreflect.Message {
	mi := &file_entity_player_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDetailProfile.ProtoReflect.Descriptor instead.
func (*PlayerDetailProfile) Descriptor() ([]byte, []int) {
	return file_entity_player_profile_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerDetailProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerDetailProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerDetailProfile) GetRankExp() int32 {
	if x != nil {
		return x.RankExp
	}
	return 0
}

func (x *PlayerDetailProfile) GetLastUpdatedAt() int64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

func (x *PlayerDetailProfile) GetFavoriteMemberCard() *DeckMemberCardDetail {
	if x != nil {
		return x.FavoriteMemberCard
	}
	return nil
}

func (x *PlayerDetailProfile) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *PlayerDetailProfile) GetFavoriteMemberCardMasterId() int64 {
	if x != nil {
		return x.FavoriteMemberCardMasterId
	}
	return 0
}

type PlayerBriefInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	ChatFrameId   int64                  `protobuf:"varint,5,opt,name=chat_frame_id,json=chatFrameId,proto3" json:"chat_frame_id,omitempty"`
	ChatBubbleId  int64                  `protobuf:"varint,6,opt,name=chat_bubble_id,json=chatBubbleId,proto3" json:"chat_bubble_id,omitempty"`
	ChatThemeId   int64                  `protobuf:"varint,7,opt,name=chat_theme_id,json=chatThemeId,proto3" json:"chat_theme_id,omitempty"`
	AvatarId      int64                  `protobuf:"varint,8,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBriefInfo) Reset() {
	*x = PlayerBriefInfo{}
	mi := &file_entity_player_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBriefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBriefInfo) ProtoMessage() {}

func (x *PlayerBriefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_player_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBriefInfo.ProtoReflect.Descriptor instead.
func (*PlayerBriefInfo) Descriptor() ([]byte, []int) {
	return file_entity_player_profile_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerBriefInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerBriefInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerBriefInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerBriefInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBriefInfo) GetChatFrameId() int64 {
	if x != nil {
		return x.ChatFrameId
	}
	return 0
}

func (x *PlayerBriefInfo) GetChatBubbleId() int64 {
	if x != nil {
		return x.ChatBubbleId
	}
	return 0
}

func (x *PlayerBriefInfo) GetChatThemeId() int64 {
	if x != nil {
		return x.ChatThemeId
	}
	return 0
}

func (x *PlayerBriefInfo) GetAvatarId() int64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

var File_entity_player_profile_proto protoreflect.FileDescriptor

const file_entity_player_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bentity/player_profile.proto\x12\x06entity\x1a\x11entity/deck.proto\x1a\x18entity/profilecard.proto\"\xed\x02\n" +
	"\x13PlayerSimpleProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brank_exp\x18\x03 \x01(\x05R\arankExp\x12&\n" +
	"\x0flast_updated_at\x18\x04 \x01(\x03R\rlastUpdatedAt\x12N\n" +
	"\x14favorite_member_card\x18\x05 \x01(\v2\x1c.entity.DeckMemberCardDetailR\x12favoriteMemberCard\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x06 \x01(\x03R\tprofileId\x12B\n" +
	"\x1efavorite_member_card_master_id\x18\a \x01(\x03R\x1afavoriteMemberCardMasterId\x12<\n" +
	"\fprofile_card\x18\b \x01(\v2\x19.entity.SimpleProfileCardR\vprofileCard\"\xaf\x02\n" +
	"\x13PlayerDetailProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brank_exp\x18\x03 \x01(\x05R\arankExp\x12&\n" +
	"\x0flast_updated_at\x18\x04 \x01(\x03R\rlastUpdatedAt\x12N\n" +
	"\x14favorite_member_card\x18\x05 \x01(\v2\x1c.entity.DeckMemberCardDetailR\x12favoriteMemberCard\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x06 \x01(\x03R\tprofileId\x12B\n" +
	"\x1efavorite_member_card_master_id\x18\a \x01(\x03R\x1afavoriteMemberCardMasterId\"\x8a\x02\n" +
	"\x0fPlayerBriefInfo\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\"\n" +
	"\rchat_frame_id\x18\x05 \x01(\x03R\vchatFrameId\x12$\n" +
	"\x0echat_bubble_id\x18\x06 \x01(\x03R\fchatBubbleId\x12\"\n" +
	"\rchat_theme_id\x18\a \x01(\x03R\vchatThemeId\x12\x1b\n" +
	"\tavatar_id\x18\b \x01(\x03R\bavatarIdB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_player_profile_proto_rawDescOnce sync.Once
	file_entity_player_profile_proto_rawDescData []byte
)

func file_entity_player_profile_proto_rawDescGZIP() []byte {
	file_entity_player_profile_proto_rawDescOnce.Do(func() {
		file_entity_player_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_player_profile_proto_rawDesc), len(file_entity_player_profile_proto_rawDesc)))
	})
	return file_entity_player_profile_proto_rawDescData
}

var file_entity_player_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_entity_player_profile_proto_goTypes = []any{
	(*PlayerSimpleProfile)(nil),  // 0: entity.PlayerSimpleProfile
	(*PlayerDetailProfile)(nil),  // 1: entity.PlayerDetailProfile
	(*PlayerBriefInfo)(nil),      // 2: entity.PlayerBriefInfo
	(*DeckMemberCardDetail)(nil), // 3: entity.DeckMemberCardDetail
	(*SimpleProfileCard)(nil),    // 4: entity.SimpleProfileCard
}
var file_entity_player_profile_proto_depIdxs = []int32{
	3, // 0: entity.PlayerSimpleProfile.favorite_member_card:type_name -> entity.DeckMemberCardDetail
	4, // 1: entity.PlayerSimpleProfile.profile_card:type_name -> entity.SimpleProfileCard
	3, // 2: entity.PlayerDetailProfile.favorite_member_card:type_name -> entity.DeckMemberCardDetail
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_entity_player_profile_proto_init() }
func file_entity_player_profile_proto_init() {
	if File_entity_player_profile_proto != nil {
		return
	}
	file_entity_deck_proto_init()
	file_entity_profilecard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_player_profile_proto_rawDesc), len(file_entity_player_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_player_profile_proto_goTypes,
		DependencyIndexes: file_entity_player_profile_proto_depIdxs,
		MessageInfos:      file_entity_player_profile_proto_msgTypes,
	}.Build()
	File_entity_player_profile_proto = out.File
	file_entity_player_profile_proto_goTypes = nil
	file_entity_player_profile_proto_depIdxs = nil
}
