// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/present.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnreceiveReason int32

const (
	UnreceiveReason_UNRECEIVE_REASON_UNSPECIFIED   UnreceiveReason = 0
	UnreceiveReason_UNRECEIVE_REASON_LIMIT_REACHED UnreceiveReason = 1
	UnreceiveReason_UNRECEIVE_REASON_EXPIRED       UnreceiveReason = 2
)

// Enum value maps for UnreceiveReason.
var (
	UnreceiveReason_name = map[int32]string{
		0: "UNRECEIVE_REASON_UNSPECIFIED",
		1: "UNRECEIVE_REASON_LIMIT_REACHED",
		2: "UNRECEIVE_REASON_EXPIRED",
	}
	UnreceiveReason_value = map[string]int32{
		"UNRECEIVE_REASON_UNSPECIFIED":   0,
		"UNRECEIVE_REASON_LIMIT_REACHED": 1,
		"UNRECEIVE_REASON_EXPIRED":       2,
	}
)

func (x UnreceiveReason) Enum() *UnreceiveReason {
	p := new(UnreceiveReason)
	*p = x
	return p
}

func (x UnreceiveReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnreceiveReason) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_present_proto_enumTypes[0].Descriptor()
}

func (UnreceiveReason) Type() protoreflect.EnumType {
	return &file_entity_present_proto_enumTypes[0]
}

func (x UnreceiveReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnreceiveReason.Descriptor instead.
func (UnreceiveReason) EnumDescriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{0}
}

type PresentResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  ResourceType           `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=entity.ResourceType" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceCount int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentResource) Reset() {
	*x = PresentResource{}
	mi := &file_entity_present_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentResource) ProtoMessage() {}

func (x *PresentResource) ProtoReflect() protoreflect.Message {
	mi := &file_entity_present_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentResource.ProtoReflect.Descriptor instead.
func (*PresentResource) Descriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{0}
}

func (x *PresentResource) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *PresentResource) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *PresentResource) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type Present struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PresentId       uint64                 `protobuf:"varint,1,opt,name=present_id,json=presentId,proto3" json:"present_id,omitempty"`
	PostAt          int64                  `protobuf:"varint,2,opt,name=post_at,json=postAt,proto3" json:"post_at,omitempty"`
	ExpireAt        *int64                 `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3,oneof" json:"expire_at,omitempty"`
	PresentResource *PresentResource       `protobuf:"bytes,4,opt,name=present_resource,json=presentResource,proto3" json:"present_resource,omitempty"`
	Title           *PresentTitle          `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Present) Reset() {
	*x = Present{}
	mi := &file_entity_present_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Present) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Present) ProtoMessage() {}

func (x *Present) ProtoReflect() protoreflect.Message {
	mi := &file_entity_present_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Present.ProtoReflect.Descriptor instead.
func (*Present) Descriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{1}
}

func (x *Present) GetPresentId() uint64 {
	if x != nil {
		return x.PresentId
	}
	return 0
}

func (x *Present) GetPostAt() int64 {
	if x != nil {
		return x.PostAt
	}
	return 0
}

func (x *Present) GetExpireAt() int64 {
	if x != nil && x.ExpireAt != nil {
		return *x.ExpireAt
	}
	return 0
}

func (x *Present) GetPresentResource() *PresentResource {
	if x != nil {
		return x.PresentResource
	}
	return nil
}

func (x *Present) GetTitle() *PresentTitle {
	if x != nil {
		return x.Title
	}
	return nil
}

type PresentTitle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PresentTypeId  int64                  `protobuf:"varint,1,opt,name=present_type_id,json=presentTypeId,proto3" json:"present_type_id,omitempty"`
	PresentParam_1 string                 `protobuf:"bytes,2,opt,name=present_param_1,json=presentParam1,proto3" json:"present_param_1,omitempty"`
	PresentParam_2 string                 `protobuf:"bytes,3,opt,name=present_param_2,json=presentParam2,proto3" json:"present_param_2,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresentTitle) Reset() {
	*x = PresentTitle{}
	mi := &file_entity_present_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentTitle) ProtoMessage() {}

func (x *PresentTitle) ProtoReflect() protoreflect.Message {
	mi := &file_entity_present_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentTitle.ProtoReflect.Descriptor instead.
func (*PresentTitle) Descriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{2}
}

func (x *PresentTitle) GetPresentTypeId() int64 {
	if x != nil {
		return x.PresentTypeId
	}
	return 0
}

func (x *PresentTitle) GetPresentParam_1() string {
	if x != nil {
		return x.PresentParam_1
	}
	return ""
}

func (x *PresentTitle) GetPresentParam_2() string {
	if x != nil {
		return x.PresentParam_2
	}
	return ""
}

type PresentUnreceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresentId     uint64                 `protobuf:"varint,1,opt,name=present_id,json=presentId,proto3" json:"present_id,omitempty"`
	Reason        UnreceiveReason        `protobuf:"varint,2,opt,name=reason,proto3,enum=entity.UnreceiveReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentUnreceived) Reset() {
	*x = PresentUnreceived{}
	mi := &file_entity_present_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentUnreceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentUnreceived) ProtoMessage() {}

func (x *PresentUnreceived) ProtoReflect() protoreflect.Message {
	mi := &file_entity_present_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentUnreceived.ProtoReflect.Descriptor instead.
func (*PresentUnreceived) Descriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{3}
}

func (x *PresentUnreceived) GetPresentId() uint64 {
	if x != nil {
		return x.PresentId
	}
	return 0
}

func (x *PresentUnreceived) GetReason() UnreceiveReason {
	if x != nil {
		return x.Reason
	}
	return UnreceiveReason_UNRECEIVE_REASON_UNSPECIFIED
}

type PresentHistory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PresentId         uint64                 `protobuf:"varint,1,opt,name=present_id,json=presentId,proto3" json:"present_id,omitempty"`
	PostAt            int64                  `protobuf:"varint,2,opt,name=post_at,json=postAt,proto3" json:"post_at,omitempty"`
	GotAt             int64                  `protobuf:"varint,3,opt,name=got_at,json=gotAt,proto3" json:"got_at,omitempty"`
	PresentResource   *PresentResource       `protobuf:"bytes,4,opt,name=present_resource,json=presentResource,proto3" json:"present_resource,omitempty"`
	Title             *PresentTitle          `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ConvertedResource *PresentResource       `protobuf:"bytes,6,opt,name=converted_resource,json=convertedResource,proto3" json:"converted_resource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PresentHistory) Reset() {
	*x = PresentHistory{}
	mi := &file_entity_present_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentHistory) ProtoMessage() {}

func (x *PresentHistory) ProtoReflect() protoreflect.Message {
	mi := &file_entity_present_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentHistory.ProtoReflect.Descriptor instead.
func (*PresentHistory) Descriptor() ([]byte, []int) {
	return file_entity_present_proto_rawDescGZIP(), []int{4}
}

func (x *PresentHistory) GetPresentId() uint64 {
	if x != nil {
		return x.PresentId
	}
	return 0
}

func (x *PresentHistory) GetPostAt() int64 {
	if x != nil {
		return x.PostAt
	}
	return 0
}

func (x *PresentHistory) GetGotAt() int64 {
	if x != nil {
		return x.GotAt
	}
	return 0
}

func (x *PresentHistory) GetPresentResource() *PresentResource {
	if x != nil {
		return x.PresentResource
	}
	return nil
}

func (x *PresentHistory) GetTitle() *PresentTitle {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *PresentHistory) GetConvertedResource() *PresentResource {
	if x != nil {
		return x.ConvertedResource
	}
	return nil
}

var File_entity_present_proto protoreflect.FileDescriptor

const file_entity_present_proto_rawDesc = "" +
	"\n" +
	"\x14entity/present.proto\x12\x06entity\x1a\x15entity/resource.proto\"\x94\x01\n" +
	"\x0fPresentResource\x129\n" +
	"\rresource_type\x18\x01 \x01(\x0e2\x14.entity.ResourceTypeR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\x03R\n" +
	"resourceId\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCount\"\xe1\x01\n" +
	"\aPresent\x12\x1d\n" +
	"\n" +
	"present_id\x18\x01 \x01(\x04R\tpresentId\x12\x17\n" +
	"\apost_at\x18\x02 \x01(\x03R\x06postAt\x12 \n" +
	"\texpire_at\x18\x03 \x01(\x03H\x00R\bexpireAt\x88\x01\x01\x12B\n" +
	"\x10present_resource\x18\x04 \x01(\v2\x17.entity.PresentResourceR\x0fpresentResource\x12*\n" +
	"\x05title\x18\x05 \x01(\v2\x14.entity.PresentTitleR\x05titleB\f\n" +
	"\n" +
	"_expire_at\"\x86\x01\n" +
	"\fPresentTitle\x12&\n" +
	"\x0fpresent_type_id\x18\x01 \x01(\x03R\rpresentTypeId\x12&\n" +
	"\x0fpresent_param_1\x18\x02 \x01(\tR\rpresentParam1\x12&\n" +
	"\x0fpresent_param_2\x18\x03 \x01(\tR\rpresentParam2\"c\n" +
	"\x11PresentUnreceived\x12\x1d\n" +
	"\n" +
	"present_id\x18\x01 \x01(\x04R\tpresentId\x12/\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x17.entity.UnreceiveReasonR\x06reason\"\x97\x02\n" +
	"\x0ePresentHistory\x12\x1d\n" +
	"\n" +
	"present_id\x18\x01 \x01(\x04R\tpresentId\x12\x17\n" +
	"\apost_at\x18\x02 \x01(\x03R\x06postAt\x12\x15\n" +
	"\x06got_at\x18\x03 \x01(\x03R\x05gotAt\x12B\n" +
	"\x10present_resource\x18\x04 \x01(\v2\x17.entity.PresentResourceR\x0fpresentResource\x12*\n" +
	"\x05title\x18\x05 \x01(\v2\x14.entity.PresentTitleR\x05title\x12F\n" +
	"\x12converted_resource\x18\x06 \x01(\v2\x17.entity.PresentResourceR\x11convertedResource*u\n" +
	"\x0fUnreceiveReason\x12 \n" +
	"\x1cUNRECEIVE_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eUNRECEIVE_REASON_LIMIT_REACHED\x10\x01\x12\x1c\n" +
	"\x18UNRECEIVE_REASON_EXPIRED\x10\x02B\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_present_proto_rawDescOnce sync.Once
	file_entity_present_proto_rawDescData []byte
)

func file_entity_present_proto_rawDescGZIP() []byte {
	file_entity_present_proto_rawDescOnce.Do(func() {
		file_entity_present_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_present_proto_rawDesc), len(file_entity_present_proto_rawDesc)))
	})
	return file_entity_present_proto_rawDescData
}

var file_entity_present_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entity_present_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_entity_present_proto_goTypes = []any{
	(UnreceiveReason)(0),      // 0: entity.UnreceiveReason
	(*PresentResource)(nil),   // 1: entity.PresentResource
	(*Present)(nil),           // 2: entity.Present
	(*PresentTitle)(nil),      // 3: entity.PresentTitle
	(*PresentUnreceived)(nil), // 4: entity.PresentUnreceived
	(*PresentHistory)(nil),    // 5: entity.PresentHistory
	(ResourceType)(0),         // 6: entity.ResourceType
}
var file_entity_present_proto_depIdxs = []int32{
	6, // 0: entity.PresentResource.resource_type:type_name -> entity.ResourceType
	1, // 1: entity.Present.present_resource:type_name -> entity.PresentResource
	3, // 2: entity.Present.title:type_name -> entity.PresentTitle
	0, // 3: entity.PresentUnreceived.reason:type_name -> entity.UnreceiveReason
	1, // 4: entity.PresentHistory.present_resource:type_name -> entity.PresentResource
	3, // 5: entity.PresentHistory.title:type_name -> entity.PresentTitle
	1, // 6: entity.PresentHistory.converted_resource:type_name -> entity.PresentResource
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_entity_present_proto_init() }
func file_entity_present_proto_init() {
	if File_entity_present_proto != nil {
		return
	}
	file_entity_resource_proto_init()
	file_entity_present_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_present_proto_rawDesc), len(file_entity_present_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_present_proto_goTypes,
		DependencyIndexes: file_entity_present_proto_depIdxs,
		EnumInfos:         file_entity_present_proto_enumTypes,
		MessageInfos:      file_entity_present_proto_msgTypes,
	}.Build()
	File_entity_present_proto = out.File
	file_entity_present_proto_goTypes = nil
	file_entity_present_proto_depIdxs = nil
}
