// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/reward.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewardResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  ResourceType           `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=entity.ResourceType" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceCount int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardResource) Reset() {
	*x = RewardResource{}
	mi := &file_entity_reward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardResource) ProtoMessage() {}

func (x *RewardResource) ProtoReflect() protoreflect.Message {
	mi := &file_entity_reward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardResource.ProtoReflect.Descriptor instead.
func (*RewardResource) Descriptor() ([]byte, []int) {
	return file_entity_reward_proto_rawDescGZIP(), []int{0}
}

func (x *RewardResource) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *RewardResource) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *RewardResource) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

var File_entity_reward_proto protoreflect.FileDescriptor

const file_entity_reward_proto_rawDesc = "" +
	"\n" +
	"\x13entity/reward.proto\x12\x06entity\x1a\x15entity/resource.proto\"\x93\x01\n" +
	"\x0eRewardResource\x129\n" +
	"\rresource_type\x18\x01 \x01(\x0e2\x14.entity.ResourceTypeR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\x03R\n" +
	"resourceId\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCountB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_reward_proto_rawDescOnce sync.Once
	file_entity_reward_proto_rawDescData []byte
)

func file_entity_reward_proto_rawDescGZIP() []byte {
	file_entity_reward_proto_rawDescOnce.Do(func() {
		file_entity_reward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_reward_proto_rawDesc), len(file_entity_reward_proto_rawDesc)))
	})
	return file_entity_reward_proto_rawDescData
}

var file_entity_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_reward_proto_goTypes = []any{
	(*RewardResource)(nil), // 0: entity.RewardResource
	(ResourceType)(0),      // 1: entity.ResourceType
}
var file_entity_reward_proto_depIdxs = []int32{
	1, // 0: entity.RewardResource.resource_type:type_name -> entity.ResourceType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entity_reward_proto_init() }
func file_entity_reward_proto_init() {
	if File_entity_reward_proto != nil {
		return
	}
	file_entity_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_reward_proto_rawDesc), len(file_entity_reward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_reward_proto_goTypes,
		DependencyIndexes: file_entity_reward_proto_depIdxs,
		MessageInfos:      file_entity_reward_proto_msgTypes,
	}.Build()
	File_entity_reward_proto = out.File
	file_entity_reward_proto_goTypes = nil
	file_entity_reward_proto_depIdxs = nil
}
