// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/season_pass.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeasonPass struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SeasonPassId             int64                  `protobuf:"varint,1,opt,name=season_pass_id,json=seasonPassId,proto3" json:"season_pass_id,omitempty"`
	Point                    int32                  `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"`
	IsPremium                bool                   `protobuf:"varint,3,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	LastReceivedLevel        int32                  `protobuf:"varint,4,opt,name=last_received_level,json=lastReceivedLevel,proto3" json:"last_received_level,omitempty"`
	PremiumLastReceivedLevel int32                  `protobuf:"varint,5,opt,name=premium_last_received_level,json=premiumLastReceivedLevel,proto3" json:"premium_last_received_level,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SeasonPass) Reset() {
	*x = SeasonPass{}
	mi := &file_entity_season_pass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonPass) ProtoMessage() {}

func (x *SeasonPass) ProtoReflect() protoreflect.Message {
	mi := &file_entity_season_pass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonPass.ProtoReflect.Descriptor instead.
func (*SeasonPass) Descriptor() ([]byte, []int) {
	return file_entity_season_pass_proto_rawDescGZIP(), []int{0}
}

func (x *SeasonPass) GetSeasonPassId() int64 {
	if x != nil {
		return x.SeasonPassId
	}
	return 0
}

func (x *SeasonPass) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *SeasonPass) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *SeasonPass) GetLastReceivedLevel() int32 {
	if x != nil {
		return x.LastReceivedLevel
	}
	return 0
}

func (x *SeasonPass) GetPremiumLastReceivedLevel() int32 {
	if x != nil {
		return x.PremiumLastReceivedLevel
	}
	return 0
}

type SeasonPassMission struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SeasonPassId        int64                  `protobuf:"varint,1,opt,name=season_pass_id,json=seasonPassId,proto3" json:"season_pass_id,omitempty"`
	SeasonPassMissionId int64                  `protobuf:"varint,2,opt,name=season_pass_mission_id,json=seasonPassMissionId,proto3" json:"season_pass_mission_id,omitempty"`
	StartCount          int64                  `protobuf:"varint,3,opt,name=start_count,json=startCount,proto3" json:"start_count,omitempty"`
	IsCompleted         bool                   `protobuf:"varint,4,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsReceived          bool                   `protobuf:"varint,5,opt,name=is_received,json=isReceived,proto3" json:"is_received,omitempty"`
	StartAt             int64                  `protobuf:"varint,6,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SeasonPassMission) Reset() {
	*x = SeasonPassMission{}
	mi := &file_entity_season_pass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonPassMission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonPassMission) ProtoMessage() {}

func (x *SeasonPassMission) ProtoReflect() protoreflect.Message {
	mi := &file_entity_season_pass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonPassMission.ProtoReflect.Descriptor instead.
func (*SeasonPassMission) Descriptor() ([]byte, []int) {
	return file_entity_season_pass_proto_rawDescGZIP(), []int{1}
}

func (x *SeasonPassMission) GetSeasonPassId() int64 {
	if x != nil {
		return x.SeasonPassId
	}
	return 0
}

func (x *SeasonPassMission) GetSeasonPassMissionId() int64 {
	if x != nil {
		return x.SeasonPassMissionId
	}
	return 0
}

func (x *SeasonPassMission) GetStartCount() int64 {
	if x != nil {
		return x.StartCount
	}
	return 0
}

func (x *SeasonPassMission) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *SeasonPassMission) GetIsReceived() bool {
	if x != nil {
		return x.IsReceived
	}
	return false
}

func (x *SeasonPassMission) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

type SeasonPassDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeasonPass       *SeasonPass            `protobuf:"bytes,1,opt,name=season_pass,json=seasonPass,proto3" json:"season_pass,omitempty"`
	Missions         []*SeasonPassMission   `protobuf:"bytes,2,rep,name=missions,proto3" json:"missions,omitempty"`
	AutoGrantedPoint int32                  `protobuf:"varint,3,opt,name=auto_granted_point,json=autoGrantedPoint,proto3" json:"auto_granted_point,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeasonPassDetail) Reset() {
	*x = SeasonPassDetail{}
	mi := &file_entity_season_pass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonPassDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonPassDetail) ProtoMessage() {}

func (x *SeasonPassDetail) ProtoReflect() protoreflect.Message {
	mi := &file_entity_season_pass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonPassDetail.ProtoReflect.Descriptor instead.
func (*SeasonPassDetail) Descriptor() ([]byte, []int) {
	return file_entity_season_pass_proto_rawDescGZIP(), []int{2}
}

func (x *SeasonPassDetail) GetSeasonPass() *SeasonPass {
	if x != nil {
		return x.SeasonPass
	}
	return nil
}

func (x *SeasonPassDetail) GetMissions() []*SeasonPassMission {
	if x != nil {
		return x.Missions
	}
	return nil
}

func (x *SeasonPassDetail) GetAutoGrantedPoint() int32 {
	if x != nil {
		return x.AutoGrantedPoint
	}
	return 0
}

var File_entity_season_pass_proto protoreflect.FileDescriptor

const file_entity_season_pass_proto_rawDesc = "" +
	"\n" +
	"\x18entity/season_pass.proto\x12\x06entity\"\xd6\x01\n" +
	"\n" +
	"SeasonPass\x12$\n" +
	"\x0eseason_pass_id\x18\x01 \x01(\x03R\fseasonPassId\x12\x14\n" +
	"\x05point\x18\x02 \x01(\x05R\x05point\x12\x1d\n" +
	"\n" +
	"is_premium\x18\x03 \x01(\bR\tisPremium\x12.\n" +
	"\x13last_received_level\x18\x04 \x01(\x05R\x11lastReceivedLevel\x12=\n" +
	"\x1bpremium_last_received_level\x18\x05 \x01(\x05R\x18premiumLastReceivedLevel\"\xee\x01\n" +
	"\x11SeasonPassMission\x12$\n" +
	"\x0eseason_pass_id\x18\x01 \x01(\x03R\fseasonPassId\x123\n" +
	"\x16season_pass_mission_id\x18\x02 \x01(\x03R\x13seasonPassMissionId\x12\x1f\n" +
	"\vstart_count\x18\x03 \x01(\x03R\n" +
	"startCount\x12!\n" +
	"\fis_completed\x18\x04 \x01(\bR\visCompleted\x12\x1f\n" +
	"\vis_received\x18\x05 \x01(\bR\n" +
	"isReceived\x12\x19\n" +
	"\bstart_at\x18\x06 \x01(\x03R\astartAt\"\xac\x01\n" +
	"\x10SeasonPassDetail\x123\n" +
	"\vseason_pass\x18\x01 \x01(\v2\x12.entity.SeasonPassR\n" +
	"seasonPass\x125\n" +
	"\bmissions\x18\x02 \x03(\v2\x19.entity.SeasonPassMissionR\bmissions\x12,\n" +
	"\x12auto_granted_point\x18\x03 \x01(\x05R\x10autoGrantedPointB\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_season_pass_proto_rawDescOnce sync.Once
	file_entity_season_pass_proto_rawDescData []byte
)

func file_entity_season_pass_proto_rawDescGZIP() []byte {
	file_entity_season_pass_proto_rawDescOnce.Do(func() {
		file_entity_season_pass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_season_pass_proto_rawDesc), len(file_entity_season_pass_proto_rawDesc)))
	})
	return file_entity_season_pass_proto_rawDescData
}

var file_entity_season_pass_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_entity_season_pass_proto_goTypes = []any{
	(*SeasonPass)(nil),        // 0: entity.SeasonPass
	(*SeasonPassMission)(nil), // 1: entity.SeasonPassMission
	(*SeasonPassDetail)(nil),  // 2: entity.SeasonPassDetail
}
var file_entity_season_pass_proto_depIdxs = []int32{
	0, // 0: entity.SeasonPassDetail.season_pass:type_name -> entity.SeasonPass
	1, // 1: entity.SeasonPassDetail.missions:type_name -> entity.SeasonPassMission
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entity_season_pass_proto_init() }
func file_entity_season_pass_proto_init() {
	if File_entity_season_pass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_season_pass_proto_rawDesc), len(file_entity_season_pass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_season_pass_proto_goTypes,
		DependencyIndexes: file_entity_season_pass_proto_depIdxs,
		MessageInfos:      file_entity_season_pass_proto_msgTypes,
	}.Build()
	File_entity_season_pass_proto = out.File
	file_entity_season_pass_proto_goTypes = nil
	file_entity_season_pass_proto_depIdxs = nil
}
