// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: entity/sendchat.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNSPECIFIED ChatType = 0
	ChatType_ALL                   ChatType = 1
	ChatType_CIRCLE                ChatType = 2
	ChatType_FRIEND                ChatType = 3
	ChatType_SYSTEM                ChatType = 4
	ChatType_IMPORTANT             ChatType = 5
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNSPECIFIED",
		1: "ALL",
		2: "CIRCLE",
		3: "FRIEND",
		4: "SYSTEM",
		5: "IMPORTANT",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNSPECIFIED": 0,
		"ALL":                   1,
		"CIRCLE":                2,
		"FRIEND":                3,
		"SYSTEM":                4,
		"IMPORTANT":             5,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_sendchat_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_entity_sendchat_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_entity_sendchat_proto_rawDescGZIP(), []int{0}
}

type SendChat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatType        ChatType               `protobuf:"varint,1,opt,name=chat_type,json=chatType,proto3,enum=entity.ChatType" json:"chat_type,omitempty"`
	FriendProfileId *int64                 `protobuf:"varint,2,opt,name=friend_profile_id,json=friendProfileId,proto3,oneof" json:"friend_profile_id,omitempty"`
	Text            *string                `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
	StampId         *uint32                `protobuf:"varint,4,opt,name=stamp_id,json=stampId,proto3,oneof" json:"stamp_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendChat) Reset() {
	*x = SendChat{}
	mi := &file_entity_sendchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChat) ProtoMessage() {}

func (x *SendChat) ProtoReflect() protoreflect.Message {
	mi := &file_entity_sendchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChat.ProtoReflect.Descriptor instead.
func (*SendChat) Descriptor() ([]byte, []int) {
	return file_entity_sendchat_proto_rawDescGZIP(), []int{0}
}

func (x *SendChat) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *SendChat) GetFriendProfileId() int64 {
	if x != nil && x.FriendProfileId != nil {
		return *x.FriendProfileId
	}
	return 0
}

func (x *SendChat) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *SendChat) GetStampId() uint32 {
	if x != nil && x.StampId != nil {
		return *x.StampId
	}
	return 0
}

var File_entity_sendchat_proto protoreflect.FileDescriptor

const file_entity_sendchat_proto_rawDesc = "" +
	"\n" +
	"\x15entity/sendchat.proto\x12\x06entity\"\xcf\x01\n" +
	"\bSendChat\x12-\n" +
	"\tchat_type\x18\x01 \x01(\x0e2\x10.entity.ChatTypeR\bchatType\x12/\n" +
	"\x11friend_profile_id\x18\x02 \x01(\x03H\x00R\x0ffriendProfileId\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tH\x01R\x04text\x88\x01\x01\x12\x1e\n" +
	"\bstamp_id\x18\x04 \x01(\rH\x02R\astampId\x88\x01\x01B\x14\n" +
	"\x12_friend_profile_idB\a\n" +
	"\x05_textB\v\n" +
	"\t_stamp_id*a\n" +
	"\bChatType\x12\x19\n" +
	"\x15CHAT_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\n" +
	"\n" +
	"\x06CIRCLE\x10\x02\x12\n" +
	"\n" +
	"\x06FRIEND\x10\x03\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x04\x12\r\n" +
	"\tIMPORTANT\x10\x05B\x16\xaa\x02\x13App.Protobuf.Entityb\x06proto3"

var (
	file_entity_sendchat_proto_rawDescOnce sync.Once
	file_entity_sendchat_proto_rawDescData []byte
)

func file_entity_sendchat_proto_rawDescGZIP() []byte {
	file_entity_sendchat_proto_rawDescOnce.Do(func() {
		file_entity_sendchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_sendchat_proto_rawDesc), len(file_entity_sendchat_proto_rawDesc)))
	})
	return file_entity_sendchat_proto_rawDescData
}

var file_entity_sendchat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entity_sendchat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_sendchat_proto_goTypes = []any{
	(ChatType)(0),    // 0: entity.ChatType
	(*SendChat)(nil), // 1: entity.SendChat
}
var file_entity_sendchat_proto_depIdxs = []int32{
	0, // 0: entity.SendChat.chat_type:type_name -> entity.ChatType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entity_sendchat_proto_init() }
func file_entity_sendchat_proto_init() {
	if File_entity_sendchat_proto != nil {
		return
	}
	file_entity_sendchat_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_sendchat_proto_rawDesc), len(file_entity_sendchat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_sendchat_proto_goTypes,
		DependencyIndexes: file_entity_sendchat_proto_depIdxs,
		EnumInfos:         file_entity_sendchat_proto_enumTypes,
		MessageInfos:      file_entity_sendchat_proto_msgTypes,
	}.Build()
	File_entity_sendchat_proto = out.File
	file_entity_sendchat_proto_goTypes = nil
	file_entity_sendchat_proto_depIdxs = nil
}
