// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/external_payments/external_payments_service.proto

package external_payments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "private-notes/game/proto/entity/method_options"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentDenyReason int32

const (
	PaymentDenyReason_DENY_REASON_NONE             PaymentDenyReason = 0
	PaymentDenyReason_DENY_REASON_LIMIT_REACHED    PaymentDenyReason = 1
	PaymentDenyReason_DENY_REASON_BY_OTHER_PAYMENT PaymentDenyReason = 2
	PaymentDenyReason_DENY_REASON_TIME_LIMIT       PaymentDenyReason = 3
)

// Enum value maps for PaymentDenyReason.
var (
	PaymentDenyReason_name = map[int32]string{
		0: "DENY_REASON_NONE",
		1: "DENY_REASON_LIMIT_REACHED",
		2: "DENY_REASON_BY_OTHER_PAYMENT",
		3: "DENY_REASON_TIME_LIMIT",
	}
	PaymentDenyReason_value = map[string]int32{
		"DENY_REASON_NONE":             0,
		"DENY_REASON_LIMIT_REACHED":    1,
		"DENY_REASON_BY_OTHER_PAYMENT": 2,
		"DENY_REASON_TIME_LIMIT":       3,
	}
)

func (x PaymentDenyReason) Enum() *PaymentDenyReason {
	p := new(PaymentDenyReason)
	*p = x
	return p
}

func (x PaymentDenyReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentDenyReason) Descriptor() protoreflect.EnumDescriptor {
	return file_app_external_payments_external_payments_service_proto_enumTypes[0].Descriptor()
}

func (PaymentDenyReason) Type() protoreflect.EnumType {
	return &file_app_external_payments_external_payments_service_proto_enumTypes[0]
}

func (x PaymentDenyReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentDenyReason.Descriptor instead.
func (PaymentDenyReason) EnumDescriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{0}
}

type ShopResetType int32

const (
	ShopResetType_SHOP_RESET_TYPE_NONE    ShopResetType = 0
	ShopResetType_SHOP_RESET_TYPE_TOTAL   ShopResetType = 1
	ShopResetType_SHOP_RESET_TYPE_DAILY   ShopResetType = 2
	ShopResetType_SHOP_RESET_TYPE_WEEKLY  ShopResetType = 3
	ShopResetType_SHOP_RESET_TYPE_MONTHLY ShopResetType = 4
)

// Enum value maps for ShopResetType.
var (
	ShopResetType_name = map[int32]string{
		0: "SHOP_RESET_TYPE_NONE",
		1: "SHOP_RESET_TYPE_TOTAL",
		2: "SHOP_RESET_TYPE_DAILY",
		3: "SHOP_RESET_TYPE_WEEKLY",
		4: "SHOP_RESET_TYPE_MONTHLY",
	}
	ShopResetType_value = map[string]int32{
		"SHOP_RESET_TYPE_NONE":    0,
		"SHOP_RESET_TYPE_TOTAL":   1,
		"SHOP_RESET_TYPE_DAILY":   2,
		"SHOP_RESET_TYPE_WEEKLY":  3,
		"SHOP_RESET_TYPE_MONTHLY": 4,
	}
)

func (x ShopResetType) Enum() *ShopResetType {
	p := new(ShopResetType)
	*p = x
	return p
}

func (x ShopResetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopResetType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_external_payments_external_payments_service_proto_enumTypes[1].Descriptor()
}

func (ShopResetType) Type() protoreflect.EnumType {
	return &file_app_external_payments_external_payments_service_proto_enumTypes[1]
}

func (x ShopResetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopResetType.Descriptor instead.
func (ShopResetType) EnumDescriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{1}
}

type CheckMaintenanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMaintenanceRequest) Reset() {
	*x = CheckMaintenanceRequest{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMaintenanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMaintenanceRequest) ProtoMessage() {}

func (x *CheckMaintenanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMaintenanceRequest.ProtoReflect.Descriptor instead.
func (*CheckMaintenanceRequest) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{0}
}

type CheckMaintenanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMaint       bool                   `protobuf:"varint,1,opt,name=is_maint,json=isMaint,proto3" json:"is_maint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMaintenanceResponse) Reset() {
	*x = CheckMaintenanceResponse{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMaintenanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMaintenanceResponse) ProtoMessage() {}

func (x *CheckMaintenanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMaintenanceResponse.ProtoReflect.Descriptor instead.
func (*CheckMaintenanceResponse) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckMaintenanceResponse) GetIsMaint() bool {
	if x != nil {
		return x.IsMaint
	}
	return false
}

type ItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopItemId    int64                  `protobuf:"varint,1,opt,name=shop_item_id,json=shopItemId,proto3" json:"shop_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatusRequest) Reset() {
	*x = ItemStatusRequest{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatusRequest) ProtoMessage() {}

func (x *ItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatusRequest.ProtoReflect.Descriptor instead.
func (*ItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{2}
}

func (x *ItemStatusRequest) GetShopItemId() int64 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

type ItemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PaymentDenyReason      `protobuf:"varint,1,opt,name=status,proto3,enum=app.external_payments.PaymentDenyReason" json:"status,omitempty"`
	RemainCount   int64                  `protobuf:"varint,2,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`
	ResetType     ShopResetType          `protobuf:"varint,3,opt,name=reset_type,json=resetType,proto3,enum=app.external_payments.ShopResetType" json:"reset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatusResponse) Reset() {
	*x = ItemStatusResponse{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatusResponse) ProtoMessage() {}

func (x *ItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatusResponse.ProtoReflect.Descriptor instead.
func (*ItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{3}
}

func (x *ItemStatusResponse) GetStatus() PaymentDenyReason {
	if x != nil {
		return x.Status
	}
	return PaymentDenyReason_DENY_REASON_NONE
}

func (x *ItemStatusResponse) GetRemainCount() int64 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *ItemStatusResponse) GetResetType() ShopResetType {
	if x != nil {
		return x.ResetType
	}
	return ShopResetType_SHOP_RESET_TYPE_NONE
}

type ExecutePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopItemId    int64                  `protobuf:"varint,1,opt,name=shop_item_id,json=shopItemId,proto3" json:"shop_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePaymentRequest) Reset() {
	*x = ExecutePaymentRequest{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePaymentRequest) ProtoMessage() {}

func (x *ExecutePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePaymentRequest.ProtoReflect.Descriptor instead.
func (*ExecutePaymentRequest) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutePaymentRequest) GetShopItemId() int64 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

type ExecutePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PaymentDenyReason      `protobuf:"varint,1,opt,name=status,proto3,enum=app.external_payments.PaymentDenyReason" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePaymentResponse) Reset() {
	*x = ExecutePaymentResponse{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePaymentResponse) ProtoMessage() {}

func (x *ExecutePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePaymentResponse.ProtoReflect.Descriptor instead.
func (*ExecutePaymentResponse) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutePaymentResponse) GetStatus() PaymentDenyReason {
	if x != nil {
		return x.Status
	}
	return PaymentDenyReason_DENY_REASON_NONE
}

type GetProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListRequest) Reset() {
	*x = GetProductListRequest{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListRequest) ProtoMessage() {}

func (x *GetProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListRequest.ProtoReflect.Descriptor instead.
func (*GetProductListRequest) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{6}
}

type ProductListItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ShopItemId         int64                  `protobuf:"varint,1,opt,name=shop_item_id,json=shopItemId,proto3" json:"shop_item_id,omitempty"`
	Status             PaymentDenyReason      `protobuf:"varint,2,opt,name=status,proto3,enum=app.external_payments.PaymentDenyReason" json:"status,omitempty"`
	RemainCount        int32                  `protobuf:"varint,3,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`
	RequiredPlayerRank int32                  `protobuf:"varint,4,opt,name=required_player_rank,json=requiredPlayerRank,proto3" json:"required_player_rank,omitempty"`
	RequiredVipRank    int32                  `protobuf:"varint,5,opt,name=required_vip_rank,json=requiredVipRank,proto3" json:"required_vip_rank,omitempty"`
	ItemName           string                 `protobuf:"bytes,6,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Price              int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	DescriptionText    string                 `protobuf:"bytes,8,opt,name=description_text,json=descriptionText,proto3" json:"description_text,omitempty"`
	Priority           int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	StartAt            string                 `protobuf:"bytes,10,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt              string                 `protobuf:"bytes,11,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	LimitConsumeCount  int32                  `protobuf:"varint,12,opt,name=limit_consume_count,json=limitConsumeCount,proto3" json:"limit_consume_count,omitempty"`
	ResetType          ShopResetType          `protobuf:"varint,13,opt,name=reset_type,json=resetType,proto3,enum=app.external_payments.ShopResetType" json:"reset_type,omitempty"`
	Banner             string                 `protobuf:"bytes,14,opt,name=banner,proto3" json:"banner,omitempty"`
	NotesText          string                 `protobuf:"bytes,15,opt,name=notes_text,json=notesText,proto3" json:"notes_text,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductListItem) Reset() {
	*x = ProductListItem{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListItem) ProtoMessage() {}

func (x *ProductListItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListItem.ProtoReflect.Descriptor instead.
func (*ProductListItem) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProductListItem) GetShopItemId() int64 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

func (x *ProductListItem) GetStatus() PaymentDenyReason {
	if x != nil {
		return x.Status
	}
	return PaymentDenyReason_DENY_REASON_NONE
}

func (x *ProductListItem) GetRemainCount() int32 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *ProductListItem) GetRequiredPlayerRank() int32 {
	if x != nil {
		return x.RequiredPlayerRank
	}
	return 0
}

func (x *ProductListItem) GetRequiredVipRank() int32 {
	if x != nil {
		return x.RequiredVipRank
	}
	return 0
}

func (x *ProductListItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ProductListItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductListItem) GetDescriptionText() string {
	if x != nil {
		return x.DescriptionText
	}
	return ""
}

func (x *ProductListItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProductListItem) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *ProductListItem) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *ProductListItem) GetLimitConsumeCount() int32 {
	if x != nil {
		return x.LimitConsumeCount
	}
	return 0
}

func (x *ProductListItem) GetResetType() ShopResetType {
	if x != nil {
		return x.ResetType
	}
	return ShopResetType_SHOP_RESET_TYPE_NONE
}

func (x *ProductListItem) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *ProductListItem) GetNotesText() string {
	if x != nil {
		return x.NotesText
	}
	return ""
}

type GetProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductListItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListResponse) Reset() {
	*x = GetProductListResponse{}
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListResponse) ProtoMessage() {}

func (x *GetProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_external_payments_external_payments_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListResponse.ProtoReflect.Descriptor instead.
func (*GetProductListResponse) Descriptor() ([]byte, []int) {
	return file_app_external_payments_external_payments_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductListResponse) GetItems() []*ProductListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_app_external_payments_external_payments_service_proto protoreflect.FileDescriptor

const file_app_external_payments_external_payments_service_proto_rawDesc = "" +
	"\n" +
	"5app/external_payments/external_payments_service.proto\x12\x15app.external_payments\x1a*entity/method_options/method_options.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n" +
	"\x17CheckMaintenanceRequest\"5\n" +
	"\x18CheckMaintenanceResponse\x12\x19\n" +
	"\bis_maint\x18\x01 \x01(\bR\aisMaint\"5\n" +
	"\x11ItemStatusRequest\x12 \n" +
	"\fshop_item_id\x18\x01 \x01(\x03R\n" +
	"shopItemId\"\xbe\x01\n" +
	"\x12ItemStatusResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.app.external_payments.PaymentDenyReasonR\x06status\x12!\n" +
	"\fremain_count\x18\x02 \x01(\x03R\vremainCount\x12C\n" +
	"\n" +
	"reset_type\x18\x03 \x01(\x0e2$.app.external_payments.ShopResetTypeR\tresetType\"9\n" +
	"\x15ExecutePaymentRequest\x12 \n" +
	"\fshop_item_id\x18\x01 \x01(\x03R\n" +
	"shopItemId\"Z\n" +
	"\x16ExecutePaymentResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.app.external_payments.PaymentDenyReasonR\x06status\"\x17\n" +
	"\x15GetProductListRequest\"\xce\x04\n" +
	"\x0fProductListItem\x12 \n" +
	"\fshop_item_id\x18\x01 \x01(\x03R\n" +
	"shopItemId\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.app.external_payments.PaymentDenyReasonR\x06status\x12!\n" +
	"\fremain_count\x18\x03 \x01(\x05R\vremainCount\x120\n" +
	"\x14required_player_rank\x18\x04 \x01(\x05R\x12requiredPlayerRank\x12*\n" +
	"\x11required_vip_rank\x18\x05 \x01(\x05R\x0frequiredVipRank\x12\x1b\n" +
	"\titem_name\x18\x06 \x01(\tR\bitemName\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x12)\n" +
	"\x10description_text\x18\b \x01(\tR\x0fdescriptionText\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x19\n" +
	"\bstart_at\x18\n" +
	" \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\v \x01(\tR\x05endAt\x12.\n" +
	"\x13limit_consume_count\x18\f \x01(\x05R\x11limitConsumeCount\x12C\n" +
	"\n" +
	"reset_type\x18\r \x01(\x0e2$.app.external_payments.ShopResetTypeR\tresetType\x12\x16\n" +
	"\x06banner\x18\x0e \x01(\tR\x06banner\x12\x1d\n" +
	"\n" +
	"notes_text\x18\x0f \x01(\tR\tnotesText\"V\n" +
	"\x16GetProductListResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.app.external_payments.ProductListItemR\x05items*\x86\x01\n" +
	"\x11PaymentDenyReason\x12\x14\n" +
	"\x10DENY_REASON_NONE\x10\x00\x12\x1d\n" +
	"\x19DENY_REASON_LIMIT_REACHED\x10\x01\x12 \n" +
	"\x1cDENY_REASON_BY_OTHER_PAYMENT\x10\x02\x12\x1a\n" +
	"\x16DENY_REASON_TIME_LIMIT\x10\x03*\x98\x01\n" +
	"\rShopResetType\x12\x18\n" +
	"\x14SHOP_RESET_TYPE_NONE\x10\x00\x12\x19\n" +
	"\x15SHOP_RESET_TYPE_TOTAL\x10\x01\x12\x19\n" +
	"\x15SHOP_RESET_TYPE_DAILY\x10\x02\x12\x1a\n" +
	"\x16SHOP_RESET_TYPE_WEEKLY\x10\x03\x12\x1b\n" +
	"\x17SHOP_RESET_TYPE_MONTHLY\x10\x042\xb9\x03\n" +
	"\x17ExternalPaymentsService\x12?\n" +
	"\x03Nop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\b\x88\xb5\x18\x01\x98\xb5\x18\x01\x12k\n" +
	"\n" +
	"ItemStatus\x12(.app.external_payments.ItemStatusRequest\x1a).app.external_payments.ItemStatusResponse\"\b\x88\xb5\x18\x01\x98\xb5\x18\x01\x12w\n" +
	"\x0eExecutePayment\x12,.app.external_payments.ExecutePaymentRequest\x1a-.app.external_payments.ExecutePaymentResponse\"\b\x88\xb5\x18\x01\x98\xb5\x18\x01\x12w\n" +
	"\x0eGetProductList\x12,.app.external_payments.GetProductListRequest\x1a-.app.external_payments.GetProductListResponse\"\b\x88\xb5\x18\x01\x98\xb5\x18\x01B \xaa\x02\x1dApp.Protobuf.ExternalPaymentsb\x06proto3"

var (
	file_app_external_payments_external_payments_service_proto_rawDescOnce sync.Once
	file_app_external_payments_external_payments_service_proto_rawDescData []byte
)

func file_app_external_payments_external_payments_service_proto_rawDescGZIP() []byte {
	file_app_external_payments_external_payments_service_proto_rawDescOnce.Do(func() {
		file_app_external_payments_external_payments_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_external_payments_external_payments_service_proto_rawDesc), len(file_app_external_payments_external_payments_service_proto_rawDesc)))
	})
	return file_app_external_payments_external_payments_service_proto_rawDescData
}

var file_app_external_payments_external_payments_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_external_payments_external_payments_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_external_payments_external_payments_service_proto_goTypes = []any{
	(PaymentDenyReason)(0),           // 0: app.external_payments.PaymentDenyReason
	(ShopResetType)(0),               // 1: app.external_payments.ShopResetType
	(*CheckMaintenanceRequest)(nil),  // 2: app.external_payments.CheckMaintenanceRequest
	(*CheckMaintenanceResponse)(nil), // 3: app.external_payments.CheckMaintenanceResponse
	(*ItemStatusRequest)(nil),        // 4: app.external_payments.ItemStatusRequest
	(*ItemStatusResponse)(nil),       // 5: app.external_payments.ItemStatusResponse
	(*ExecutePaymentRequest)(nil),    // 6: app.external_payments.ExecutePaymentRequest
	(*ExecutePaymentResponse)(nil),   // 7: app.external_payments.ExecutePaymentResponse
	(*GetProductListRequest)(nil),    // 8: app.external_payments.GetProductListRequest
	(*ProductListItem)(nil),          // 9: app.external_payments.ProductListItem
	(*GetProductListResponse)(nil),   // 10: app.external_payments.GetProductListResponse
	(*emptypb.Empty)(nil),            // 11: google.protobuf.Empty
}
var file_app_external_payments_external_payments_service_proto_depIdxs = []int32{
	0,  // 0: app.external_payments.ItemStatusResponse.status:type_name -> app.external_payments.PaymentDenyReason
	1,  // 1: app.external_payments.ItemStatusResponse.reset_type:type_name -> app.external_payments.ShopResetType
	0,  // 2: app.external_payments.ExecutePaymentResponse.status:type_name -> app.external_payments.PaymentDenyReason
	0,  // 3: app.external_payments.ProductListItem.status:type_name -> app.external_payments.PaymentDenyReason
	1,  // 4: app.external_payments.ProductListItem.reset_type:type_name -> app.external_payments.ShopResetType
	9,  // 5: app.external_payments.GetProductListResponse.items:type_name -> app.external_payments.ProductListItem
	11, // 6: app.external_payments.ExternalPaymentsService.Nop:input_type -> google.protobuf.Empty
	4,  // 7: app.external_payments.ExternalPaymentsService.ItemStatus:input_type -> app.external_payments.ItemStatusRequest
	6,  // 8: app.external_payments.ExternalPaymentsService.ExecutePayment:input_type -> app.external_payments.ExecutePaymentRequest
	8,  // 9: app.external_payments.ExternalPaymentsService.GetProductList:input_type -> app.external_payments.GetProductListRequest
	11, // 10: app.external_payments.ExternalPaymentsService.Nop:output_type -> google.protobuf.Empty
	5,  // 11: app.external_payments.ExternalPaymentsService.ItemStatus:output_type -> app.external_payments.ItemStatusResponse
	7,  // 12: app.external_payments.ExternalPaymentsService.ExecutePayment:output_type -> app.external_payments.ExecutePaymentResponse
	10, // 13: app.external_payments.ExternalPaymentsService.GetProductList:output_type -> app.external_payments.GetProductListResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_external_payments_external_payments_service_proto_init() }
func file_app_external_payments_external_payments_service_proto_init() {
	if File_app_external_payments_external_payments_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_external_payments_external_payments_service_proto_rawDesc), len(file_app_external_payments_external_payments_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_external_payments_external_payments_service_proto_goTypes,
		DependencyIndexes: file_app_external_payments_external_payments_service_proto_depIdxs,
		EnumInfos:         file_app_external_payments_external_payments_service_proto_enumTypes,
		MessageInfos:      file_app_external_payments_external_payments_service_proto_msgTypes,
	}.Build()
	File_app_external_payments_external_payments_service_proto = out.File
	file_app_external_payments_external_payments_service_proto_goTypes = nil
	file_app_external_payments_external_payments_service_proto_depIdxs = nil
}
