// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/character/character_service.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GainFriendshipRankRewardRequest struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Rewards       []*entity.CharacterFriendshipRankReward `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GainFriendshipRankRewardRequest) Reset() {
	*x = GainFriendshipRankRewardRequest{}
	mi := &file_app_character_character_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GainFriendshipRankRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GainFriendshipRankRewardRequest) ProtoMessage() {}

func (x *GainFriendshipRankRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_character_character_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GainFriendshipRankRewardRequest.ProtoReflect.Descriptor instead.
func (*GainFriendshipRankRewardRequest) Descriptor() ([]byte, []int) {
	return file_app_character_character_service_proto_rawDescGZIP(), []int{0}
}

func (x *GainFriendshipRankRewardRequest) GetRewards() []*entity.CharacterFriendshipRankReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type GainFriendshipRankRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GainFriendshipRankRewardResponse) Reset() {
	*x = GainFriendshipRankRewardResponse{}
	mi := &file_app_character_character_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GainFriendshipRankRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GainFriendshipRankRewardResponse) ProtoMessage() {}

func (x *GainFriendshipRankRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_character_character_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GainFriendshipRankRewardResponse.ProtoReflect.Descriptor instead.
func (*GainFriendshipRankRewardResponse) Descriptor() ([]byte, []int) {
	return file_app_character_character_service_proto_rawDescGZIP(), []int{1}
}

func (x *GainFriendshipRankRewardResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_app_character_character_service_proto protoreflect.FileDescriptor

const file_app_character_character_service_proto_rawDesc = "" +
	"\n" +
	"%app/character/character_service.proto\x12\rapp.character\x1a\x16entity/character.proto\x1a\x19entity/notification.proto\"b\n" +
	"\x1fGainFriendshipRankRewardRequest\x12?\n" +
	"\arewards\x18\x01 \x03(\v2%.entity.CharacterFriendshipRankRewardR\arewards\"\\\n" +
	" GainFriendshipRankRewardResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification2\x8f\x01\n" +
	"\x10CharacterService\x12{\n" +
	"\x18GainFriendshipRankReward\x12..app.character.GainFriendshipRankRewardRequest\x1a/.app.character.GainFriendshipRankRewardResponseB\x19\xaa\x02\x16App.Protobuf.Characterb\x06proto3"

var (
	file_app_character_character_service_proto_rawDescOnce sync.Once
	file_app_character_character_service_proto_rawDescData []byte
)

func file_app_character_character_service_proto_rawDescGZIP() []byte {
	file_app_character_character_service_proto_rawDescOnce.Do(func() {
		file_app_character_character_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_character_character_service_proto_rawDesc), len(file_app_character_character_service_proto_rawDesc)))
	})
	return file_app_character_character_service_proto_rawDescData
}

var file_app_character_character_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_character_character_service_proto_goTypes = []any{
	(*GainFriendshipRankRewardRequest)(nil),      // 0: app.character.GainFriendshipRankRewardRequest
	(*GainFriendshipRankRewardResponse)(nil),     // 1: app.character.GainFriendshipRankRewardResponse
	(*entity.CharacterFriendshipRankReward)(nil), // 2: entity.CharacterFriendshipRankReward
	(*entity.Notification)(nil),                  // 3: entity.Notification
}
var file_app_character_character_service_proto_depIdxs = []int32{
	2, // 0: app.character.GainFriendshipRankRewardRequest.rewards:type_name -> entity.CharacterFriendshipRankReward
	3, // 1: app.character.GainFriendshipRankRewardResponse.notification:type_name -> entity.Notification
	0, // 2: app.character.CharacterService.GainFriendshipRankReward:input_type -> app.character.GainFriendshipRankRewardRequest
	1, // 3: app.character.CharacterService.GainFriendshipRankReward:output_type -> app.character.GainFriendshipRankRewardResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_character_character_service_proto_init() }
func file_app_character_character_service_proto_init() {
	if File_app_character_character_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_character_character_service_proto_rawDesc), len(file_app_character_character_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_character_character_service_proto_goTypes,
		DependencyIndexes: file_app_character_character_service_proto_depIdxs,
		MessageInfos:      file_app_character_character_service_proto_msgTypes,
	}.Build()
	File_app_character_character_service_proto = out.File
	file_app_character_character_service_proto_goTypes = nil
	file_app_character_character_service_proto_depIdxs = nil
}
