// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: app/invitation/invitation_service.proto

package invitation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvitationService_GenerateInvitationCode_FullMethodName = "/app.invitation.InvitationService/GenerateInvitationCode"
	InvitationService_InputInvitationCode_FullMethodName    = "/app.invitation.InvitationService/InputInvitationCode"
	InvitationService_UpdateInvitationView_FullMethodName   = "/app.invitation.InvitationService/UpdateInvitationView"
)

// InvitationServiceClient is the client API for InvitationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvitationServiceClient interface {
	GenerateInvitationCode(ctx context.Context, in *GenerateInvitationCodeRequest, opts ...grpc.CallOption) (*GenerateInvitationCodeResponse, error)
	InputInvitationCode(ctx context.Context, in *InputInvitationCodeRequest, opts ...grpc.CallOption) (*InputInvitationCodeResponse, error)
	UpdateInvitationView(ctx context.Context, in *UpdateInvitationViewRequest, opts ...grpc.CallOption) (*UpdateInvitationViewResponse, error)
}

type invitationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvitationServiceClient(cc grpc.ClientConnInterface) InvitationServiceClient {
	return &invitationServiceClient{cc}
}

func (c *invitationServiceClient) GenerateInvitationCode(ctx context.Context, in *GenerateInvitationCodeRequest, opts ...grpc.CallOption) (*GenerateInvitationCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInvitationCodeResponse)
	err := c.cc.Invoke(ctx, InvitationService_GenerateInvitationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) InputInvitationCode(ctx context.Context, in *InputInvitationCodeRequest, opts ...grpc.CallOption) (*InputInvitationCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputInvitationCodeResponse)
	err := c.cc.Invoke(ctx, InvitationService_InputInvitationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) UpdateInvitationView(ctx context.Context, in *UpdateInvitationViewRequest, opts ...grpc.CallOption) (*UpdateInvitationViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInvitationViewResponse)
	err := c.cc.Invoke(ctx, InvitationService_UpdateInvitationView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvitationServiceServer is the server API for InvitationService service.
// All implementations must embed UnimplementedInvitationServiceServer
// for forward compatibility.
type InvitationServiceServer interface {
	GenerateInvitationCode(context.Context, *GenerateInvitationCodeRequest) (*GenerateInvitationCodeResponse, error)
	InputInvitationCode(context.Context, *InputInvitationCodeRequest) (*InputInvitationCodeResponse, error)
	UpdateInvitationView(context.Context, *UpdateInvitationViewRequest) (*UpdateInvitationViewResponse, error)
	mustEmbedUnimplementedInvitationServiceServer()
}

// UnimplementedInvitationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvitationServiceServer struct{}

func (UnimplementedInvitationServiceServer) GenerateInvitationCode(context.Context, *GenerateInvitationCodeRequest) (*GenerateInvitationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInvitationCode not implemented")
}
func (UnimplementedInvitationServiceServer) InputInvitationCode(context.Context, *InputInvitationCodeRequest) (*InputInvitationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InputInvitationCode not implemented")
}
func (UnimplementedInvitationServiceServer) UpdateInvitationView(context.Context, *UpdateInvitationViewRequest) (*UpdateInvitationViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvitationView not implemented")
}
func (UnimplementedInvitationServiceServer) mustEmbedUnimplementedInvitationServiceServer() {}
func (UnimplementedInvitationServiceServer) testEmbeddedByValue()                           {}

// UnsafeInvitationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvitationServiceServer will
// result in compilation errors.
type UnsafeInvitationServiceServer interface {
	mustEmbedUnimplementedInvitationServiceServer()
}

func RegisterInvitationServiceServer(s grpc.ServiceRegistrar, srv InvitationServiceServer) {
	// If the following call pancis, it indicates UnimplementedInvitationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvitationService_ServiceDesc, srv)
}

func _InvitationService_GenerateInvitationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInvitationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).GenerateInvitationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvitationService_GenerateInvitationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).GenerateInvitationCode(ctx, req.(*GenerateInvitationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_InputInvitationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputInvitationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).InputInvitationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvitationService_InputInvitationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).InputInvitationCode(ctx, req.(*InputInvitationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_UpdateInvitationView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInvitationViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).UpdateInvitationView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvitationService_UpdateInvitationView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).UpdateInvitationView(ctx, req.(*UpdateInvitationViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvitationService_ServiceDesc is the grpc.ServiceDesc for InvitationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvitationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.invitation.InvitationService",
	HandlerType: (*InvitationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInvitationCode",
			Handler:    _InvitationService_GenerateInvitationCode_Handler,
		},
		{
			MethodName: "InputInvitationCode",
			Handler:    _InvitationService_InputInvitationCode_Handler,
		},
		{
			MethodName: "UpdateInvitationView",
			Handler:    _InvitationService_UpdateInvitationView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/invitation/invitation_service.proto",
}
