// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/vip/vip_service.proto

package vip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchVipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchVipRequest) Reset() {
	*x = FetchVipRequest{}
	mi := &file_app_vip_vip_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchVipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVipRequest) ProtoMessage() {}

func (x *FetchVipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVipRequest.ProtoReflect.Descriptor instead.
func (*FetchVipRequest) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{0}
}

type FetchVipResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Vip                   *entity.Vip            `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	PurchasedVipPackRanks []int32                `protobuf:"varint,2,rep,packed,name=purchased_vip_pack_ranks,json=purchasedVipPackRanks,proto3" json:"purchased_vip_pack_ranks,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FetchVipResponse) Reset() {
	*x = FetchVipResponse{}
	mi := &file_app_vip_vip_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchVipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVipResponse) ProtoMessage() {}

func (x *FetchVipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVipResponse.ProtoReflect.Descriptor instead.
func (*FetchVipResponse) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchVipResponse) GetVip() *entity.Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *FetchVipResponse) GetPurchasedVipPackRanks() []int32 {
	if x != nil {
		return x.PurchasedVipPackRanks
	}
	return nil
}

type ReceivePointRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConsecutiveLoginCount int32                  `protobuf:"varint,1,opt,name=consecutive_login_count,json=consecutiveLoginCount,proto3" json:"consecutive_login_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReceivePointRequest) Reset() {
	*x = ReceivePointRequest{}
	mi := &file_app_vip_vip_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivePointRequest) ProtoMessage() {}

func (x *ReceivePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivePointRequest.ProtoReflect.Descriptor instead.
func (*ReceivePointRequest) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReceivePointRequest) GetConsecutiveLoginCount() int32 {
	if x != nil {
		return x.ConsecutiveLoginCount
	}
	return 0
}

type ReceivePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vip           *entity.Vip            `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	Notification  *entity.Notification   `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivePointResponse) Reset() {
	*x = ReceivePointResponse{}
	mi := &file_app_vip_vip_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivePointResponse) ProtoMessage() {}

func (x *ReceivePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivePointResponse.ProtoReflect.Descriptor instead.
func (*ReceivePointResponse) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReceivePointResponse) GetVip() *entity.Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *ReceivePointResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ReceiveRankupRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VipRank       int32                  `protobuf:"varint,1,opt,name=vip_rank,json=vipRank,proto3" json:"vip_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRankupRewardRequest) Reset() {
	*x = ReceiveRankupRewardRequest{}
	mi := &file_app_vip_vip_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRankupRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRankupRewardRequest) ProtoMessage() {}

func (x *ReceiveRankupRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRankupRewardRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRankupRewardRequest) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveRankupRewardRequest) GetVipRank() int32 {
	if x != nil {
		return x.VipRank
	}
	return 0
}

type ReceiveRankupRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vip           *entity.Vip            `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	Notification  *entity.Notification   `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRankupRewardResponse) Reset() {
	*x = ReceiveRankupRewardResponse{}
	mi := &file_app_vip_vip_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRankupRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRankupRewardResponse) ProtoMessage() {}

func (x *ReceiveRankupRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRankupRewardResponse.ProtoReflect.Descriptor instead.
func (*ReceiveRankupRewardResponse) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveRankupRewardResponse) GetVip() *entity.Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *ReceiveRankupRewardResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ReceiveRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VipRank       int32                  `protobuf:"varint,1,opt,name=vip_rank,json=vipRank,proto3" json:"vip_rank,omitempty"`
	DayNumber     int32                  `protobuf:"varint,2,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRewardRequest) Reset() {
	*x = ReceiveRewardRequest{}
	mi := &file_app_vip_vip_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRewardRequest) ProtoMessage() {}

func (x *ReceiveRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRewardRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRewardRequest) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveRewardRequest) GetVipRank() int32 {
	if x != nil {
		return x.VipRank
	}
	return 0
}

func (x *ReceiveRewardRequest) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

type ReceiveRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vip           *entity.Vip            `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	Notification  *entity.Notification   `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRewardResponse) Reset() {
	*x = ReceiveRewardResponse{}
	mi := &file_app_vip_vip_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRewardResponse) ProtoMessage() {}

func (x *ReceiveRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRewardResponse.ProtoReflect.Descriptor instead.
func (*ReceiveRewardResponse) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveRewardResponse) GetVip() *entity.Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *ReceiveRewardResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type PurchaseRankPackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VipRank       int32                  `protobuf:"varint,1,opt,name=vip_rank,json=vipRank,proto3" json:"vip_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRankPackRequest) Reset() {
	*x = PurchaseRankPackRequest{}
	mi := &file_app_vip_vip_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRankPackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRankPackRequest) ProtoMessage() {}

func (x *PurchaseRankPackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRankPackRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRankPackRequest) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseRankPackRequest) GetVipRank() int32 {
	if x != nil {
		return x.VipRank
	}
	return 0
}

type PurchaseRankPackResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Vip                   *entity.Vip            `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	PurchasedVipPackRanks []int32                `protobuf:"varint,2,rep,packed,name=purchased_vip_pack_ranks,json=purchasedVipPackRanks,proto3" json:"purchased_vip_pack_ranks,omitempty"`
	Notification          *entity.Notification   `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PurchaseRankPackResponse) Reset() {
	*x = PurchaseRankPackResponse{}
	mi := &file_app_vip_vip_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRankPackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRankPackResponse) ProtoMessage() {}

func (x *PurchaseRankPackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vip_vip_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRankPackResponse.ProtoReflect.Descriptor instead.
func (*PurchaseRankPackResponse) Descriptor() ([]byte, []int) {
	return file_app_vip_vip_service_proto_rawDescGZIP(), []int{9}
}

func (x *PurchaseRankPackResponse) GetVip() *entity.Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *PurchaseRankPackResponse) GetPurchasedVipPackRanks() []int32 {
	if x != nil {
		return x.PurchasedVipPackRanks
	}
	return nil
}

func (x *PurchaseRankPackResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_app_vip_vip_service_proto protoreflect.FileDescriptor

const file_app_vip_vip_service_proto_rawDesc = "" +
	"\n" +
	"\x19app/vip/vip_service.proto\x12\aapp.vip\x1a\x19entity/notification.proto\x1a\x10entity/vip.proto\"\x11\n" +
	"\x0fFetchVipRequest\"j\n" +
	"\x10FetchVipResponse\x12\x1d\n" +
	"\x03vip\x18\x01 \x01(\v2\v.entity.VipR\x03vip\x127\n" +
	"\x18purchased_vip_pack_ranks\x18\x02 \x03(\x05R\x15purchasedVipPackRanks\"M\n" +
	"\x13ReceivePointRequest\x126\n" +
	"\x17consecutive_login_count\x18\x01 \x01(\x05R\x15consecutiveLoginCount\"o\n" +
	"\x14ReceivePointResponse\x12\x1d\n" +
	"\x03vip\x18\x01 \x01(\v2\v.entity.VipR\x03vip\x128\n" +
	"\fnotification\x18\x02 \x01(\v2\x14.entity.NotificationR\fnotification\"7\n" +
	"\x1aReceiveRankupRewardRequest\x12\x19\n" +
	"\bvip_rank\x18\x01 \x01(\x05R\avipRank\"v\n" +
	"\x1bReceiveRankupRewardResponse\x12\x1d\n" +
	"\x03vip\x18\x01 \x01(\v2\v.entity.VipR\x03vip\x128\n" +
	"\fnotification\x18\x02 \x01(\v2\x14.entity.NotificationR\fnotification\"P\n" +
	"\x14ReceiveRewardRequest\x12\x19\n" +
	"\bvip_rank\x18\x01 \x01(\x05R\avipRank\x12\x1d\n" +
	"\n" +
	"day_number\x18\x02 \x01(\x05R\tdayNumber\"p\n" +
	"\x15ReceiveRewardResponse\x12\x1d\n" +
	"\x03vip\x18\x01 \x01(\v2\v.entity.VipR\x03vip\x128\n" +
	"\fnotification\x18\x02 \x01(\v2\x14.entity.NotificationR\fnotification\"4\n" +
	"\x17PurchaseRankPackRequest\x12\x19\n" +
	"\bvip_rank\x18\x01 \x01(\x05R\avipRank\"\xac\x01\n" +
	"\x18PurchaseRankPackResponse\x12\x1d\n" +
	"\x03vip\x18\x01 \x01(\v2\v.entity.VipR\x03vip\x127\n" +
	"\x18purchased_vip_pack_ranks\x18\x02 \x03(\x05R\x15purchasedVipPackRanks\x128\n" +
	"\fnotification\x18\x03 \x01(\v2\x14.entity.NotificationR\fnotification2\xa2\x03\n" +
	"\n" +
	"VipService\x12<\n" +
	"\x05Fetch\x12\x18.app.vip.FetchVipRequest\x1a\x19.app.vip.FetchVipResponse\x12K\n" +
	"\fReceivePoint\x12\x1c.app.vip.ReceivePointRequest\x1a\x1d.app.vip.ReceivePointResponse\x12N\n" +
	"\rReceiveReward\x12\x1d.app.vip.ReceiveRewardRequest\x1a\x1e.app.vip.ReceiveRewardResponse\x12W\n" +
	"\x10PurchaseRankPack\x12 .app.vip.PurchaseRankPackRequest\x1a!.app.vip.PurchaseRankPackResponse\x12`\n" +
	"\x13ReceiveRankupReward\x12#.app.vip.ReceiveRankupRewardRequest\x1a$.app.vip.ReceiveRankupRewardResponseB\x13\xaa\x02\x10App.Protobuf.Vipb\x06proto3"

var (
	file_app_vip_vip_service_proto_rawDescOnce sync.Once
	file_app_vip_vip_service_proto_rawDescData []byte
)

func file_app_vip_vip_service_proto_rawDescGZIP() []byte {
	file_app_vip_vip_service_proto_rawDescOnce.Do(func() {
		file_app_vip_vip_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_vip_vip_service_proto_rawDesc), len(file_app_vip_vip_service_proto_rawDesc)))
	})
	return file_app_vip_vip_service_proto_rawDescData
}

var file_app_vip_vip_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_vip_vip_service_proto_goTypes = []any{
	(*FetchVipRequest)(nil),             // 0: app.vip.FetchVipRequest
	(*FetchVipResponse)(nil),            // 1: app.vip.FetchVipResponse
	(*ReceivePointRequest)(nil),         // 2: app.vip.ReceivePointRequest
	(*ReceivePointResponse)(nil),        // 3: app.vip.ReceivePointResponse
	(*ReceiveRankupRewardRequest)(nil),  // 4: app.vip.ReceiveRankupRewardRequest
	(*ReceiveRankupRewardResponse)(nil), // 5: app.vip.ReceiveRankupRewardResponse
	(*ReceiveRewardRequest)(nil),        // 6: app.vip.ReceiveRewardRequest
	(*ReceiveRewardResponse)(nil),       // 7: app.vip.ReceiveRewardResponse
	(*PurchaseRankPackRequest)(nil),     // 8: app.vip.PurchaseRankPackRequest
	(*PurchaseRankPackResponse)(nil),    // 9: app.vip.PurchaseRankPackResponse
	(*entity.Vip)(nil),                  // 10: entity.Vip
	(*entity.Notification)(nil),         // 11: entity.Notification
}
var file_app_vip_vip_service_proto_depIdxs = []int32{
	10, // 0: app.vip.FetchVipResponse.vip:type_name -> entity.Vip
	10, // 1: app.vip.ReceivePointResponse.vip:type_name -> entity.Vip
	11, // 2: app.vip.ReceivePointResponse.notification:type_name -> entity.Notification
	10, // 3: app.vip.ReceiveRankupRewardResponse.vip:type_name -> entity.Vip
	11, // 4: app.vip.ReceiveRankupRewardResponse.notification:type_name -> entity.Notification
	10, // 5: app.vip.ReceiveRewardResponse.vip:type_name -> entity.Vip
	11, // 6: app.vip.ReceiveRewardResponse.notification:type_name -> entity.Notification
	10, // 7: app.vip.PurchaseRankPackResponse.vip:type_name -> entity.Vip
	11, // 8: app.vip.PurchaseRankPackResponse.notification:type_name -> entity.Notification
	0,  // 9: app.vip.VipService.Fetch:input_type -> app.vip.FetchVipRequest
	2,  // 10: app.vip.VipService.ReceivePoint:input_type -> app.vip.ReceivePointRequest
	6,  // 11: app.vip.VipService.ReceiveReward:input_type -> app.vip.ReceiveRewardRequest
	8,  // 12: app.vip.VipService.PurchaseRankPack:input_type -> app.vip.PurchaseRankPackRequest
	4,  // 13: app.vip.VipService.ReceiveRankupReward:input_type -> app.vip.ReceiveRankupRewardRequest
	1,  // 14: app.vip.VipService.Fetch:output_type -> app.vip.FetchVipResponse
	3,  // 15: app.vip.VipService.ReceivePoint:output_type -> app.vip.ReceivePointResponse
	7,  // 16: app.vip.VipService.ReceiveReward:output_type -> app.vip.ReceiveRewardResponse
	9,  // 17: app.vip.VipService.PurchaseRankPack:output_type -> app.vip.PurchaseRankPackResponse
	5,  // 18: app.vip.VipService.ReceiveRankupReward:output_type -> app.vip.ReceiveRankupRewardResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_app_vip_vip_service_proto_init() }
func file_app_vip_vip_service_proto_init() {
	if File_app_vip_vip_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_vip_vip_service_proto_rawDesc), len(file_app_vip_vip_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_vip_vip_service_proto_goTypes,
		DependencyIndexes: file_app_vip_vip_service_proto_depIdxs,
		MessageInfos:      file_app_vip_vip_service_proto_msgTypes,
	}.Build()
	File_app_vip_vip_service_proto = out.File
	file_app_vip_vip_service_proto_goTypes = nil
	file_app_vip_vip_service_proto_depIdxs = nil
}
