// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/mission/mission_service.proto

package mission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	entity "private-notes/game/proto/entity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMissionRequest) Reset() {
	*x = FetchMissionRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMissionRequest) ProtoMessage() {}

func (x *FetchMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMissionRequest.ProtoReflect.Descriptor instead.
func (*FetchMissionRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{0}
}

type FetchMissionResponse struct {
	state             protoimpl.MessageState             `protogen:"open.v1"`
	MissionCounters   []*entity.MissionCounter           `protobuf:"bytes,1,rep,name=mission_counters,json=missionCounters,proto3" json:"mission_counters,omitempty"`
	NormalMissions    []*entity.MissionProgress          `protobuf:"bytes,2,rep,name=normal_missions,json=normalMissions,proto3" json:"normal_missions,omitempty"`
	LimitedMissions   []*entity.MissionProgress          `protobuf:"bytes,3,rep,name=limited_missions,json=limitedMissions,proto3" json:"limited_missions,omitempty"`
	CharacterMissions []*entity.CharacterMissionReceived `protobuf:"bytes,4,rep,name=character_missions,json=characterMissions,proto3" json:"character_missions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchMissionResponse) Reset() {
	*x = FetchMissionResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMissionResponse) ProtoMessage() {}

func (x *FetchMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMissionResponse.ProtoReflect.Descriptor instead.
func (*FetchMissionResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMissionResponse) GetMissionCounters() []*entity.MissionCounter {
	if x != nil {
		return x.MissionCounters
	}
	return nil
}

func (x *FetchMissionResponse) GetNormalMissions() []*entity.MissionProgress {
	if x != nil {
		return x.NormalMissions
	}
	return nil
}

func (x *FetchMissionResponse) GetLimitedMissions() []*entity.MissionProgress {
	if x != nil {
		return x.LimitedMissions
	}
	return nil
}

func (x *FetchMissionResponse) GetCharacterMissions() []*entity.CharacterMissionReceived {
	if x != nil {
		return x.CharacterMissions
	}
	return nil
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionIds    []int64                `protobuf:"varint,1,rep,packed,name=mission_ids,json=missionIds,proto3" json:"mission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveRequest) GetMissionIds() []int64 {
	if x != nil {
		return x.MissionIds
	}
	return nil
}

type ReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveResponse) Reset() {
	*x = ReceiveResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponse) ProtoMessage() {}

func (x *ReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponse.ProtoReflect.Descriptor instead.
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiveResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ReceiveLimitedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionIds    []int64                `protobuf:"varint,1,rep,packed,name=mission_ids,json=missionIds,proto3" json:"mission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveLimitedRequest) Reset() {
	*x = ReceiveLimitedRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveLimitedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveLimitedRequest) ProtoMessage() {}

func (x *ReceiveLimitedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveLimitedRequest.ProtoReflect.Descriptor instead.
func (*ReceiveLimitedRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveLimitedRequest) GetMissionIds() []int64 {
	if x != nil {
		return x.MissionIds
	}
	return nil
}

type ReceiveLimitedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveLimitedResponse) Reset() {
	*x = ReceiveLimitedResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveLimitedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveLimitedResponse) ProtoMessage() {}

func (x *ReceiveLimitedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveLimitedResponse.ProtoReflect.Descriptor instead.
func (*ReceiveLimitedResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveLimitedResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ReceiveCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	MissionIds    []int64                `protobuf:"varint,2,rep,packed,name=mission_ids,json=missionIds,proto3" json:"mission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCharacterRequest) Reset() {
	*x = ReceiveCharacterRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCharacterRequest) ProtoMessage() {}

func (x *ReceiveCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCharacterRequest.ProtoReflect.Descriptor instead.
func (*ReceiveCharacterRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveCharacterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ReceiveCharacterRequest) GetMissionIds() []int64 {
	if x != nil {
		return x.MissionIds
	}
	return nil
}

type ReceiveCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCharacterResponse) Reset() {
	*x = ReceiveCharacterResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCharacterResponse) ProtoMessage() {}

func (x *ReceiveCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCharacterResponse.ProtoReflect.Descriptor instead.
func (*ReceiveCharacterResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveCharacterResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type FetchEventMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEventMissionRequest) Reset() {
	*x = FetchEventMissionRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEventMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEventMissionRequest) ProtoMessage() {}

func (x *FetchEventMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEventMissionRequest.ProtoReflect.Descriptor instead.
func (*FetchEventMissionRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{8}
}

func (x *FetchEventMissionRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type FetchEventMissionResponse struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	MissionCounters   []*entity.MissionCounter  `protobuf:"bytes,1,rep,name=mission_counters,json=missionCounters,proto3" json:"mission_counters,omitempty"`
	MissionProgresses []*entity.MissionProgress `protobuf:"bytes,2,rep,name=mission_progresses,json=missionProgresses,proto3" json:"mission_progresses,omitempty"`
	Notification      *entity.Notification      `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchEventMissionResponse) Reset() {
	*x = FetchEventMissionResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEventMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEventMissionResponse) ProtoMessage() {}

func (x *FetchEventMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEventMissionResponse.ProtoReflect.Descriptor instead.
func (*FetchEventMissionResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{9}
}

func (x *FetchEventMissionResponse) GetMissionCounters() []*entity.MissionCounter {
	if x != nil {
		return x.MissionCounters
	}
	return nil
}

func (x *FetchEventMissionResponse) GetMissionProgresses() []*entity.MissionProgress {
	if x != nil {
		return x.MissionProgresses
	}
	return nil
}

func (x *FetchEventMissionResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ReceiveEventMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionIds    []int64                `protobuf:"varint,1,rep,packed,name=mission_ids,json=missionIds,proto3" json:"mission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveEventMissionRequest) Reset() {
	*x = ReceiveEventMissionRequest{}
	mi := &file_app_mission_mission_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveEventMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveEventMissionRequest) ProtoMessage() {}

func (x *ReceiveEventMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveEventMissionRequest.ProtoReflect.Descriptor instead.
func (*ReceiveEventMissionRequest) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiveEventMissionRequest) GetMissionIds() []int64 {
	if x != nil {
		return x.MissionIds
	}
	return nil
}

type ReceiveEventMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *entity.Notification   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveEventMissionResponse) Reset() {
	*x = ReceiveEventMissionResponse{}
	mi := &file_app_mission_mission_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveEventMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveEventMissionResponse) ProtoMessage() {}

func (x *ReceiveEventMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_mission_mission_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveEventMissionResponse.ProtoReflect.Descriptor instead.
func (*ReceiveEventMissionResponse) Descriptor() ([]byte, []int) {
	return file_app_mission_mission_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReceiveEventMissionResponse) GetNotification() *entity.Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_app_mission_mission_service_proto protoreflect.FileDescriptor

const file_app_mission_mission_service_proto_rawDesc = "" +
	"\n" +
	"!app/mission/mission_service.proto\x12\vapp.mission\x1a\x14entity/mission.proto\x1a\x19entity/notification.proto\"\x15\n" +
	"\x13FetchMissionRequest\"\xb0\x02\n" +
	"\x14FetchMissionResponse\x12A\n" +
	"\x10mission_counters\x18\x01 \x03(\v2\x16.entity.MissionCounterR\x0fmissionCounters\x12@\n" +
	"\x0fnormal_missions\x18\x02 \x03(\v2\x17.entity.MissionProgressR\x0enormalMissions\x12B\n" +
	"\x10limited_missions\x18\x03 \x03(\v2\x17.entity.MissionProgressR\x0flimitedMissions\x12O\n" +
	"\x12character_missions\x18\x04 \x03(\v2 .entity.CharacterMissionReceivedR\x11characterMissions\"1\n" +
	"\x0eReceiveRequest\x12\x1f\n" +
	"\vmission_ids\x18\x01 \x03(\x03R\n" +
	"missionIds\"K\n" +
	"\x0fReceiveResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification\"8\n" +
	"\x15ReceiveLimitedRequest\x12\x1f\n" +
	"\vmission_ids\x18\x01 \x03(\x03R\n" +
	"missionIds\"R\n" +
	"\x16ReceiveLimitedResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification\"]\n" +
	"\x17ReceiveCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1f\n" +
	"\vmission_ids\x18\x02 \x03(\x03R\n" +
	"missionIds\"T\n" +
	"\x18ReceiveCharacterResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification\"5\n" +
	"\x18FetchEventMissionRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"\xe0\x01\n" +
	"\x19FetchEventMissionResponse\x12A\n" +
	"\x10mission_counters\x18\x01 \x03(\v2\x16.entity.MissionCounterR\x0fmissionCounters\x12F\n" +
	"\x12mission_progresses\x18\x02 \x03(\v2\x17.entity.MissionProgressR\x11missionProgresses\x128\n" +
	"\fnotification\x18\x03 \x01(\v2\x14.entity.NotificationR\fnotification\"=\n" +
	"\x1aReceiveEventMissionRequest\x12\x1f\n" +
	"\vmission_ids\x18\x01 \x03(\x03R\n" +
	"missionIds\"W\n" +
	"\x1bReceiveEventMissionResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.entity.NotificationR\fnotification2\xa0\x04\n" +
	"\x0eMissionService\x12L\n" +
	"\x05Fetch\x12 .app.mission.FetchMissionRequest\x1a!.app.mission.FetchMissionResponse\x12D\n" +
	"\aReceive\x12\x1b.app.mission.ReceiveRequest\x1a\x1c.app.mission.ReceiveResponse\x12Y\n" +
	"\x0eReceiveLimited\x12\".app.mission.ReceiveLimitedRequest\x1a#.app.mission.ReceiveLimitedResponse\x12_\n" +
	"\x10ReceiveCharacter\x12$.app.mission.ReceiveCharacterRequest\x1a%.app.mission.ReceiveCharacterResponse\x12[\n" +
	"\n" +
	"FetchEvent\x12%.app.mission.FetchEventMissionRequest\x1a&.app.mission.FetchEventMissionResponse\x12a\n" +
	"\fReceiveEvent\x12'.app.mission.ReceiveEventMissionRequest\x1a(.app.mission.ReceiveEventMissionResponseB\x17\xaa\x02\x14App.Protobuf.Presentb\x06proto3"

var (
	file_app_mission_mission_service_proto_rawDescOnce sync.Once
	file_app_mission_mission_service_proto_rawDescData []byte
)

func file_app_mission_mission_service_proto_rawDescGZIP() []byte {
	file_app_mission_mission_service_proto_rawDescOnce.Do(func() {
		file_app_mission_mission_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_mission_mission_service_proto_rawDesc), len(file_app_mission_mission_service_proto_rawDesc)))
	})
	return file_app_mission_mission_service_proto_rawDescData
}

var file_app_mission_mission_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_mission_mission_service_proto_goTypes = []any{
	(*FetchMissionRequest)(nil),             // 0: app.mission.FetchMissionRequest
	(*FetchMissionResponse)(nil),            // 1: app.mission.FetchMissionResponse
	(*ReceiveRequest)(nil),                  // 2: app.mission.ReceiveRequest
	(*ReceiveResponse)(nil),                 // 3: app.mission.ReceiveResponse
	(*ReceiveLimitedRequest)(nil),           // 4: app.mission.ReceiveLimitedRequest
	(*ReceiveLimitedResponse)(nil),          // 5: app.mission.ReceiveLimitedResponse
	(*ReceiveCharacterRequest)(nil),         // 6: app.mission.ReceiveCharacterRequest
	(*ReceiveCharacterResponse)(nil),        // 7: app.mission.ReceiveCharacterResponse
	(*FetchEventMissionRequest)(nil),        // 8: app.mission.FetchEventMissionRequest
	(*FetchEventMissionResponse)(nil),       // 9: app.mission.FetchEventMissionResponse
	(*ReceiveEventMissionRequest)(nil),      // 10: app.mission.ReceiveEventMissionRequest
	(*ReceiveEventMissionResponse)(nil),     // 11: app.mission.ReceiveEventMissionResponse
	(*entity.MissionCounter)(nil),           // 12: entity.MissionCounter
	(*entity.MissionProgress)(nil),          // 13: entity.MissionProgress
	(*entity.CharacterMissionReceived)(nil), // 14: entity.CharacterMissionReceived
	(*entity.Notification)(nil),             // 15: entity.Notification
}
var file_app_mission_mission_service_proto_depIdxs = []int32{
	12, // 0: app.mission.FetchMissionResponse.mission_counters:type_name -> entity.MissionCounter
	13, // 1: app.mission.FetchMissionResponse.normal_missions:type_name -> entity.MissionProgress
	13, // 2: app.mission.FetchMissionResponse.limited_missions:type_name -> entity.MissionProgress
	14, // 3: app.mission.FetchMissionResponse.character_missions:type_name -> entity.CharacterMissionReceived
	15, // 4: app.mission.ReceiveResponse.notification:type_name -> entity.Notification
	15, // 5: app.mission.ReceiveLimitedResponse.notification:type_name -> entity.Notification
	15, // 6: app.mission.ReceiveCharacterResponse.notification:type_name -> entity.Notification
	12, // 7: app.mission.FetchEventMissionResponse.mission_counters:type_name -> entity.MissionCounter
	13, // 8: app.mission.FetchEventMissionResponse.mission_progresses:type_name -> entity.MissionProgress
	15, // 9: app.mission.FetchEventMissionResponse.notification:type_name -> entity.Notification
	15, // 10: app.mission.ReceiveEventMissionResponse.notification:type_name -> entity.Notification
	0,  // 11: app.mission.MissionService.Fetch:input_type -> app.mission.FetchMissionRequest
	2,  // 12: app.mission.MissionService.Receive:input_type -> app.mission.ReceiveRequest
	4,  // 13: app.mission.MissionService.ReceiveLimited:input_type -> app.mission.ReceiveLimitedRequest
	6,  // 14: app.mission.MissionService.ReceiveCharacter:input_type -> app.mission.ReceiveCharacterRequest
	8,  // 15: app.mission.MissionService.FetchEvent:input_type -> app.mission.FetchEventMissionRequest
	10, // 16: app.mission.MissionService.ReceiveEvent:input_type -> app.mission.ReceiveEventMissionRequest
	1,  // 17: app.mission.MissionService.Fetch:output_type -> app.mission.FetchMissionResponse
	3,  // 18: app.mission.MissionService.Receive:output_type -> app.mission.ReceiveResponse
	5,  // 19: app.mission.MissionService.ReceiveLimited:output_type -> app.mission.ReceiveLimitedResponse
	7,  // 20: app.mission.MissionService.ReceiveCharacter:output_type -> app.mission.ReceiveCharacterResponse
	9,  // 21: app.mission.MissionService.FetchEvent:output_type -> app.mission.FetchEventMissionResponse
	11, // 22: app.mission.MissionService.ReceiveEvent:output_type -> app.mission.ReceiveEventMissionResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_mission_mission_service_proto_init() }
func file_app_mission_mission_service_proto_init() {
	if File_app_mission_mission_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_mission_mission_service_proto_rawDesc), len(file_app_mission_mission_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_mission_mission_service_proto_goTypes,
		DependencyIndexes: file_app_mission_mission_service_proto_depIdxs,
		MessageInfos:      file_app_mission_mission_service_proto_msgTypes,
	}.Build()
	File_app_mission_mission_service_proto = out.File
	file_app_mission_mission_service_proto_goTypes = nil
	file_app_mission_mission_service_proto_depIdxs = nil
}
