// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/chat/chat_client_service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "private-notes/game/proto/entity/method_options"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientSendIMMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *IMMsg                 `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSendIMMsgRequest) Reset() {
	*x = ClientSendIMMsgRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSendIMMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSendIMMsgRequest) ProtoMessage() {}

func (x *ClientSendIMMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSendIMMsgRequest.ProtoReflect.Descriptor instead.
func (*ClientSendIMMsgRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientSendIMMsgRequest) GetMsg() *IMMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ClientSendIMMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSendIMMsgResponse) Reset() {
	*x = ClientSendIMMsgResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSendIMMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSendIMMsgResponse) ProtoMessage() {}

func (x *ClientSendIMMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSendIMMsgResponse.ProtoReflect.Descriptor instead.
func (*ClientSendIMMsgResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSendIMMsgResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ClientSendIMMsgResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ClientSyncMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	LastMsgID     int64                  `protobuf:"varint,2,opt,name=LastMsgID,proto3" json:"LastMsgID,omitempty"`
	Receiver      int64                  `protobuf:"varint,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSyncMsgRequest) Reset() {
	*x = ClientSyncMsgRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSyncMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSyncMsgRequest) ProtoMessage() {}

func (x *ClientSyncMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSyncMsgRequest.ProtoReflect.Descriptor instead.
func (*ClientSyncMsgRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *ClientSyncMsgRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ClientSyncMsgRequest) GetLastMsgID() int64 {
	if x != nil {
		return x.LastMsgID
	}
	return 0
}

func (x *ClientSyncMsgRequest) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

type ClientSyncMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSyncMsgResponse) Reset() {
	*x = ClientSyncMsgResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSyncMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSyncMsgResponse) ProtoMessage() {}

func (x *ClientSyncMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSyncMsgResponse.ProtoReflect.Descriptor instead.
func (*ClientSyncMsgResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSyncMsgResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type ClientGetWorldRoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetWorldRoomListRequest) Reset() {
	*x = ClientGetWorldRoomListRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetWorldRoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetWorldRoomListRequest) ProtoMessage() {}

func (x *ClientGetWorldRoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetWorldRoomListRequest.ProtoReflect.Descriptor instead.
func (*ClientGetWorldRoomListRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{4}
}

type ClientGetWorldRoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	RoomInfos     []*WorldRoomInfo       `protobuf:"bytes,2,rep,name=RoomInfos,proto3" json:"RoomInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetWorldRoomListResponse) Reset() {
	*x = ClientGetWorldRoomListResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetWorldRoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetWorldRoomListResponse) ProtoMessage() {}

func (x *ClientGetWorldRoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetWorldRoomListResponse.ProtoReflect.Descriptor instead.
func (*ClientGetWorldRoomListResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *ClientGetWorldRoomListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ClientGetWorldRoomListResponse) GetRoomInfos() []*WorldRoomInfo {
	if x != nil {
		return x.RoomInfos
	}
	return nil
}

type ClientSwitchWorldRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetRoomID  int64                  `protobuf:"varint,1,opt,name=TargetRoomID,proto3" json:"TargetRoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSwitchWorldRoomRequest) Reset() {
	*x = ClientSwitchWorldRoomRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSwitchWorldRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSwitchWorldRoomRequest) ProtoMessage() {}

func (x *ClientSwitchWorldRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSwitchWorldRoomRequest.ProtoReflect.Descriptor instead.
func (*ClientSwitchWorldRoomRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *ClientSwitchWorldRoomRequest) GetTargetRoomID() int64 {
	if x != nil {
		return x.TargetRoomID
	}
	return 0
}

type ClientSwitchWorldRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	WorldRoomID   int64                  `protobuf:"varint,2,opt,name=WorldRoomID,proto3" json:"WorldRoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSwitchWorldRoomResponse) Reset() {
	*x = ClientSwitchWorldRoomResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSwitchWorldRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSwitchWorldRoomResponse) ProtoMessage() {}

func (x *ClientSwitchWorldRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSwitchWorldRoomResponse.ProtoReflect.Descriptor instead.
func (*ClientSwitchWorldRoomResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *ClientSwitchWorldRoomResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ClientSwitchWorldRoomResponse) GetWorldRoomID() int64 {
	if x != nil {
		return x.WorldRoomID
	}
	return 0
}

type TopicSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Visible       bool                   `protobuf:"varint,2,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSetting) Reset() {
	*x = TopicSetting{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSetting) ProtoMessage() {}

func (x *TopicSetting) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSetting.ProtoReflect.Descriptor instead.
func (*TopicSetting) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{8}
}

func (x *TopicSetting) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TopicSetting) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type ChatDisplaySettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorldChannelVisible  bool                   `protobuf:"varint,1,opt,name=world_channel_visible,json=worldChannelVisible,proto3" json:"world_channel_visible,omitempty"`
	WorldFilterText      bool                   `protobuf:"varint,2,opt,name=world_filter_text,json=worldFilterText,proto3" json:"world_filter_text,omitempty"`
	WorldFilterStamp     bool                   `protobuf:"varint,3,opt,name=world_filter_stamp,json=worldFilterStamp,proto3" json:"world_filter_stamp,omitempty"`
	WorldFilterEntertain bool                   `protobuf:"varint,4,opt,name=world_filter_entertain,json=worldFilterEntertain,proto3" json:"world_filter_entertain,omitempty"`
	Topics               []*TopicSetting        `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChatDisplaySettings) Reset() {
	*x = ChatDisplaySettings{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDisplaySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDisplaySettings) ProtoMessage() {}

func (x *ChatDisplaySettings) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDisplaySettings.ProtoReflect.Descriptor instead.
func (*ChatDisplaySettings) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{9}
}

func (x *ChatDisplaySettings) GetWorldChannelVisible() bool {
	if x != nil {
		return x.WorldChannelVisible
	}
	return false
}

func (x *ChatDisplaySettings) GetWorldFilterText() bool {
	if x != nil {
		return x.WorldFilterText
	}
	return false
}

func (x *ChatDisplaySettings) GetWorldFilterStamp() bool {
	if x != nil {
		return x.WorldFilterStamp
	}
	return false
}

func (x *ChatDisplaySettings) GetWorldFilterEntertain() bool {
	if x != nil {
		return x.WorldFilterEntertain
	}
	return false
}

func (x *ChatDisplaySettings) GetTopics() []*TopicSetting {
	if x != nil {
		return x.Topics
	}
	return nil
}

type ClientSetChatSettingsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SpecialFocusAccountIds []int64                `protobuf:"varint,1,rep,packed,name=special_focus_account_ids,json=specialFocusAccountIds,proto3" json:"special_focus_account_ids,omitempty"`
	ChatThemeId            int64                  `protobuf:"varint,2,opt,name=chat_theme_id,json=chatThemeId,proto3" json:"chat_theme_id,omitempty"`
	ChatBubbleId           int64                  `protobuf:"varint,3,opt,name=chat_bubble_id,json=chatBubbleId,proto3" json:"chat_bubble_id,omitempty"`
	ChatFrameId            int64                  `protobuf:"varint,4,opt,name=chat_frame_id,json=chatFrameId,proto3" json:"chat_frame_id,omitempty"`
	DisplaySettings        *ChatDisplaySettings   `protobuf:"bytes,5,opt,name=display_settings,json=displaySettings,proto3" json:"display_settings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientSetChatSettingsRequest) Reset() {
	*x = ClientSetChatSettingsRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSetChatSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSetChatSettingsRequest) ProtoMessage() {}

func (x *ClientSetChatSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSetChatSettingsRequest.ProtoReflect.Descriptor instead.
func (*ClientSetChatSettingsRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{10}
}

func (x *ClientSetChatSettingsRequest) GetSpecialFocusAccountIds() []int64 {
	if x != nil {
		return x.SpecialFocusAccountIds
	}
	return nil
}

func (x *ClientSetChatSettingsRequest) GetChatThemeId() int64 {
	if x != nil {
		return x.ChatThemeId
	}
	return 0
}

func (x *ClientSetChatSettingsRequest) GetChatBubbleId() int64 {
	if x != nil {
		return x.ChatBubbleId
	}
	return 0
}

func (x *ClientSetChatSettingsRequest) GetChatFrameId() int64 {
	if x != nil {
		return x.ChatFrameId
	}
	return 0
}

func (x *ClientSetChatSettingsRequest) GetDisplaySettings() *ChatDisplaySettings {
	if x != nil {
		return x.DisplaySettings
	}
	return nil
}

type ClientSetChatSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSetChatSettingsResponse) Reset() {
	*x = ClientSetChatSettingsResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSetChatSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSetChatSettingsResponse) ProtoMessage() {}

func (x *ClientSetChatSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSetChatSettingsResponse.ProtoReflect.Descriptor instead.
func (*ClientSetChatSettingsResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{11}
}

func (x *ClientSetChatSettingsResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type ClientGetChatSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetChatSettingsRequest) Reset() {
	*x = ClientGetChatSettingsRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetChatSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetChatSettingsRequest) ProtoMessage() {}

func (x *ClientGetChatSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetChatSettingsRequest.ProtoReflect.Descriptor instead.
func (*ClientGetChatSettingsRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{12}
}

type ClientGetChatSettingsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ret                    int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	SpecialFocusAccountIds []int64                `protobuf:"varint,2,rep,packed,name=special_focus_account_ids,json=specialFocusAccountIds,proto3" json:"special_focus_account_ids,omitempty"`
	ChatThemeId            int64                  `protobuf:"varint,3,opt,name=chat_theme_id,json=chatThemeId,proto3" json:"chat_theme_id,omitempty"`
	ChatBubbleId           int64                  `protobuf:"varint,4,opt,name=chat_bubble_id,json=chatBubbleId,proto3" json:"chat_bubble_id,omitempty"`
	ChatFrameId            int64                  `protobuf:"varint,5,opt,name=chat_frame_id,json=chatFrameId,proto3" json:"chat_frame_id,omitempty"`
	DisplaySettings        *ChatDisplaySettings   `protobuf:"bytes,6,opt,name=display_settings,json=displaySettings,proto3" json:"display_settings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientGetChatSettingsResponse) Reset() {
	*x = ClientGetChatSettingsResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetChatSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetChatSettingsResponse) ProtoMessage() {}

func (x *ClientGetChatSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetChatSettingsResponse.ProtoReflect.Descriptor instead.
func (*ClientGetChatSettingsResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClientGetChatSettingsResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ClientGetChatSettingsResponse) GetSpecialFocusAccountIds() []int64 {
	if x != nil {
		return x.SpecialFocusAccountIds
	}
	return nil
}

func (x *ClientGetChatSettingsResponse) GetChatThemeId() int64 {
	if x != nil {
		return x.ChatThemeId
	}
	return 0
}

func (x *ClientGetChatSettingsResponse) GetChatBubbleId() int64 {
	if x != nil {
		return x.ChatBubbleId
	}
	return 0
}

func (x *ClientGetChatSettingsResponse) GetChatFrameId() int64 {
	if x != nil {
		return x.ChatFrameId
	}
	return 0
}

func (x *ClientGetChatSettingsResponse) GetDisplaySettings() *ChatDisplaySettings {
	if x != nil {
		return x.DisplaySettings
	}
	return nil
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{14}
}

type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationInfo    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetNotificationsResponse) GetNotifications() []*NotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type ClaimNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimNotificationRequest) Reset() {
	*x = ClaimNotificationRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNotificationRequest) ProtoMessage() {}

func (x *ClaimNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNotificationRequest.ProtoReflect.Descriptor instead.
func (*ClaimNotificationRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{16}
}

func (x *ClaimNotificationRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type ClaimNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimNotificationResponse) Reset() {
	*x = ClaimNotificationResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNotificationResponse) ProtoMessage() {}

func (x *ClaimNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNotificationResponse.ProtoReflect.Descriptor instead.
func (*ClaimNotificationResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimNotificationResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ClaimNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPlayerId int64                  `protobuf:"varint,1,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reason         *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatReportRequest) Reset() {
	*x = ChatReportRequest{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReportRequest) ProtoMessage() {}

func (x *ChatReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReportRequest.ProtoReflect.Descriptor instead.
func (*ChatReportRequest) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{18}
}

func (x *ChatReportRequest) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *ChatReportRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatReportRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type ChatReportResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ret                 int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ChatReportUsedToday int32                  `protobuf:"varint,2,opt,name=chat_report_used_today,json=chatReportUsedToday,proto3" json:"chat_report_used_today,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatReportResponse) Reset() {
	*x = ChatReportResponse{}
	mi := &file_app_chat_chat_client_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReportResponse) ProtoMessage() {}

func (x *ChatReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_client_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReportResponse.ProtoReflect.Descriptor instead.
func (*ChatReportResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_client_service_proto_rawDescGZIP(), []int{19}
}

func (x *ChatReportResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ChatReportResponse) GetChatReportUsedToday() int32 {
	if x != nil {
		return x.ChatReportUsedToday
	}
	return 0
}

var File_app_chat_chat_client_service_proto protoreflect.FileDescriptor

const file_app_chat_chat_client_service_proto_rawDesc = "" +
	"\n" +
	"\"app/chat/chat_client_service.proto\x12\bapp.chat\x1a\x1aapp/chat/chat_common.proto\x1a*entity/method_options/method_options.proto\";\n" +
	"\x16ClientSendIMMsgRequest\x12!\n" +
	"\x03Msg\x18\x01 \x01(\v2\x0f.app.chat.IMMsgR\x03Msg\"E\n" +
	"\x17ClientSendIMMsgResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\"d\n" +
	"\x14ClientSyncMsgRequest\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x1c\n" +
	"\tLastMsgID\x18\x02 \x01(\x03R\tLastMsgID\x12\x1a\n" +
	"\bReceiver\x18\x03 \x01(\x03R\bReceiver\")\n" +
	"\x15ClientSyncMsgResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\"\x1f\n" +
	"\x1dClientGetWorldRoomListRequest\"i\n" +
	"\x1eClientGetWorldRoomListResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\x125\n" +
	"\tRoomInfos\x18\x02 \x03(\v2\x17.app.chat.WorldRoomInfoR\tRoomInfos\"B\n" +
	"\x1cClientSwitchWorldRoomRequest\x12\"\n" +
	"\fTargetRoomID\x18\x01 \x01(\x03R\fTargetRoomID\"S\n" +
	"\x1dClientSwitchWorldRoomResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\x12 \n" +
	"\vWorldRoomID\x18\x02 \x01(\x03R\vWorldRoomID\"C\n" +
	"\fTopicSetting\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x18\n" +
	"\avisible\x18\x02 \x01(\bR\avisible\"\x89\x02\n" +
	"\x13ChatDisplaySettings\x122\n" +
	"\x15world_channel_visible\x18\x01 \x01(\bR\x13worldChannelVisible\x12*\n" +
	"\x11world_filter_text\x18\x02 \x01(\bR\x0fworldFilterText\x12,\n" +
	"\x12world_filter_stamp\x18\x03 \x01(\bR\x10worldFilterStamp\x124\n" +
	"\x16world_filter_entertain\x18\x04 \x01(\bR\x14worldFilterEntertain\x12.\n" +
	"\x06topics\x18\x05 \x03(\v2\x16.app.chat.TopicSettingR\x06topics\"\x91\x02\n" +
	"\x1cClientSetChatSettingsRequest\x129\n" +
	"\x19special_focus_account_ids\x18\x01 \x03(\x03R\x16specialFocusAccountIds\x12\"\n" +
	"\rchat_theme_id\x18\x02 \x01(\x03R\vchatThemeId\x12$\n" +
	"\x0echat_bubble_id\x18\x03 \x01(\x03R\fchatBubbleId\x12\"\n" +
	"\rchat_frame_id\x18\x04 \x01(\x03R\vchatFrameId\x12H\n" +
	"\x10display_settings\x18\x05 \x01(\v2\x1d.app.chat.ChatDisplaySettingsR\x0fdisplaySettings\"1\n" +
	"\x1dClientSetChatSettingsResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\"\x1e\n" +
	"\x1cClientGetChatSettingsRequest\"\xa4\x02\n" +
	"\x1dClientGetChatSettingsResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\x129\n" +
	"\x19special_focus_account_ids\x18\x02 \x03(\x03R\x16specialFocusAccountIds\x12\"\n" +
	"\rchat_theme_id\x18\x03 \x01(\x03R\vchatThemeId\x12$\n" +
	"\x0echat_bubble_id\x18\x04 \x01(\x03R\fchatBubbleId\x12\"\n" +
	"\rchat_frame_id\x18\x05 \x01(\x03R\vchatFrameId\x12H\n" +
	"\x10display_settings\x18\x06 \x01(\v2\x1d.app.chat.ChatDisplaySettingsR\x0fdisplaySettings\"\x19\n" +
	"\x17GetNotificationsRequest\"\\\n" +
	"\x18GetNotificationsResponse\x12@\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1a.app.chat.NotificationInfoR\rnotifications\"C\n" +
	"\x18ClaimNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"G\n" +
	"\x19ClaimNotificationResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x11ChatReportRequest\x12(\n" +
	"\x10target_player_id\x18\x01 \x01(\x03R\x0etargetPlayerId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"[\n" +
	"\x12ChatReportResponse\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\x123\n" +
	"\x16chat_report_used_today\x18\x02 \x01(\x05R\x13chatReportUsedToday2\xe2\x06\n" +
	"\x11ClientChatService\x12X\n" +
	"\tSendIMMsg\x12 .app.chat.ClientSendIMMsgRequest\x1a!.app.chat.ClientSendIMMsgResponse\"\x06\x92\xb5\x18\x02@\x01\x12R\n" +
	"\aSyncMsg\x12\x1e.app.chat.ClientSyncMsgRequest\x1a\x1f.app.chat.ClientSyncMsgResponse\"\x06\x92\xb5\x18\x02@\x01\x12m\n" +
	"\x10GetWorldRoomList\x12'.app.chat.ClientGetWorldRoomListRequest\x1a(.app.chat.ClientGetWorldRoomListResponse\"\x06\x92\xb5\x18\x02@\x01\x12j\n" +
	"\x0fSwitchWorldRoom\x12&.app.chat.ClientSwitchWorldRoomRequest\x1a'.app.chat.ClientSwitchWorldRoomResponse\"\x06\x92\xb5\x18\x02@\x01\x12b\n" +
	"\x0fSetChatSettings\x12&.app.chat.ClientSetChatSettingsRequest\x1a'.app.chat.ClientSetChatSettingsResponse\x12b\n" +
	"\x0fGetChatSettings\x12&.app.chat.ClientGetChatSettingsRequest\x1a'.app.chat.ClientGetChatSettingsResponse\x12Y\n" +
	"\x10GetNotifications\x12!.app.chat.GetNotificationsRequest\x1a\".app.chat.GetNotificationsResponse\x12\\\n" +
	"\x11ClaimNotification\x12\".app.chat.ClaimNotificationRequest\x1a#.app.chat.ClaimNotificationResponse\x12C\n" +
	"\x06Report\x12\x1b.app.chat.ChatReportRequest\x1a\x1c.app.chat.ChatReportResponseB\x14\xaa\x02\x11App.Protobuf.Chatb\x06proto3"

var (
	file_app_chat_chat_client_service_proto_rawDescOnce sync.Once
	file_app_chat_chat_client_service_proto_rawDescData []byte
)

func file_app_chat_chat_client_service_proto_rawDescGZIP() []byte {
	file_app_chat_chat_client_service_proto_rawDescOnce.Do(func() {
		file_app_chat_chat_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_chat_chat_client_service_proto_rawDesc), len(file_app_chat_chat_client_service_proto_rawDesc)))
	})
	return file_app_chat_chat_client_service_proto_rawDescData
}

var file_app_chat_chat_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_app_chat_chat_client_service_proto_goTypes = []any{
	(*ClientSendIMMsgRequest)(nil),         // 0: app.chat.ClientSendIMMsgRequest
	(*ClientSendIMMsgResponse)(nil),        // 1: app.chat.ClientSendIMMsgResponse
	(*ClientSyncMsgRequest)(nil),           // 2: app.chat.ClientSyncMsgRequest
	(*ClientSyncMsgResponse)(nil),          // 3: app.chat.ClientSyncMsgResponse
	(*ClientGetWorldRoomListRequest)(nil),  // 4: app.chat.ClientGetWorldRoomListRequest
	(*ClientGetWorldRoomListResponse)(nil), // 5: app.chat.ClientGetWorldRoomListResponse
	(*ClientSwitchWorldRoomRequest)(nil),   // 6: app.chat.ClientSwitchWorldRoomRequest
	(*ClientSwitchWorldRoomResponse)(nil),  // 7: app.chat.ClientSwitchWorldRoomResponse
	(*TopicSetting)(nil),                   // 8: app.chat.TopicSetting
	(*ChatDisplaySettings)(nil),            // 9: app.chat.ChatDisplaySettings
	(*ClientSetChatSettingsRequest)(nil),   // 10: app.chat.ClientSetChatSettingsRequest
	(*ClientSetChatSettingsResponse)(nil),  // 11: app.chat.ClientSetChatSettingsResponse
	(*ClientGetChatSettingsRequest)(nil),   // 12: app.chat.ClientGetChatSettingsRequest
	(*ClientGetChatSettingsResponse)(nil),  // 13: app.chat.ClientGetChatSettingsResponse
	(*GetNotificationsRequest)(nil),        // 14: app.chat.GetNotificationsRequest
	(*GetNotificationsResponse)(nil),       // 15: app.chat.GetNotificationsResponse
	(*ClaimNotificationRequest)(nil),       // 16: app.chat.ClaimNotificationRequest
	(*ClaimNotificationResponse)(nil),      // 17: app.chat.ClaimNotificationResponse
	(*ChatReportRequest)(nil),              // 18: app.chat.ChatReportRequest
	(*ChatReportResponse)(nil),             // 19: app.chat.ChatReportResponse
	(*IMMsg)(nil),                          // 20: app.chat.IMMsg
	(*WorldRoomInfo)(nil),                  // 21: app.chat.WorldRoomInfo
	(*NotificationInfo)(nil),               // 22: app.chat.NotificationInfo
}
var file_app_chat_chat_client_service_proto_depIdxs = []int32{
	20, // 0: app.chat.ClientSendIMMsgRequest.Msg:type_name -> app.chat.IMMsg
	21, // 1: app.chat.ClientGetWorldRoomListResponse.RoomInfos:type_name -> app.chat.WorldRoomInfo
	8,  // 2: app.chat.ChatDisplaySettings.topics:type_name -> app.chat.TopicSetting
	9,  // 3: app.chat.ClientSetChatSettingsRequest.display_settings:type_name -> app.chat.ChatDisplaySettings
	9,  // 4: app.chat.ClientGetChatSettingsResponse.display_settings:type_name -> app.chat.ChatDisplaySettings
	22, // 5: app.chat.GetNotificationsResponse.notifications:type_name -> app.chat.NotificationInfo
	0,  // 6: app.chat.ClientChatService.SendIMMsg:input_type -> app.chat.ClientSendIMMsgRequest
	2,  // 7: app.chat.ClientChatService.SyncMsg:input_type -> app.chat.ClientSyncMsgRequest
	4,  // 8: app.chat.ClientChatService.GetWorldRoomList:input_type -> app.chat.ClientGetWorldRoomListRequest
	6,  // 9: app.chat.ClientChatService.SwitchWorldRoom:input_type -> app.chat.ClientSwitchWorldRoomRequest
	10, // 10: app.chat.ClientChatService.SetChatSettings:input_type -> app.chat.ClientSetChatSettingsRequest
	12, // 11: app.chat.ClientChatService.GetChatSettings:input_type -> app.chat.ClientGetChatSettingsRequest
	14, // 12: app.chat.ClientChatService.GetNotifications:input_type -> app.chat.GetNotificationsRequest
	16, // 13: app.chat.ClientChatService.ClaimNotification:input_type -> app.chat.ClaimNotificationRequest
	18, // 14: app.chat.ClientChatService.Report:input_type -> app.chat.ChatReportRequest
	1,  // 15: app.chat.ClientChatService.SendIMMsg:output_type -> app.chat.ClientSendIMMsgResponse
	3,  // 16: app.chat.ClientChatService.SyncMsg:output_type -> app.chat.ClientSyncMsgResponse
	5,  // 17: app.chat.ClientChatService.GetWorldRoomList:output_type -> app.chat.ClientGetWorldRoomListResponse
	7,  // 18: app.chat.ClientChatService.SwitchWorldRoom:output_type -> app.chat.ClientSwitchWorldRoomResponse
	11, // 19: app.chat.ClientChatService.SetChatSettings:output_type -> app.chat.ClientSetChatSettingsResponse
	13, // 20: app.chat.ClientChatService.GetChatSettings:output_type -> app.chat.ClientGetChatSettingsResponse
	15, // 21: app.chat.ClientChatService.GetNotifications:output_type -> app.chat.GetNotificationsResponse
	17, // 22: app.chat.ClientChatService.ClaimNotification:output_type -> app.chat.ClaimNotificationResponse
	19, // 23: app.chat.ClientChatService.Report:output_type -> app.chat.ChatReportResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_chat_chat_client_service_proto_init() }
func file_app_chat_chat_client_service_proto_init() {
	if File_app_chat_chat_client_service_proto != nil {
		return
	}
	file_app_chat_chat_common_proto_init()
	file_app_chat_chat_client_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_chat_chat_client_service_proto_rawDesc), len(file_app_chat_chat_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_chat_chat_client_service_proto_goTypes,
		DependencyIndexes: file_app_chat_chat_client_service_proto_depIdxs,
		MessageInfos:      file_app_chat_chat_client_service_proto_msgTypes,
	}.Build()
	File_app_chat_chat_client_service_proto = out.File
	file_app_chat_chat_client_service_proto_goTypes = nil
	file_app_chat_chat_client_service_proto_depIdxs = nil
}
