// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: app/chat/chat_common.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GmChatOpt int32

const (
	GmChatOpt_ChatOpt_None      GmChatOpt = 0
	GmChatOpt_ChatOpt_GetForbid GmChatOpt = 1
	GmChatOpt_ChatOpt_SetForbid GmChatOpt = 2
)

// Enum value maps for GmChatOpt.
var (
	GmChatOpt_name = map[int32]string{
		0: "ChatOpt_None",
		1: "ChatOpt_GetForbid",
		2: "ChatOpt_SetForbid",
	}
	GmChatOpt_value = map[string]int32{
		"ChatOpt_None":      0,
		"ChatOpt_GetForbid": 1,
		"ChatOpt_SetForbid": 2,
	}
)

func (x GmChatOpt) Enum() *GmChatOpt {
	p := new(GmChatOpt)
	*p = x
	return p
}

func (x GmChatOpt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GmChatOpt) Descriptor() protoreflect.EnumDescriptor {
	return file_app_chat_chat_common_proto_enumTypes[0].Descriptor()
}

func (GmChatOpt) Type() protoreflect.EnumType {
	return &file_app_chat_chat_common_proto_enumTypes[0]
}

func (x GmChatOpt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GmChatOpt.Descriptor instead.
func (GmChatOpt) EnumDescriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MessageType_Chat_Emoji         MessageType = 0
	MessageType_MessageType_Chat_Text          MessageType = 1
	MessageType_MessageType_Chat_TextFromSound MessageType = 2
	MessageType_MessageType_Chat_InviteTeam    MessageType = 3
	MessageType_MessageType_Chat_InviteLeague  MessageType = 4
	MessageType_MessageType_Chat_RoomDismiss   MessageType = 5
	MessageType_MessageType_System_FriendAdded MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MessageType_Chat_Emoji",
		1: "MessageType_Chat_Text",
		2: "MessageType_Chat_TextFromSound",
		3: "MessageType_Chat_InviteTeam",
		4: "MessageType_Chat_InviteLeague",
		5: "MessageType_Chat_RoomDismiss",
		6: "MessageType_System_FriendAdded",
	}
	MessageType_value = map[string]int32{
		"MessageType_Chat_Emoji":         0,
		"MessageType_Chat_Text":          1,
		"MessageType_Chat_TextFromSound": 2,
		"MessageType_Chat_InviteTeam":    3,
		"MessageType_Chat_InviteLeague":  4,
		"MessageType_Chat_RoomDismiss":   5,
		"MessageType_System_FriendAdded": 6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_chat_chat_common_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_app_chat_chat_common_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{1}
}

type EIMType int32

const (
	EIMType_IM_Peer EIMType = 0
	EIMType_IM_Room EIMType = 4
)

// Enum value maps for EIMType.
var (
	EIMType_name = map[int32]string{
		0: "IM_Peer",
		4: "IM_Room",
	}
	EIMType_value = map[string]int32{
		"IM_Peer": 0,
		"IM_Room": 4,
	}
)

func (x EIMType) Enum() *EIMType {
	p := new(EIMType)
	*p = x
	return p
}

func (x EIMType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EIMType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_chat_chat_common_proto_enumTypes[2].Descriptor()
}

func (EIMType) Type() protoreflect.EnumType {
	return &file_app_chat_chat_common_proto_enumTypes[2]
}

func (x EIMType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EIMType.Descriptor instead.
func (EIMType) EnumDescriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{2}
}

type GRPCCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCCommonResponse) Reset() {
	*x = GRPCCommonResponse{}
	mi := &file_app_chat_chat_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCCommonResponse) ProtoMessage() {}

func (x *GRPCCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCCommonResponse.ProtoReflect.Descriptor instead.
func (*GRPCCommonResponse) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCCommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GRPCCommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GRPCPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCPing) Reset() {
	*x = GRPCPing{}
	mi := &file_app_chat_chat_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCPing) ProtoMessage() {}

func (x *GRPCPing) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCPing.ProtoReflect.Descriptor instead.
func (*GRPCPing) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCPing) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BaseNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
	RetMsg        string                 `protobuf:"bytes,2,opt,name=RetMsg,proto3" json:"RetMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseNoti) Reset() {
	*x = BaseNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseNoti) ProtoMessage() {}

func (x *BaseNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseNoti.ProtoReflect.Descriptor instead.
func (*BaseNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{2}
}

func (x *BaseNoti) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *BaseNoti) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

type RPCCommonNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCCommonNoti) Reset() {
	*x = RPCCommonNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCCommonNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCCommonNoti) ProtoMessage() {}

func (x *RPCCommonNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCCommonNoti.ProtoReflect.Descriptor instead.
func (*RPCCommonNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{3}
}

func (x *RPCCommonNoti) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type MessageRetNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNoti              `protobuf:"bytes,3,opt,name=Base,proto3" json:"Base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRetNoti) Reset() {
	*x = MessageRetNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRetNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRetNoti) ProtoMessage() {}

func (x *MessageRetNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRetNoti.ProtoReflect.Descriptor instead.
func (*MessageRetNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRetNoti) GetBase() *BaseNoti {
	if x != nil {
		return x.Base
	}
	return nil
}

type CSCommonMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgkey        string                 `protobuf:"bytes,2,opt,name=Msgkey,proto3" json:"Msgkey,omitempty"`
	Msgbody       []byte                 `protobuf:"bytes,3,opt,name=Msgbody,proto3" json:"Msgbody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSCommonMessage) Reset() {
	*x = CSCommonMessage{}
	mi := &file_app_chat_chat_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSCommonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSCommonMessage) ProtoMessage() {}

func (x *CSCommonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSCommonMessage.ProtoReflect.Descriptor instead.
func (*CSCommonMessage) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{5}
}

func (x *CSCommonMessage) GetMsgkey() string {
	if x != nil {
		return x.Msgkey
	}
	return ""
}

func (x *CSCommonMessage) GetMsgbody() []byte {
	if x != nil {
		return x.Msgbody
	}
	return nil
}

type ChatText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatText) Reset() {
	*x = ChatText{}
	mi := &file_app_chat_chat_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatText) ProtoMessage() {}

func (x *ChatText) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatText.ProtoReflect.Descriptor instead.
func (*ChatText) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{6}
}

func (x *ChatText) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ChatText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatEmoji struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	EmojiID       int32                  `protobuf:"varint,2,opt,name=EmojiID,proto3" json:"EmojiID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEmoji) Reset() {
	*x = ChatEmoji{}
	mi := &file_app_chat_chat_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEmoji) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEmoji) ProtoMessage() {}

func (x *ChatEmoji) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEmoji.ProtoReflect.Descriptor instead.
func (*ChatEmoji) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{7}
}

func (x *ChatEmoji) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ChatEmoji) GetEmojiID() int32 {
	if x != nil {
		return x.EmojiID
	}
	return 0
}

type ChatTextFromSound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	SoundUrl      string                 `protobuf:"bytes,3,opt,name=SoundUrl,proto3" json:"SoundUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTextFromSound) Reset() {
	*x = ChatTextFromSound{}
	mi := &file_app_chat_chat_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTextFromSound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTextFromSound) ProtoMessage() {}

func (x *ChatTextFromSound) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTextFromSound.ProtoReflect.Descriptor instead.
func (*ChatTextFromSound) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{8}
}

func (x *ChatTextFromSound) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ChatTextFromSound) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatTextFromSound) GetSoundUrl() string {
	if x != nil {
		return x.SoundUrl
	}
	return ""
}

type ChatJoinLeagueAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatJoinLeagueAccepted) Reset() {
	*x = ChatJoinLeagueAccepted{}
	mi := &file_app_chat_chat_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatJoinLeagueAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatJoinLeagueAccepted) ProtoMessage() {}

func (x *ChatJoinLeagueAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatJoinLeagueAccepted.ProtoReflect.Descriptor instead.
func (*ChatJoinLeagueAccepted) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{9}
}

func (x *ChatJoinLeagueAccepted) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type IMMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgID         int64                  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Sender        int64                  `protobuf:"varint,3,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver      int64                  `protobuf:"varint,4,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Receivers     []int64                `protobuf:"varint,9,rep,packed,name=Receivers,proto3" json:"Receivers,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	MsgType       int32                  `protobuf:"varint,6,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Time          int64                  `protobuf:"varint,8,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMMsg) Reset() {
	*x = IMMsg{}
	mi := &file_app_chat_chat_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg) ProtoMessage() {}

func (x *IMMsg) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg.ProtoReflect.Descriptor instead.
func (*IMMsg) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{10}
}

func (x *IMMsg) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *IMMsg) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *IMMsg) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *IMMsg) GetReceivers() []int64 {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *IMMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *IMMsg) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *IMMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IMMsg) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type IMMsgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*IMMsg               `protobuf:"bytes,1,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMMsgs) Reset() {
	*x = IMMsgs{}
	mi := &file_app_chat_chat_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMMsgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsgs) ProtoMessage() {}

func (x *IMMsgs) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsgs.ProtoReflect.Descriptor instead.
func (*IMMsgs) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{11}
}

func (x *IMMsgs) GetMsgs() []*IMMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type MessageIMNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*IMMsg               `protobuf:"bytes,3,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageIMNoti) Reset() {
	*x = MessageIMNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageIMNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIMNoti) ProtoMessage() {}

func (x *MessageIMNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIMNoti.ProtoReflect.Descriptor instead.
func (*MessageIMNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{12}
}

func (x *MessageIMNoti) GetMsgs() []*IMMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type MessageNewMsgNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgID         int64                  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Receiver      int64                  `protobuf:"varint,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageNewMsgNoti) Reset() {
	*x = MessageNewMsgNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageNewMsgNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNewMsgNoti) ProtoMessage() {}

func (x *MessageNewMsgNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNewMsgNoti.ProtoReflect.Descriptor instead.
func (*MessageNewMsgNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{13}
}

func (x *MessageNewMsgNoti) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *MessageNewMsgNoti) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

type MessageGroupMsgNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *IMMsg                 `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	AccountIDs    []int64                `protobuf:"varint,5,rep,packed,name=AccountIDs,proto3" json:"AccountIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageGroupMsgNoti) Reset() {
	*x = MessageGroupMsgNoti{}
	mi := &file_app_chat_chat_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageGroupMsgNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGroupMsgNoti) ProtoMessage() {}

func (x *MessageGroupMsgNoti) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGroupMsgNoti.ProtoReflect.Descriptor instead.
func (*MessageGroupMsgNoti) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{14}
}

func (x *MessageGroupMsgNoti) GetMsg() *IMMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MessageGroupMsgNoti) GetAccountIDs() []int64 {
	if x != nil {
		return x.AccountIDs
	}
	return nil
}

type WorldRoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        int64                  `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	MemberNum     int32                  `protobuf:"varint,2,opt,name=MemberNum,proto3" json:"MemberNum,omitempty"`
	MaxMemberNum  int32                  `protobuf:"varint,3,opt,name=MaxMemberNum,proto3" json:"MaxMemberNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldRoomInfo) Reset() {
	*x = WorldRoomInfo{}
	mi := &file_app_chat_chat_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldRoomInfo) ProtoMessage() {}

func (x *WorldRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldRoomInfo.ProtoReflect.Descriptor instead.
func (*WorldRoomInfo) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{15}
}

func (x *WorldRoomInfo) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *WorldRoomInfo) GetMemberNum() int32 {
	if x != nil {
		return x.MemberNum
	}
	return 0
}

func (x *WorldRoomInfo) GetMaxMemberNum() int32 {
	if x != nil {
		return x.MaxMemberNum
	}
	return 0
}

type NotificationReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  int32                  `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceCount int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationReward) Reset() {
	*x = NotificationReward{}
	mi := &file_app_chat_chat_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationReward) ProtoMessage() {}

func (x *NotificationReward) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationReward.ProtoReflect.Descriptor instead.
func (*NotificationReward) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{16}
}

func (x *NotificationReward) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *NotificationReward) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *NotificationReward) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type NotificationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NotificationType int32                  `protobuf:"varint,2,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ExpireAt         int64                  `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	HasRewards       bool                   `protobuf:"varint,6,opt,name=has_rewards,json=hasRewards,proto3" json:"has_rewards,omitempty"`
	Claimed          bool                   `protobuf:"varint,7,opt,name=claimed,proto3" json:"claimed,omitempty"`
	Rewards          []*NotificationReward  `protobuf:"bytes,8,rep,name=rewards,proto3" json:"rewards,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationInfo) Reset() {
	*x = NotificationInfo{}
	mi := &file_app_chat_chat_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationInfo) ProtoMessage() {}

func (x *NotificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_chat_chat_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationInfo.ProtoReflect.Descriptor instead.
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return file_app_chat_chat_common_proto_rawDescGZIP(), []int{17}
}

func (x *NotificationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationInfo) GetNotificationType() int32 {
	if x != nil {
		return x.NotificationType
	}
	return 0
}

func (x *NotificationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *NotificationInfo) GetHasRewards() bool {
	if x != nil {
		return x.HasRewards
	}
	return false
}

func (x *NotificationInfo) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *NotificationInfo) GetRewards() []*NotificationReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *NotificationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_app_chat_chat_common_proto protoreflect.FileDescriptor

const file_app_chat_chat_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapp/chat/chat_common.proto\x12\bapp.chat\"B\n" +
	"\x12GRPCCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\bGRPCPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\"<\n" +
	"\bBaseNoti\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCode\x12\x16\n" +
	"\x06RetMsg\x18\x02 \x01(\tR\x06RetMsg\"!\n" +
	"\rRPCCommonNoti\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\"8\n" +
	"\x0eMessageRetNoti\x12&\n" +
	"\x04Base\x18\x03 \x01(\v2\x12.app.chat.BaseNotiR\x04Base\"C\n" +
	"\x0fCSCommonMessage\x12\x16\n" +
	"\x06Msgkey\x18\x02 \x01(\tR\x06Msgkey\x12\x18\n" +
	"\aMsgbody\x18\x03 \x01(\fR\aMsgbody\".\n" +
	"\bChatText\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Text\x18\x02 \x01(\tR\x04Text\"5\n" +
	"\tChatEmoji\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x18\n" +
	"\aEmojiID\x18\x02 \x01(\x05R\aEmojiID\"S\n" +
	"\x11ChatTextFromSound\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Text\x18\x02 \x01(\tR\x04Text\x12\x1a\n" +
	"\bSoundUrl\x18\x03 \x01(\tR\bSoundUrl\"(\n" +
	"\x16ChatJoinLeagueAccepted\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\"\xcb\x01\n" +
	"\x05IMMsg\x12\x14\n" +
	"\x05MsgID\x18\x02 \x01(\x03R\x05MsgID\x12\x16\n" +
	"\x06Sender\x18\x03 \x01(\x03R\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x04 \x01(\x03R\bReceiver\x12\x1c\n" +
	"\tReceivers\x18\t \x03(\x03R\tReceivers\x12\x12\n" +
	"\x04Type\x18\x05 \x01(\x05R\x04Type\x12\x18\n" +
	"\aMsgType\x18\x06 \x01(\x05R\aMsgType\x12\x18\n" +
	"\aContent\x18\a \x01(\tR\aContent\x12\x12\n" +
	"\x04Time\x18\b \x01(\x03R\x04Time\"-\n" +
	"\x06IMMsgs\x12#\n" +
	"\x04Msgs\x18\x01 \x03(\v2\x0f.app.chat.IMMsgR\x04Msgs\"4\n" +
	"\rMessageIMNoti\x12#\n" +
	"\x04Msgs\x18\x03 \x03(\v2\x0f.app.chat.IMMsgR\x04Msgs\"E\n" +
	"\x11MessageNewMsgNoti\x12\x14\n" +
	"\x05MsgID\x18\x02 \x01(\x03R\x05MsgID\x12\x1a\n" +
	"\bReceiver\x18\x03 \x01(\x03R\bReceiver\"X\n" +
	"\x13MessageGroupMsgNoti\x12!\n" +
	"\x03Msg\x18\x01 \x01(\v2\x0f.app.chat.IMMsgR\x03Msg\x12\x1e\n" +
	"\n" +
	"AccountIDs\x18\x05 \x03(\x03R\n" +
	"AccountIDs\"i\n" +
	"\rWorldRoomInfo\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\x03R\x06RoomID\x12\x1c\n" +
	"\tMemberNum\x18\x02 \x01(\x05R\tMemberNum\x12\"\n" +
	"\fMaxMemberNum\x18\x03 \x01(\x05R\fMaxMemberNum\"\x81\x01\n" +
	"\x12NotificationReward\x12#\n" +
	"\rresource_type\x18\x01 \x01(\x05R\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\x03R\n" +
	"resourceId\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCount\"\xae\x02\n" +
	"\x10NotificationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x11notification_type\x18\x02 \x01(\x05R\x10notificationType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x03R\bexpireAt\x12\x1f\n" +
	"\vhas_rewards\x18\x06 \x01(\bR\n" +
	"hasRewards\x12\x18\n" +
	"\aclaimed\x18\a \x01(\bR\aclaimed\x126\n" +
	"\arewards\x18\b \x03(\v2\x1c.app.chat.NotificationRewardR\arewards\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt*K\n" +
	"\tgmChatOpt\x12\x10\n" +
	"\fChatOpt_None\x10\x00\x12\x15\n" +
	"\x11ChatOpt_GetForbid\x10\x01\x12\x15\n" +
	"\x11ChatOpt_SetForbid\x10\x02*\xf2\x01\n" +
	"\vMessageType\x12\x1a\n" +
	"\x16MessageType_Chat_Emoji\x10\x00\x12\x19\n" +
	"\x15MessageType_Chat_Text\x10\x01\x12\"\n" +
	"\x1eMessageType_Chat_TextFromSound\x10\x02\x12\x1f\n" +
	"\x1bMessageType_Chat_InviteTeam\x10\x03\x12!\n" +
	"\x1dMessageType_Chat_InviteLeague\x10\x04\x12 \n" +
	"\x1cMessageType_Chat_RoomDismiss\x10\x05\x12\"\n" +
	"\x1eMessageType_System_FriendAdded\x10\x06*#\n" +
	"\aEIMType\x12\v\n" +
	"\aIM_Peer\x10\x00\x12\v\n" +
	"\aIM_Room\x10\x04B\x14\xaa\x02\x11App.Protobuf.Chatb\x06proto3"

var (
	file_app_chat_chat_common_proto_rawDescOnce sync.Once
	file_app_chat_chat_common_proto_rawDescData []byte
)

func file_app_chat_chat_common_proto_rawDescGZIP() []byte {
	file_app_chat_chat_common_proto_rawDescOnce.Do(func() {
		file_app_chat_chat_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_chat_chat_common_proto_rawDesc), len(file_app_chat_chat_common_proto_rawDesc)))
	})
	return file_app_chat_chat_common_proto_rawDescData
}

var file_app_chat_chat_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_chat_chat_common_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_chat_chat_common_proto_goTypes = []any{
	(GmChatOpt)(0),                 // 0: app.chat.gmChatOpt
	(MessageType)(0),               // 1: app.chat.MessageType
	(EIMType)(0),                   // 2: app.chat.EIMType
	(*GRPCCommonResponse)(nil),     // 3: app.chat.GRPCCommonResponse
	(*GRPCPing)(nil),               // 4: app.chat.GRPCPing
	(*BaseNoti)(nil),               // 5: app.chat.BaseNoti
	(*RPCCommonNoti)(nil),          // 6: app.chat.RPCCommonNoti
	(*MessageRetNoti)(nil),         // 7: app.chat.MessageRetNoti
	(*CSCommonMessage)(nil),        // 8: app.chat.CSCommonMessage
	(*ChatText)(nil),               // 9: app.chat.ChatText
	(*ChatEmoji)(nil),              // 10: app.chat.ChatEmoji
	(*ChatTextFromSound)(nil),      // 11: app.chat.ChatTextFromSound
	(*ChatJoinLeagueAccepted)(nil), // 12: app.chat.ChatJoinLeagueAccepted
	(*IMMsg)(nil),                  // 13: app.chat.IMMsg
	(*IMMsgs)(nil),                 // 14: app.chat.IMMsgs
	(*MessageIMNoti)(nil),          // 15: app.chat.MessageIMNoti
	(*MessageNewMsgNoti)(nil),      // 16: app.chat.MessageNewMsgNoti
	(*MessageGroupMsgNoti)(nil),    // 17: app.chat.MessageGroupMsgNoti
	(*WorldRoomInfo)(nil),          // 18: app.chat.WorldRoomInfo
	(*NotificationReward)(nil),     // 19: app.chat.NotificationReward
	(*NotificationInfo)(nil),       // 20: app.chat.NotificationInfo
}
var file_app_chat_chat_common_proto_depIdxs = []int32{
	5,  // 0: app.chat.MessageRetNoti.Base:type_name -> app.chat.BaseNoti
	13, // 1: app.chat.IMMsgs.Msgs:type_name -> app.chat.IMMsg
	13, // 2: app.chat.MessageIMNoti.Msgs:type_name -> app.chat.IMMsg
	13, // 3: app.chat.MessageGroupMsgNoti.Msg:type_name -> app.chat.IMMsg
	19, // 4: app.chat.NotificationInfo.rewards:type_name -> app.chat.NotificationReward
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_app_chat_chat_common_proto_init() }
func file_app_chat_chat_common_proto_init() {
	if File_app_chat_chat_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_chat_chat_common_proto_rawDesc), len(file_app_chat_chat_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_chat_chat_common_proto_goTypes,
		DependencyIndexes: file_app_chat_chat_common_proto_depIdxs,
		EnumInfos:         file_app_chat_chat_common_proto_enumTypes,
		MessageInfos:      file_app_chat_chat_common_proto_msgTypes,
	}.Build()
	File_app_chat_chat_common_proto = out.File
	file_app_chat_chat_common_proto_goTypes = nil
	file_app_chat_chat_common_proto_depIdxs = nil
}
